README.md
pom.xml

Since we don't publish snapshots at the moment lets just use `DEVELOPMENT` and
stop bumping the version number for release until we get it automated.
This lets us just draft a release when we want to kick travis to upload to
maven central.

Lets stop bumping the version in the repo

---

detekt_baseline.xml
src/main/kotlin/com/expedia/graphql/annotations/GraphQLDirective.kt
src/main/kotlin/com/expedia/graphql/schema/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/schemaAnnotations.kt
src/main/kotlin/com/expedia/graphql/toSchema.kt
src/test/kotlin/com/expedia/graphql/schema/SchemaGeneratorTest.kt

Clean up the last detekt warnings. My next PR will actually fix the remaining base line ignores and delete the `detekt_baseline` file

Optimize imports and detekt warnings

---

.travis/deploy.sh

It looks like travis is checking things out in a headless branch mode when
building tags which is causing problems when the release plugin goes to fetch
the git symbolic ref.

Deploy needs to checkout a local branch

---

detekt_baseline.xml
src/main/kotlin/com/expedia/graphql/schema/exceptions/InvalidListTypeException.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kParameterExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/dataFetcherUtils.kt

Next I can pull out the specific type generators and have only the main methods like `graphqlTypeOf()` exposed on `SchemaGenerator`

refactor: move more functions out of SchemaGenerator

---

src/main/kotlin/com/expedia/graphql/schema/exceptions/ConflictingTypesException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/CouldNotGetJvmNameOfKTypeException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/CouldNotGetNameOfAnnotationException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/CouldNotGetNameOfEnumException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/GraphQLKotlinException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/InvalidInputFieldTypeException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/InvalidListTypeException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/InvalidSchemaException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/NestingNonNullTypeException.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/TypeNotSupportedException.kt

Creating a base exception for the entire library makes stack traces more clear and easier for clients to catch any exception while still being specific

feat: base exception

---

detekt_baseline.xml
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SubTypeMapper.kt
src/main/kotlin/com/expedia/graphql/schema/generator/TypesCache.kt
src/main/kotlin/com/expedia/graphql/schema/generator/models/KGraphQLType.kt
src/main/kotlin/com/expedia/graphql/toSchema.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorAsyncTests.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SubTypeMapperTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/TypesCacheTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/models/KGraphQLTypeTest.kt

General clean up
* Require queries and don't default to empty list since that causes an exception
* Return the filtered list from `SubTypeMapper` since all users were filtering anyway
* Move model package
* Fix some detekt issues

refactor: more clean up

---

pom.xml
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/WiringContext.kt
src/main/kotlin/com/expedia/graphql/schema/generator/directive/DirectiveWiringHelper.kt
src/main/kotlin/com/expedia/graphql/schema/hooks/SchemaGeneratorHooks.kt
src/test/kotlin/com/expedia/graphql/schema/generator/DirectiveTests.kt

This enables rewiring based on directives (see #60) by offering general purpose hooks that allows us to rewire/modify generated graphqltypes.
The base example for directive based authentication, would work with this:
https://www.graphql-java.com/documentation/v11/sdl-directives/
With this hook available I can then use a helper class such as this can be used to wire up the directives:
https://gist.github.com/d4rken/7cb60a6a7b315d25766ff15884f9b99b
The new hook has a placeholder `WiringContext` which would need to get some functionality to allow for feature parity with graphql-java's [`SchemaDirectiveEnvironment`](https://github.com/graphql-java/graphql-java/blob/5eb2ab743bf7afc05e2243d3dc0bcf22a0384366/src/main/java/graphql/schema/idl/SchemaDirectiveWiringEnvironment.java)
I was a bit out …

Additional SchemaGeneratorHook that allows modifying GraphQLTypes.

---

README.md

Update link to new graphql-java documentation location

---

example/src/main/kotlin/com.expedia.graphql.sample/model/Widget.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/ScalarQuery.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/booleanExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/fieldExtenstions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kParameterExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kPropertyExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/schemaFilters.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/EnumTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/FunctionTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/InputObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/InterfaceTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/ObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/PropertyTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/UnionTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/AnnotationExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/BooleanExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/FieldExtenstionsKtTest.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/KPropertyExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/KTypeExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaFiltersTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/types/PropertyTypeTest.kt

The issue was only with class properties. We couldn't set the annotation target because we also need the annotation to be valid on function arguments so classes still default the annotation to the constructor function arguments.
We need to check 4 possible annotation on a property:
* `@Deprecated`
* `@GraphQLDescription`
* `@GraphQLID`
* `@GraphQLIgnore`
The way I get around this is I first check if the property has the annotation, which is what we do right now so `@property:` prefixed annotations are handled first. If I can't find anything there I look at the parent class constructor, check it's arguments for a matching type (see  `KClass<*>.findConstructorParamter`), and return any annotations there, or default to null/false
A good example of the changes is in …

feat: remove requirement for @property: prefix

---

README.md
example/pom.xml
pom.xml

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/98

build: change group id to com.expedia

---

src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetJvmNameOfKTypeException.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfAnnotationException.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfEnumException.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfKClassException.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfKParameterException.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfKTypeException.kt
src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/directiveExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
src/main/kotlin/com/expedia/graphql/generator/state/TypesCacheKey.kt
src/main/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/InputObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/InterfaceTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/UnionTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/extensions/DeepNameKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/GraphQLTypeExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt

Pull out extension method for `simpleName` and `name` that return a non-nullable string and throw exceptions if it is null

refactor: extract simple name for better test coverage

---

example/src/main/kotlin/com.expedia.graphql.sample/Application.kt
src/main/kotlin/com/expedia/graphql/TopLevelObject.kt
src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/toSchema.kt
src/test/kotlin/com/expedia/graphql/ToSchemaKtTest.kt
src/test/kotlin/com/expedia/graphql/TopLevelObjectTest.kt
src/test/kotlin/com/expedia/graphql/dataFetchers/CustomDataFetcherTests.kt
src/test/kotlin/com/expedia/graphql/dataFetchers/DataFetchPredicateTests.kt
src/test/kotlin/com/expedia/graphql/generator/DirectiveTests.kt
src/test/kotlin/com/expedia/graphql/generator/PolymorphicTests.kt
src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorAsyncTests.kt
src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt

Drop all short hands and clever names for explict types

feat: rename TopLevelObject

---

src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/PropertyTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt

The graphql description was supposed to fall back to the description of the type of the argument if there was none. This was not working as we have to fall back to the KClass first.
Also I added more unit tests for getting the list type and array type and simplified the directives adding to state

fix: description of parameters

---

src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/toSchema.kt
src/test/kotlin/com/expedia/graphql/ToSchemaKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt

Move the query and mutation builder code to their own TypeBuilder class

refactor: create separate top level builders

---

example/src/main/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooks.kt
example/src/main/kotlin/com/expedia/graphql/sample/model/Node.kt
example/src/main/kotlin/com/expedia/graphql/sample/query/RecursiveQuery.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastToKClassException.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotGetNameOfKTypeException.kt
src/main/kotlin/com/expedia/graphql/exceptions/TypeNotSupportedException.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
src/main/kotlin/com/expedia/graphql/generator/types/ListTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/113
* Move the primitive types map to a single location
* Move extracting the cache name to extension functions
* Deleted unused exceptions

refactor: simplify type cache

---

README.md

The svg is being cached so the version is out of date. [shields.io](https://shields.io) has a much better cache update so I am using the same badge as Maven Central but changes the color, text, and link

Update javadoc badge

---

src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
src/main/kotlin/com/expedia/graphql/generator/types/InputObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/ListTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/ListTypeTest.kt

Internal changes only
By using the full input name in the cache we have less string building logic and it makes it easier to debug when you inspect the values
Inspecting the cache locally:
BEFORE
AFTER

refactor: use input name in cache

---

example/src/main/kotlin/com/expedia/graphql/sample/model/HidesInheritance.kt
example/src/main/kotlin/com/expedia/graphql/sample/query/PrivateInterfaceQuery.kt
src/main/kotlin/com/expedia/graphql/exceptions/InvalidMutationTypeException.kt
src/main/kotlin/com/expedia/graphql/exceptions/InvalidQueryTypeException.kt
src/main/kotlin/com/expedia/graphql/exceptions/InvalidSchemaException.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/ToSchemaKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilderTest.kt

Currently we are filtering non public properties and functions and don't expose them in the schema. We should have a consistent behavior for handling classes as well. With this change schema generator requires all query and mutation objects to have PUBLIC visibility modifier. Additionally, schema generator also won't include any non-public interfaces in the resulting schema.

Check if query and mutation classes are public

---

.gitignore
.travis.yml
.travis/deploy.sh
.travis/update-version.sh

With this change, on every tagged build, Travis will push a new branch back to GitHub that updates the pom in the library and the example to the snapshot of `tagVersion` + 0.0.1
We need to add the token as a secret key here: https://travis-ci.org/ExpediaDotCom/graphql-kotlin/settings which requires repo admin access

build: travis commits the snapshot updates

---

src/test/kotlin/com/expedia/IntegrationTests.kt
src/test/kotlin/com/expedia/graphql/integration/OptionalResultsTest.kt

Showed me that my error wasn't with this lib.
See #150
We have lot's of modular tests already, a few more integration tests can't hurt :smile: .

An integration test for optional results.

---

src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt

If a class was named `SearchInput`, we would map that to `SearchInputInput`. If devs are specifically naming it an input we should not duplicate the string

feat: do not append duplicate input suffix

---

src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastArgumentException.kt
src/main/kotlin/com/expedia/graphql/exceptions/InvalidInputFieldTypeException.kt
src/main/kotlin/com/expedia/graphql/execution/FunctionDataFetcher.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/suppressedExtenstions.kt
src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/SuppressedExtenstionsKtTest.kt

The new exception reads as following
```
com.expedia.graphql.exceptions.CouldNotCastArgumentException: Could not cast or map arguments in the data fetcher for parameter #1 items of fun com.expedia.graphql.execution.FunctionDataFetcherTest.MyClass.printList(kotlin.collections.List<kotlin.String>): kotlin.String
```
Also I added unit tests for the function data fetcher

feat: log a better exception on invalid argument types

---

example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
src/main/kotlin/com/expedia/graphql/SchemaGeneratorConfig.kt
src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/toSchema.kt
src/test/kotlin/com/expedia/graphql/execution/CustomDataFetcherTests.kt
src/test/kotlin/com/expedia/graphql/execution/DataFetchPredicateTests.kt
src/test/kotlin/com/expedia/graphql/generator/DirectiveTests.kt
src/test/kotlin/com/expedia/graphql/generator/PolymorphicTests.kt
src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorAsyncTests.kt
src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
src/test/kotlin/com/expedia/graphql/integration/OptionalResultsTest.kt

To prepare for subscriptions, I moved the order of the parameters in `toSchema()` so that `config` is first. This will allow us to easily add subscriptions as the optional final parameter. Also since we will have another option for a top level name I combined all the names into a single object

feat: update config settings for subscriptions

---

src/main/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
src/test/kotlin/com/expedia/graphql/generator/types/FunctionTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt

This will have no impact on existing clients. I just moved the handling of `CompletableFuture`s into the code so that it will always happen. Right now, clients need to remember to still handle `CompletableFuture`s if they override the hook.
We now resolve the type from the hook first, which defaults to the same type. Then we check after if it is on of the default supported wrapped types, which right now only includes `CompletableFuture`, but will extend to `Publisher` when we support subscriptions

fix: move the default handling of CompletableFuture

---

src/main/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilderTest.kt

fix: remove directive duplication in the generator

---

.travis.yml

It looks like the conditional for `deployment.on.jdk` is a single version not an array. This would make sense if we don't want both jobs to publish a jar
https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

fix: travis deployments are not running

---

.travis.yml

We could use this if we wanted to publish snapshots but we are not doing that anyway right now because our deploy script checks to see if there is `TRAVIS_TAG` so it never runs on master pushes

build: don't run deploy on master branch push

---

example/src/main/kotlin/com/expedia/graphql/sample/model/Animal.kt
src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/types/DirectiveTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/EnumTypeBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
src/test/kotlin/com/expedia/graphql/utils/CustomDirective.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/175
The new example code
```kotlin
@GraphQLDescription("enum holding all supported animal types")
@SimpleDirective
enum class AnimalType {
CAT,
@SimpleDirective
DOG
}
```
makes this schema in the SDL
```graphql
#enum holding all supported animal types
enum AnimalType @simpleDirective {
CAT
DOG @simpleDirective
}
```

fix: add directives on enum values

---

src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
src/test/kotlin/com/expedia/graphql/test/integration/NodeGraphTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/191
We are not going to resolve a type to a cached `GraphQLTypeReference`, instead we will try creating the full object or just create another `GraphQLTypeReference` if it still under construction.

fix: do not cache GraphQLTypeReference

---

src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KTypeExtensionsKtTest.kt
src/test/kotlin/com/expedia/graphql/generator/state/TypesCacheTest.kt

To simplify logic and make the cache simpler, we will not cache any list type. This means that the TypeCache is truly just caching fully qualified types. Lists will still be generated but they will not hit the cache to get their graphql type until they request a class.
This will also help if we want to support adding Sets to the types as it just becomes one location we have to update for all the valid list types

feat: do not cache list types

---

src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt

Currently `FunctionBuilder` includes all parameters except those annotated with `GraphQLContext` and those of type `DataFetchingEnvironment`: https://github.com/ExpediaDotCom/graphql-kotlin/blob/9915070a96b68d36528ee7cf28ba825e1e53dd85/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt#L38-L41
With this present change, `FunctionBuilder` would also ignore parameters annotated with `@GraphQLIgnore`.
What follows is my concrete use case in the context of a Spring app, but the change would be convenient in other situations as well.
===
The example in the repo resolves nested queries by virtue of a `lateinit var` field (see https://github.com/ExpediaDotCom/graphql-kotlin/blob/3132d8851d67f2147f08590207279841a74338ad/example/src/main/kotlin/com/expedia/graphql/sample/query/Ne …

FunctionBuilder ignores parameters annotated with GraphQLIgnore

---

src/main/kotlin/com/expedia/graphql/annotations/GraphQLName.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/test/kotlin/com/expedia/graphql/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/AnnotationExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/EnumBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/InputObjectBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/InterfaceBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/ObjectBuilderTest.kt
src/test/kotlin/com/expedia/graphql/generator/types/UnionBuilderTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/210
I went ahead and packaged my local changes into a PR, even before hearing back whether it's desirable in upstream. It might be useful to somebody else, regardless of whether it gets merged. Thanks.

Support custom names via @GraphQLName

---

example/src/main/kotlin/com/expedia/graphql/sample/query/PolymorphicQuery.kt
src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/filters/superclassFilters.kt
src/test/kotlin/com/expedia/graphql/generator/PolymorphicTests.kt

Fixes: https://github.com/ExpediaDotCom/graphql-kotlin/issues/220

fix: abstract classes should generate interface

---

src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
src/main/kotlin/com/expedia/graphql/generator/filters/superclassFilters.kt
src/main/kotlin/com/expedia/graphql/generator/types/MutationBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/QueryBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/SubscriptionBuilder.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt

Abstract classes can not be used as input. By moving the check to one location we can use the same logic across the library.

fix: abstract classes as input are invalid

---

src/main/kotlin/com/expedia/graphql/execution/FunctionDataFetcher.kt
src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt

This allows thrown `GraphQLException` instances to be handled by
`graph-java` as it would if thrown directly by a `DataFetcher` lambda.
---
I'm working on a prototype for an API gateway, a snippet of my login resolve is as follows
```kotlin
val body = /* Usernam and password json object*/
client.post(/* port */, /* domain */, /* path */)
.putHeader("Accept", "application/json")
.putHeader("Content-Type", "application/json")
.sendJsonObject(body, {ar -> tokenFuture.complete(ar); })
val response = tokenFuture.get()
val result = response.result()
if (result.statusCode() != 200) {
throw GraphQLException("Username and password combination failed.")
}
```
When Implementing directly with Graphql-Java's `DataFetchers` the error messages would appear as expected.
```json
{
"data": null,
"errors": …
```

FunctionDataFetch throws `InvocationException.cause` property when available

---

src/main/kotlin/com/expedia/graphql/exceptions/TypeNotSupportedException.kt

Update the exception message to be clear about the situations in which the exception can be thrown. One of the most common questions we get is around trying to use ` Map<>` which is not a valid type for a GraphQL schema.

fix: update TypeNotSupportedException message

---

src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/231
Adds a new hook that can be used to modify all the GraphQLTypes that get generated from reflection. This allows for runtime documentation or any other changes that may want to be made to types after they are fully generated

feat: new hook for modifying object types

---

example/src/main/kotlin/com/expedia/graphql/sample/query/NestedQueries.kt

Add more example that don't require the bean factory

example: add another nested example

---

src/main/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactory.kt
src/test/kotlin/com/expedia/graphql/directives/KotlinDirectiveWiringFactoryTest.kt

There are use cases when directives could be just informational (e.g. @deprecated). Instead of defining no-op directive wiring we should just ignore directives without wiring.

Revert throwing exception on missing directive wiring

---

.travis.yml

I accidentally copied over the scripts steps from the master branch which changed the structure of the repo. In the `0.6.x` branch we still want to verify the example repo

Add back the example script step

---

pom.xml

Set the profiles for release and javadoc to only run on the schema-generator module as the example app doesn't need to be published

publish only the schema-generator module

---

graphql-kotlin-spring-example/pom.xml
pom.xml

Additional configuration fixes:
* remove maven-javadoc-plugin as dokka already genertes the javadoc jar
* explicitly disable maven-deploy-plugin as we are using nexus-staging-maven-plugin with explicit config
* skip generating sources for the example app

Explicitly disable nexus-staging-maven-plugin in example app

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/annotations/GraphQLName.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kCallableExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InputObjectBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/extensions/GraphQLSchemaExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/AnnotationExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KCallableExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KPropertyExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/248
Use `@GraphQLName` to set the name of fields in the schema, not just type names

feat: allow renaming of properties and functions

---

.travis/update-version.sh

versions-maven-plugin is unable to automatically increment snapshot versions of non-standard version project (e.g. 1.0.0-RC1-SNAPSHOT).

fix: use maven release plugin in update-version.sh travis script

---

pom.xml

Based on nexus-staging-maven-plugin it appears that plugin may not release the artifacts if last module (in our case example app) has it disabled. As I workaround I created defaultBuild profile (active by default) that includes example app but if any other profile is specified (e.g. -P release) then default one will be automatically disabled. This will allow us to release only schema generator module.

exclude example app from release profile

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/UnionBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/PolymorphicTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt

* devs can use @GraphQLName annotation to rename the underlying types - this change updates interface and union type resolvers to retrieve correct name when resolving the types
* update SchemaGeneratorHooks.didGenerateGraphQLType method to return the generated type instead of returning Unit, this makes it consistent with return type of other hook methods

Fix type resolvers for renamed polymorphic types and fix hooks signature

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/state/SchemaGeneratorState.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/DirectiveBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/DirectiveBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/directives/CakeOnly.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/directives/CustomDirectiveWiringFactory.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/directives/SpecificValueOnly.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/directives/SpecificValueOnlySchemaDirectiveWiring.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/query/CustomDirectiveQuery.kt

Directive definitions should only be added to the schema once - while building the schema we are caching the directive definitions and add them after processing all the objects. Our current logic relies on this cache to not-rebuild the directives per each one of its declarations. Directives can have arguments which means that we have to rebuild the directive definition if they accept any arguments.

fix: directives with arguments should be created per declaration

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/state/SchemaGeneratorState.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/InterfaceBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/ObjectBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/UnionBuilderTest.kt

`graphql-java` requires all `GraphQLObjectType`, `GraphQLInterfaceType` and `GraphQLUnionType` types to have unique names within a schema. While generating the schemas based on the reflections we have to ensure that each one of those objects is build only once. Since underlying objects do not implement hashcode it leads to problems if we attempt to update the fields through some hooks (e.g. use `newBuilder(existingObject)`). In order to make sure we only build those objects once we implemented basic caching logic in our builders - when we start building the target object we put it under construction and after it is build we add it to the cache and mark it completed.
Unfortunately, existing logic was flawed - all objects were being put under construction but only `GraphQLObjectType`s …

fix: properly cache GraphQL object/interfaces/union types

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/ObjectBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/QueryBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/UnionBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt

InterfaceBuilder attempts to create all the implementing `GraphQLObjectType`s after building an interface but before executing the `willAddGraphQLTypeToSchema` hook. This means that if we attempt to update the interface in that hook there could be some objects implementing that interface and referencing the old one. Since graphql-java schema objects don't implement hashcode we end up with type conflict of two interfaces being defined in the schema.
Fix is to use `GraphQLTypeReference` when referencing `GraphQLInterfaceType` from the `GraphQLObjectType` builder. Reference is just by name and they are resolved as the last step of building a schema. This allows us to modify the interface in the hook.
Resolves: https://github.com/ExpediaDotCom/graphql-kotlin/issues/281

fix: allow modifying GraphQLInterfaceType in the willAddGraphQLTypeToSchema hook

---

codecov.yml

Instead of deleting the tests, we can just exclude this project from the reports
This is the previous PR https://github.com/ExpediaDotCom/graphql-kotlin/pull/290

chore: exclude the example app from code coverage

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SubTypeMapper.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kFunctionExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/state/TypesCache.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/ObjectBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/UnionBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KFunctionExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/UnionBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/hooks/SchemaGeneratorHooksTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/test/integration/RecursiveInterfaceTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/294
Interfaces now go through the internal TypeBuilder method 'graphQLTypeOf' instead of 'objectFromReflection'. This means we can make 'objectFromReflection' private. But the type may be (if not always) wrapped in a GraphQLNonNull which means we have to cast it back to the interface type before adding it to the ObjectBuilder.

fix: *generateGraphQLType hooks are now called on interfaces

---

graphql-kotlin-spring-example/pom.xml

Update the example application to include the spring maven plugin
This allows us to use
```
mvn spring-boot:run
```
instead of
```
mvn org.springframework.boot:spring-boot-maven-plugin:run
```

Spring boot example was missing the plugin to work correctly

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kParameterExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/ArgumentBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/FunctionBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/extensions/GraphQLSchemaExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/extensions/KParameterExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/ArgumentBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/FunctionBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/249
Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/318
Resolve the two bugs and refactor the function to its own ArgumentBuilder so we can more easily test the bugs

Fix bugs with generating arguments

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/extensions/kPropertyExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/DirectiveBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InputObjectBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/InputPropertyBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/types/PropertyBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/DirectiveBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/InputPropertyBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/PropertyBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/generator/types/TypeTestHelper.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/278
Property (input/output) directives are now resolved by checking the property and the constructor argument for any directives. This is the same pattern for checking any other annotations we have

Directives on constructor args with no prefix

---

examples/federation/base-app/src/main/kotlin/com/expedia/graphql/sample/Application.kt
examples/federation/base-app/src/main/kotlin/com/expedia/graphql/sample/query/NestedQuery.kt
examples/spring/pom.xml
graphql-kotlin-federation/src/main/kotlin/com/expedia/graphql/federation/execution/FederatedTypeRegistry.kt
graphql-kotlin-federation/src/test/kotlin/com/expedia/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expedia/graphql/federation/execution/EntityQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expedia/graphql/federation/execution/ServiceQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/test/data/queries/simple/NestedQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expedia/graphql/generator/TypeBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expedia/graphql/test/integration/NodeGraphTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/310
While I don't think it is possible to have an input type extended we should still be able to have nested types that are not part of the federated entities be generated properly. This can happen when there are lists of nullalbes or double wrapped elements

Fix nested federation

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/resolvers.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/exception/FederatedRequestFailureTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/FieldSetTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/ServiceTest.kt

Add some unit tests for non-covered files to get us higher before the 1.0.0 release
No code changes, just move and add test files

add more test coverage for federation

---

graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinFieldDirectiveEnvironment.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinSchemaDirectiveEnvironment.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinFieldDirectiveEnvironmentTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinSchemaDirectiveEnvironmentTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilderTest.kt

Add more unit tests and remove duplicate default values to increase code coverage

Increase code coverage

---

README.md
graphql-kotlin-federation/README.md
graphql-kotlin-schema-generator/README.md

Update the maven central badges and javadocs links for each module, also remove the maven central badge for the main README since `graphql-kotlin` is not a published library

Update READMEs with new maven central link

---

graphql-kotlin-federation/pom.xml

Hi, we just noticed that the junit dependency was not marked as test dependency.
What do you think?
best regards
Lars

Mark junit as test scoped dependency

---

CONTRIBUTING.md
README.md

Add some more details in the main README to align with the Expedia Group OSS templates and provide some more details to first time viewers. Also update the CONTRIBUTING doc with more details
https://github.com/ExpediaGroup/new-project

Add usage in the main README

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/query/ScalarQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidIdTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ArgumentBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/ScalarBuilderTest.kt

Due to deserialization issues that can happen with UUID, we are only going to support Strings as the explicit type for GraphQLID. You can still use UUID in your data fetchers but you will have to do the parsing yourself and handle the exceptions if it is not a valid UUID.
Example of client input
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/317

BREAKING CHANGE: Change GraphQLID to only use strings

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/context/MyGraphQLContextFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/GraphQLContextFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilterTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt

Abstracts creation of GraphQL context by introducing GraphQLContextFactory interface and provides default WebFilter that utilizes it to populate GraphQL context in the reactor subscriber context.
https://github.com/ExpediaGroup/graphql-kotlin/pull/329 - Add new module graphql-kotlin-spring-server

feature: abstract away creation of GraphQL context

---

CONTRIBUTING.md

Per the EG Open Source docs, we need to have this header on all source files.

Update CONTRIBUTING.md with license header

---

graphql-kotlin-federation/README.md
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExtendsDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExternalDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ProvidesDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/RequiresDirective.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorKeyDirectiveTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorProvidesDirectiveTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorRequiresDirectiveTest.kt
graphql-kotlin-federation/src/test/kotlin/test/data/queries/federated/Product.kt

Removes unnecessary `@property:` prefix from the annotations
* https://github.com/ExpediaGroup/graphql-kotlin/pull/320 - Directives on constructor args with no prefix

federation documentation cleanup

---

.travis/update-version.sh
examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

Fix the script to update all pom files and check in all the files to git. Also update to the correct versions that was not done in the last build
https://github.com/ExpediaGroup/graphql-kotlin/pull/350

Fix travis script to update versions

---

graphql-kotlin-spring-server/README.md

docs: Query and Mutation should be marker interfaces rather than annotations

docs: Query and Mutation should be marker interfaces

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/context/MyGraphQLContextFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/GraphQLContextFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandler.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilterTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt

`graphql-kotlin-spring-server` updates:
- update `GraphQLContextFactory` to use coroutines for building the context
- extract `SubscriptionHandler` logic from default `WebSocketHandler`, default subscription `WebSocketHandler` will now call available `SubscriberHandler` bean
- update `SimpleSubscriptionHandler` to use `GraphQLContext` - fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/360
- add error handling to `SimpleSubscriptionHandler`
https://github.com/ExpediaGroup/graphql-kotlin/issues/360

spring server updates

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/exceptions/CustomDataFetcherExceptionHandler.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/query/DataAndErrors.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/KotlinDataFetcherExceptionHandler.kt

By default, our default exception handler was wrapping all the runtime exceptions in `graphql-java` `ExceptionWhileDataFetching` GraphQLError. Since this default GraphQL error exposes `exception` field it was also getting serialized in the response. While this is was still valid GraphQL response, per [spec](https://graphql.github.io/graphql-spec/June2018/#sec-Errors) `exception` field is not part of the defined error fields and instead should be included in the error `extensions` entry field instead (if at all).
Note: the above serialization issue could also be solved by using `graphql-java` `ExecutionResult#toSpecification` method to generate final results but that would also imply that we would need to return `Map` instead of a `GraphQLResponse`. …

Update default exception handler to use SimpleKotlinGraphQLError

---

detekt.yml
examples/spring/src/main/kotlin/com/expediagroup/graphql/sample/subscriptions/SimpleSubscription.kt
examples/spring/src/main/resources/application.yml
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/UknownSubscriptionOperationType.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/SubscriptionOperationMessage.kt
graphql-kotlin-spring-server/src/main/resources/META-INF/spring-configuration-metadata.json
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt

Support the messages that come from the Apollo client subscriptions.
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md
We need to wrap the GraphQLRequest and GraphQLResponse in a special message before we send it over the web socket. That message structure is implemented in the handler for the `graphql-ws` protocol
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/370

Fix Apollo subscription message handling

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaValidator.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLDirectiveContainerExtensions.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Any.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateFieldSelection.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateKeySetField.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateRequiresDirective.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateDirectiveKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateFieldSelectionKtTest.kt
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
pom.xml

One last bump of unit test coverage and update our dependencies before the 1.0.0 release

Upgrade library versions and unit tests

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt

Open FederatedSchemaGenerator so that it can be inherited from.
#384

Make FederatedSchemaGenerator open

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/test/data/queries/federated/Product.kt

Add tests that verify that generated federated schema does not return custom directives in the `_service { sdl }` query.
https://github.com/ExpediaGroup/graphql-kotlin/issues/373
https://github.com/ExpediaGroup/graphql-kotlin/pull/374

federation: add tests to verify custom directive support

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/QueryHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerTest.kt

Update the exception message to include the path and original exception message

spring-server: include path in SimpleKotlinGraphQLError error message

---

graphql-kotlin-spring-server/README.md

Update the readme example with missing `@Component` annotation

Missing @Component in ReadMe example

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt

`graphql-java` allows for applying various `Instrumentations` to the GraphQL execution. If multilple instrumentations are to be applied they need to be wrapped in an instance of `ChainedInstrumentation` that has an explicit order of the instrumentations.
In order to simplify Spring configuration we should allow users to either create a single instrumentation bean (could be a chained one) or multiple instrumentation beans and then automatically wrap them in chained instrumentation if necessary. Unfortunately, by default `graphql-java` `Instrumentation` does not specify order in which it should be applied (as it is generally explicitly configured). In order to support proper ordering of the instrumentations we can simply check if they implement `Ordered` interface and use their order value …

[spring-server] enable support for specifying instrumentation order

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLRequest.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLRequestTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponseKtTest.kt

When creating new `ExecutionInput` we should automatically register `DataLoaderRegistry` if it is present in the application context.
https://github.com/ExpediaGroup/graphql-kotlin/issues/381
https://github.com/ExpediaGroup/graphql-kotlin/pull/396

[spring-server] SimplQueryHandler support for DataLoaderRegistry

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorProvidesDirectiveTest.kt

When generating federated GraphQL schema we attempt to validate the generated objects. This is problematic when we are dealing with nested relationships as at validation time, those objects are still being built so we only have access to their `GraphQLTypeReference`. Those references are replaced as the last step of schema generation lifecycle which means we won't be able to perform any validations on those objects when they are still being built. This PR disables the validation of `@provides` directive when it references objects that are still being built.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/397

[federation] skip validation of nested objects under construction

---

codecov.yml

Update the code coverage reports so they don't need to be checked on documentation updates

Exclude docs from coverage reports/checks

---

graphql-kotlin-federation/README.md
graphql-kotlin-schema-generator/README.md
graphql-kotlin-spring-server/README.md

Update docs link in other READMEs

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/DataLoaderRegistryFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt

Instance of `DataLoaderRegistry` should be created per GraphQL query execution instead of being a singleton. Developers can create their custom instance of `DataLoaderRegistry` by providing custom `DataLoaderRegistryFactory` bean.
https://github.com/ExpediaGroup/graphql-kotlin/issues/381
https://github.com/ExpediaGroup/graphql-kotlin/pull/396
https://github.com/ExpediaGroup/graphql-kotlin/pull/400

[spring-server] support for creating data loader registry per execution

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/DataLoaderConfiguration.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Organization.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/OrganizationQuery.kt

I've asked about using dataLoaders in the related issue, so here is my example of its possible implementation, using an extension of a query handler. What do you think?
Note that I also made ExecutionResult.toGraphQLResponse() function public in this PR.
https://github.com/ExpediaGroup/graphql-kotlin/issues/381

Example of DataLoaders.

---

docs/getting-started.md

Added Javadoc links for the three libraries

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt

Federated GraphQL gateway can contain number of services that are not exposing any of their types as federated types (i.e. without exposing any of them using @key directives). We were incorrectly generating SDL only if there were some federated types in the generated schema. Fix is to always generated the SDL.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/416

[federation] fix: SDL should be generated for non-federated schemas

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt

In our default GraphQL route we were explicitly checking if `Content-Type` header is just `application/json`. If request was also specifying charset, e.g. `application/json;charset=UTF-8` our logic would fail to match it and result in HTTP 400 (Bad Request) response.

[spring-server] fix: handle graphql request with charset coding

---

examples/federation/README.md

The current link was causing a 404 as it was using an absolute path
None

Fixed link to Gateway Readme

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/README.md
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

Move the declared version of spring-boot to the root so we use the same version across all the modules and examples
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/429

Move spring-boot version to single location

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponseKtTest.kt

📝 Description
Refer https://github.com/ExpediaGroup/graphql-kotlin/issues/423#issuecomment-539622384 for the cause
The fix includes setting `stackTrace` to an empty array when the error type is a `ValidationError` and a `NonNullableValueCoercedAsNullException` was thrown
🔗 Related Issues
Resolves #423

[spring-server] fix: Exclude stacktraces when null values are specified for non-null parameters

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidInterfaceException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/filters/superclassFilters.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/InterfaceOfInterfaceTest.kt

According to the spec, an interface can not implement another interface. This is not caught by our schema generator but instead just returns the first level interface as the type in the schema. We are now throwing an exception to help translate this understanding of GraphQL through the Kotlin code
Is this a breaking change? Someone may be using 1.0.0 today and just by updating their version they will have to fix something.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/419

Throw exception on multi-level interface

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/SchemaGeneratorConfig.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/NoopSchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt

`SchemaGeneratorConfig`/`FederatedSchemaGeneratorConfig` auto config beans now accept optional parameters to set custom hooks, data fetcher factory provider and top level names.

[spring-server] simplify schema configuration auto configuration

---

.github/workflows/maven.yml
.travis.yml

* update Github CI Action to run verify goal instead of just package
* prevent Travis from running install goal twice - by default Travis will attempt to install the dependencies before running the actual build script, this results in running `mvn install` goal twice: once for installing dependencies and skipping the tests and another one from our build script. This PR disables the default dependency installation goal.

[chore] continous integration build upgrade

---

examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
examples/spring/src/main/resources/application.yml
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
graphql-kotlin-spring-server/src/main/resources/META-INF/spring-configuration-metadata.json
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt

SpringBoot 2.2 supports using immutable data classes for `ConfigurationProperties` by specifying `@ConstructorBinding`.

[spring-server] use data classes for configuration properties

---

graphql-kotlin-federation/pom.xml
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestResolvers.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestSchema.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/federated/Product.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/simple/NestedQuery.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/simple/SimpleQuery.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/EntityQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/FederatedQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SubTypeMapper.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SubTypeMapperTest.kt
pom.xml

There is a security issue with one of the dependencies of `org.reflections:reflection:0.9.11`. Instead of resolving the dep issue we should migrate away from this library since the last version was released in 2017.
https://github.com/classgraph/classgraph is an active supported library with reported faster implementation of reflection.
The security issue was in `com.google.guava:guava:20.0` but since we were still using some guava code in our library I have added `com.google.guava:guava:28-jre` as an explicit dependency
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/449

Remove reflections lib in favor of ClassGraph

---

.github/workflows/maven.yml
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SubTypeMapper.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt

Migrate the actions Maven check to java 11
Also per this issue, we should be running ScanResult::close if we no longer need to use the reflection results: classgraph/classgraph#331

Fix GH actions PR check

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt

New configuration properties:
* `graphql.sdl.enabled` - Boolean flag to indicate whether SDL endpoint should be enabled, defaults to true
* `graphql.sdl.endpoint` - SDL endpoint, defaults to /sdl

[spring-server] make sdl endpoint customizable

---

docs/server/spring-beans.md
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SchemaConfigurationTest.kt

ContextWebFilter is now an open class so it can be easily extended. Default implementation is now conditionally created.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/452

[spring-server] make ContextWebFilter conditionally created

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
pom.xml

With 2.2.1.RELEASE SpringBoot team changed the behavior that was automatically applying constructor binding to all classes referenced from the top level properties. New behavior requires explicitly specifying that we want to use constructor binding on all classes.
See https://github.com/spring-projects/spring-boot/issues/18919 for more details

[spring-server] upgrade to SpringBoot 2.2.1.RELEASE

---

graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSubscriptionTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilderTest.kt
pom.xml

Subscriptions must return a `org.reactivestreams.Publisher` for graphql-java to work properly. An exception will now be thrown if any return type of a top level subscription is not a subclass of Publisher
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/359

Validate subscription return type

---

pom.xml

In order to release to nexus we need to publish Javadocs. Currently dokka only works for JDK8 so we had it explicitly gated behind a profile that would only be activated when run using Java 8. Since we are explicitly gating Travis release job to run on Java 8 only so we don't need this separate profile.

[chore] move dokka configuration to release profile

---

examples/federation/extend-app/src/main/kotlin/com/expediagroup/graphql/examples/extend/Widget.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/FederatedTypeResolver.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/resolvers.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestResolvers.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/EntityQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ResolversKtTest.kt

When resolving the federated types we currently don't have access to GraphQLContext. GraphQLContext can contain some important information (e.g. related to auth) that might be needed for type resolution so the resolvers should be able to access it. This PR updates the `FederatedTypeResolver` interface to also accept `DataFetchingEnvironment` when batch resolving the types.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/472

[federation] federated type resolvers should have access to environment

---

README.md

Add links to slack channel and how to join Kotlin slack instance

Add slack info to README

---

examples/spring/src/main/resources/application.yml
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt

Filter out request over http that contain websocket headers and lower the order for when the ws:// protocol is handled so you can have both `http://app/graphql` and `ws://app/graphql`
Fixes #484

Allow for subscription request on the same endpoint

---

docs/customizing-schemas/renaming-fields.md
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/InputObjectBuilderTest.kt

Currently we can only parse renamed input class fields if they include the Jackson annotation @JsonProperty. This is because when we get the java class for the argument it doesn't have any information for jackson to know that the constructor field has been renamed. I tried looking into adding a custom deserializer but we can't dynamically have one for all classes. Until we can find a better solution this unit test serves as documentation for the only way to make this work for now
https://github.com/ExpediaGroup/graphql-kotlin/issues/493

Add unit tests for renaming input type fields

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt

On startup of server, prepend a newline so the schema is slightly more readable

Log schema with starting newline

---

.github/workflows/publish-docs.yml

Update the action to use tokens provided in the environment instead of custom ones

Update publish-docs to use github tokens

---

.github/workflows/publish-docs.yml

Reverts ExpediaGroup/graphql-kotlin#504
We need to use the token of a verified user that has admin access to our repo to publish to Github Pages
So we can not use the auto token for Actions, we are going back to using @eg-oss-ci 
https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#troubleshooting-publishing-problems-with-your-github-pages-site

Revert "Update publish-docs to use github tokens"

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt

Refactor of the websocket logic to keep sending the keep alive messages until the client calls `connection terminate`.
Clients can open a connection with `GQL_CONNECTION_INIT` but never call `GQL_START`. The keep alive messages from the server should still be sent in that case, which also means we don't need to save the websocket session. We can just stop the session only on `GQL_CONNECTION_TERMINATE`
This also cleans up the keep alive connections after `GQL_STOP` is sent by the client or the server sends `GQL_CONNECTION_ERROR`
https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md
* https://github.com/ExpediaGroup/graphql-kotlin/pull/510
* https://github.com/ExpediaGroup/graphql-kotlin/issues/499

Do not close session on subscription GQL_STOP

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionStateTest.kt

Please merge this first: https://github.com/ExpediaGroup/graphql-kotlin/pull/514
Move the saving of subscriptions to a separate class so we can verify the logic with unit tests and simplify the`ApolloSubscriptionProtocolHandler`. This also exposed a bug that we were not saving the operation subscriptions to be stopped properly. This is now covered by the unit tests
* Builds on top of https://github.com/ExpediaGroup/graphql-kotlin/pull/514 for testing purposes
* Hopefully will help with subscription performance: #499

Fix subscription caching logic

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt

#141 # :pencil: Description
Prevent starting second subscription with the same id, remove he complete message as it's not needed, and probably preventing flux from closing. Validated this will solve the problems, as it finally ran longer than 2 minutes.
https://github.com/ExpediaGroup/graphql-kotlin/issues/499

Prevent starting second subscription with the same id

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/MutationBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/QueryBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/MutationBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/QueryBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt

Update SchemaGeneratorHooks interface to specify target kClass info for isValidProperty, isValidFunction, didGenerateQueryType, didGenerateMutationType and didGenerateSubscriptionType hooks.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/526

[generator] update generator hooks to include target kclass info

---

detekt.yml
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/toFederatedSchema.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/TestSchema.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/FederatedQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/EmptyInputObjectTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/EmptyInterfaceTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/EmptyMutationTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/EmptyObjectTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/EmptyQueryTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/EmptySubscriptionTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/MutationBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/QueryBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilder.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/MutationBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/QueryBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/SubscriptionBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/UnionBuilderTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt

GraphQL specification requires Query type to be present as it is required to run introspection query. Per specification it also shouldn't be possible to generate empty complex types (objects, input objects or interfaces) and they should expose at least a single field. Since root Query type is a special GraphQLObjectType it also has to expose at least a single field.
Breaking changes:
* at least single Query is required when generating the schema
* split `didGenerateQueryType` hook (and corresponding `Mutation` and `Subscription` hooks) into `didGenerateQueryFieldType` (previous functionality) and `didGenerateQueryObjectType` hooks to allow more granular control when generating the schema
* default `SchemaGeneratorHooks` now performs validation of generated object types (including special …

BREAKING CHANGE: empty complex types should fail schema generation

---

build.gradle.kts

Per https://central.sonatype.org/pages/requirements.html generated `pom.xml` file should contain following metadata:
* coordinates (i.e. groupId, artifactId and version)
* project name (adding)
* project description (adding)
* project url
* license
* developer info
* scm

[build] add missing sonatype information

---

CONTRIBUTING.md
build.gradle.kts
examples/federation/base-app/README.md
examples/federation/extend-app/README.md
examples/spring/README.md
gradle.properties
graphql-kotlin-spring-server/build.gradle.kts
settings.gradle.kts

`maven-publish` plugin only uploads to nexus staging but does not release the artifacts which means ithe release process requires an extra manual step (i.e. log into nexus web ui and release). `nexus-staging` plugin automates this proces by allowing you to automatically release published artifacts to nexus (i.e. similar to what maven `nexus-staging-maven-plugin`).
Updated build process so the `publish` task is finalized by `closeAndReleaseRepository` task.

[build] configure nexus-staging plugin

---

.github/workflows/release.yml
build.gradle.kts

Also changes release workflow to an explicit task invocation.

[build] add missing credentials to nexus-staging plugin config

---

build.gradle.kts
docs/contributors/release-proc.md
gradle.properties
settings.gradle.kts

Currently Gradle publish task is not using staging repository ID when publishing to Sonatype Maven Central (see: https://github.com/gradle/gradle/issues/5711). Furthermore, Gradle publish does not automatically release artifacts from Sonatype staging directory and requires manual step to finalize the release (i.e. log in to Sonatype repository and release uploaded staged artifacts).
As a workaround, in order to automatically publish to Maven Central we need to apply:
* `nexus-publish-plugin` - to explicitly create Sonatype staging ID prior to publishing artifacts (needed by `nexus-staging-plugin` to work reliably)
* `nexus-staging-plugin` - to explicitly close and release libs triggering the automatic Maven Central release
NOTE: It appears that shortcomings of Gradle `maven-publish` …

[build] apply nexus-publish plugin to explicitly create sonatype staging

---

build.gradle.kts

Gradle `publish` task now explicitly depends on the `initializeSonatypeStagingRepository` task from `nexus-publish-plugin`. We need to explicitly set this as we are not publishing any artifacts from the root project.

[build] explicitly configure nexus-publish-plugin on root project

---

build.gradle.kts

It appears that maven-publish plugin will skip its execution if repositories are not configured in given project. Changing the configuration to apply nexus-publish plugin on all projects.

[build] apply nexus-publish plugin on ALL projects

---

.gitignore
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Any.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Entity.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_FieldSet.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Service.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidator.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorTest.kt

To cleanup our public class, function, and value exposure, I moved some of the federation objects to internal scope since they do not need to be exposed as public

[federation] Move vals and functions to internal scope

---

examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/PolymorphicQueryIT.kt
gradle.properties
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/data/queries/federated/Product.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/ServiceTest.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactory.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/CouldNotCastGraphQLSchemaElement.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/graphQLExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/KGraphQLType.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactoryTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/DeepNameKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorAsyncTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/KGraphQLTypeTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/TypesCacheTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateListTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt

Upgrading to graphql-java 14 requires some breaking changes: https://github.com/graphql-java/graphql-java/releases/tag/v14.0
The biggest change is that the SDL descriptions are now printed with `"Comments"` instead of `#Comment`. So we needed to update a few integration tests and our regex in federation that inspects the schema. This PR would make it a lot simpler, but it can be merged later: https://github.com/graphql-java/graphql-java/pull/1756
The other big change is in the underlying schema code and how a `GraphQLType` has been split up into `GraphQLType` and `GraphQLNamedType`, and how some elements of execution use the new type `GraphQLSchemaElement` instead of `GraphQLType`. We were able to hide most of this behind the generator but there are some breaking changes to our library …

Upgrade to graphql-java 14

---

CONTRIBUTING.md
docs/examples.md
examples/federation/README.md
examples/federation/base-app/README.md
examples/federation/extend-app/README.md
examples/spring/README.md
gradle.properties
graphql-kotlin-schema-generator/build.gradle.kts

Update various dependencies. The only minor version update is for JUnit, detekt, and ktlint so there shouldn't be any library code we need to update to take advantage of new features. At the same time, I cleaned up a couple docs and README files that reference maven still.
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/566
* Kotlin: https://blog.jetbrains.com/kotlin/2019/11/kotlin-1-3-60-released/
* Kotlin coroutines: https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.3.3
* Jackson: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.2
* Spring Boot: https://spring.io/blog/2020/01/20/spring-boot-2-2-4-released
* Classgraph: https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.60
* Reactor: …

Update dependency versions and docs

---

build.gradle.kts
gradle.properties

Increase the default timeout of publish to 5 minutes (60 attempts at 5 seconds)
Failed publish: https://github.com/ExpediaGroup/graphql-kotlin/commit/f4cd12841d8b85df8dbe5c9294322d59e9ff6e9f/checks?check_suite_id=416873727

[build] Update nexus publish timeout

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties

There is a bug with Gradle 6 and Nexus 2 currently that we can fix by setting a systemProp. 
See here for more info: https://github.com/gradle/gradle/issues/11308

Set gradle prop to fix release process

---

.github/workflows/release.yml

The step actions/cache does not support the release event.
See: https://github.com/actions/cache/blob/b45d91cc4bac5c58ff24b19cd3b6711b2c5eca8f/src/utils/actionUtils.ts#L98
And our logs: https://github.com/ExpediaGroup/graphql-kotlin/runs/408004612\?check_suite_focus\=true\#step:5:10

Remove actions/cache from release

---

docs/spring-server/subscriptions.md

Fixed link to example code: `.../sample/...` -> `.../examples/...`

Fixed URL to Subscription example

---

.github/workflows/continuous-integration.yml

Instead of using a Github App on the repo, we can move to use the new GH Action release-drafter so the release notes are updated on every merge to master
This runs in parallel with the gradle build so it does not block.
See https://github.com/release-drafter/release-drafter
The release-drafter team as plans on removing the GH App eventually: https://github.com/release-drafter/release-drafter/issues/335

Add release notes step in GH Actions

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt

Open the internal methods to the protected scope so that we can more easily override specific methods to provide more features. Internally to Expedia Group we have the need to provide a `CustomFunctionDataFetcher` that overrides the get method. However we don't want to have to reimplement all the other methods as well that convert the classes and parse the arguments. Right now we are actually missing out on using the new feature to use List over array for input types. This could be fixed internally but it is already done in open source so we would like to take advantage of that.
Also this will now allow users to override the coroutine context that is used for suspending functions without having to create an entirely new data fetcher implementation.
For context I found this more helpful …

feat: open FunctionDataFetcher methods for extension

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateProvidesDirective.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/graphqlTypeExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateGraphQLType.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateObject.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateUnion.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphqlTypeExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/filters/SuperclassFiltersKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt

This is a patch change to allow additional types to more easily be extended in later PRs. As a side-effect of this change we actually simplify where types are all generated and the main generateSchema function becomes just a little more straight forward.
This will make https://github.com/ExpediaGroup/graphql-kotlin/pull/585 a little eaiser to implement

Allow additional types to be added with custom SchemaGenerator

---

examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/query/SimpleQuery.kt
examples/federation/gateway/.gitignore
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/DeprecatedDirectiveExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt

`graphql-java` now adds `@deprecated` directive definition automatically so we dont have to explicitly add it anymore. This change also fixes handling of multiline directive definition declaration in the federation library.
I verified locally that our federation example still works fine with deprecated query. Unsure if this integration test (i.e. starting up 2 SpringBoot apps and node gateway and then running HTTP request) is something we can automate. Posted a question about it on Github forum: https://github.community/t5/GitHub-Actions/integration-test-that-starts-multiple-apps/m-p/44918#M5969
Related issue: https://github.com/graphql-java/graphql-java/issues/1598

[generator] deprecated directive cleanup

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt

As discussed in other PRs #587 and #585 we can allow developers to have more customization of the schema by allowing them to add additional types of their own without having to add it to the schema directly. What they do with this feature will be up to them, but from a library perspective it is not bad feature to support.
See my comment here for more details: https://github.com/ExpediaGroup/graphql-kotlin/pull/585#discussion_r374316867

Allow updating custom additional types

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/TrackTimesInvoked.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/instrumentation/TrackTimesInvokedInstrumentation.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/StressQuery.kt

Add a `StressQuery` that will create a lot of nodes so we can stress test data fetchers with a single query instead of lots of requests. 
This will help us debug performance overhead around `PropertyDataFetcher` vs `FunctionDataFetcher` vs `suspend FunctionDataFetcher`
I used YourKit locally to get a snapshot of each query. The files are too big to upload but I am looking at the results right now
```graphql
query stress {
stressNode(count:100000) {
valueId
}
}
```
```graphql
query stress {
stressNode(count:100000) {
functionId
}
}
```
```graphql
query stress {
stressNode(count:100000) {
suspendId
}
}
```

Add example stress query

---

docs/execution/async-models.md
examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomFederationSchemaGeneratorHooks.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/Application.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomDataFetcherFactoryProvider.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomFunctionDataFetcher.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/SpringDataFetcherFactory.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomSchemaGeneratorHooks.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/AsyncQuery.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/AsyncQueryIT.kt

With the removal of evaluation predicates from the `FunctionDataFetcher` we no longer have an option to automatically handle Reactor/RxJava monads. In order to enable monad support we need to configure custom `SchemaGeneratorHook` to generate valid schema as well as custom `FunctionDataFetcher` so it can correctly process monads at runtime. Ideally this sort of additional runtime logic should be handled by hooks/instrumentation but with the current implementation relying on `graphql-java` it is the simplest workaround to get it working.
https://github.com/ExpediaGroup/graphql-kotlin/issues/596
https://github.com/ExpediaGroup/graphql-kotlin/pull/597

[docs] example usage of Reactor Mono

---

gradle.properties
graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorAsyncTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/utils/FunctionReturnTypesKtTest.kt

Update the latest dependencies to stay on top of updates and bug fixes
* Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/604

Upgrade dependencies

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt

Use the handy method on coroutine GlobalScope to execute as a CompletableFuture instead of mapping the result. This shouldn't really change much but does make the code a little easier to read
N\A

Update completable future mapping for coroutines

---

.github/workflows/pr-check-docs.yml
.github/workflows/publish-docs.yml
website/package-lock.json
website/package.json
website/siteConfig.js

Use https://github.com/peaceiris/actions-gh-pages to publish to the gh-pages branch. This will hopefully remove some config and tokens that we need to save now that GH Actions support pushing branch via the GITHUB_TOKEN secret
See: https://github.com/peaceiris/actions-gh-pages/issues/9

Update publish docs to use a community action

---

.github/workflows/publish-docs.yml

As seen in this publish step the path is relative to the project.
https://github.com/ExpediaGroup/graphql-kotlin/runs/469008143?check_suite_focus=true#step:6:123
```
Error: ENOENT: no such file or directory, scandir '/home/runner/work/graphql-kotlin/graphql-kotlin/build'
```
#616 
#614

Publish the build directory in the website

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/ConcurrentAdditionalTypesTest.kt

We would encounter a bug if generating the additional types produced more additional types. So we now call the function recursively and clear it out before generating more.
N\A

[generator] Fix issue generating nested additional types

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt

Changed the current recursive approach of adding the additional types to iterative one.
This approach saves:
-  a bunch of `toSet()` calls which internally means creation of new LinkedHashSet
- `.plus()` calls which also creates a new LinkedHashSet and does an `addAll()` internally.

move generation of additional types to an iterative approach

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/CustomDataFetcherFactoryProvider.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/execution/SpringDataFetcherFactory.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/KotlinDataFetcherFactoryProvider.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/CustomDataFetcherTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt

We made the `FunctionDataFetcher` return nullable in this change https://github.com/ExpediaGroup/graphql-kotlin/pull/613. That is a good change but I only realized after integrating into our internal SDK that this also impacts the `KotlinDataFetcherFactoryProvider`. 
`KotlinDataFetcherFactoryProvider` returns a `DataFetcherFactory`, and in graphql-java those are supposed to implement the same types that the `DataFetcher` returns. So this change fixed that to match the same types in graphql-java.
This is a breaking change as the interface signature has now been changed.
Data Fetcher returns nullable here: https://github.com/ExpediaGroup/graphql-kotlin/pull/613

BREAKING CHANGE: Make the KotlinDataFetcherFactoryProvider nullable

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt

Additional types cannot be edited, but comments suggest that is the appropriate way to add additional types before generateAdditionalTypes() is called:
```
/**
* Generate the GraphQL type for all the `additionalTypes`. They are generated as non-inputs and not as IDs.
* If you need to provide more custom additional types that were not picked up from reflection of the schema objects,
* you can modify the set of `additionalTypes` before you call this method.
*
* This function is recursive because while generating the additionalTypes it is possible to create additional types that need to be processed.
*/
```
#615

Add additionalTypes to generateSchema

---

gradle.properties
graphql-kotlin-schema-generator/build.gradle.kts

Spring Boot 2.2.5 was released which includes a fix for a security issue in netty. See: https://spring.io/blog/2020/02/27/spring-boot-2-2-5-released
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/625

Upgrade springboot to fix security issue

---

examples/gradle.properties
gradle.properties
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/RoutesConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/FederationConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/SubscriptionConfigurationTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt

Refactor library and test code to remove some build and IDE warnings. This is a non-functional change.
N\A

Refactor to remove build warnings

---

examples/gradle.properties
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Increase the gradle jvm max memory as we are seeing intermittent OutOfMemory errors on GitHub Actions
See: https://github.com/gradle/gradle/issues/8139
N\A

Increase Gradle wrapper memory

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/filters/propertyFilters.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/InterfaceBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt

Fixes transitive properties of `@GraphQLIgnore` when applied on polymorphic types.
Fixes #631 and #632

Polymorphic ignore

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/filters/propertyFilters.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/filters/PropertyFiltersTest.kt

Fixes transitive properties of @GraphQLIgnore when applied on polymorphic types.
Apply the same changes as #633 for the 2.x / master branch
Fixes #631 and #632

Polymorphic ignore 2.x

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kTypeExtensions.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KParameterExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/CustomScalarExecutionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/utils/graphqlUuidType.kt

Converting a list input type for custom scalars was losing the type information. We need to use a specific Jackson conversion method to properly convert the List interface
#635

Custom scalar input

---

website/package-lock.json
website/package.json

Github warned us about an issue in one of docusaurus' dependencies. This forces the new fixed version. This is only in our docs code.
Resolved the Github security report: https://github.com/ExpediaGroup/graphql-kotlin/network/alert/website/package-lock.json/minimist/open

[docs] Fix the NPM/Github security report issue

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/toFederatedSchema.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/ClassScanner.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/toSchema.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/testSchemaConfig.kt

Extracting separate changes from https://github.com/ExpediaGroup/graphql-kotlin/pull/641 that cleans up the resources used when creating a new schema generator. Hopefully this will help with our unit test out of memory issues
https://github.com/ExpediaGroup/graphql-kotlin/pull/641

Make SchemaGenerator closeable

---

docs/execution/subscriptions.md
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidSubscriptionTypeException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateSubscription.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt

Allow for the use of custom types for subscriptions. This requires that you override two hooks, and the execution strategy, but at least this is now possible and we don't have to worry about blocking others from using their own types
https://github.com/ExpediaGroup/graphql-kotlin/pull/629

Allow for custom subscription return types

---

docs/writing-schemas/interfaces.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Fruit.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/PolymorphicQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateGraphQLTypeKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInterfaceTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt

Allows sealed classes to be used as GraphQL Interfaces. This means that you can restrict the possible implementations of the interfaces since subclasses can only be declared with the root class
https://kotlinlang.org/docs/reference/sealed-classes.html
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/642

Support sealed classes for interfaces

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/TypesCache.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/ClassScannerTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/TypeTestHelper.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/instrumentation/InstrumentationIT.kt

In an attempt to fix the out of memory errors, I simplified some of our unit tests to create few ClassScanners and SchemaGenerators, and close all usages of the ones we still have left

Reduce number of class scanners created in tests

---

graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategy.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/FlowSubscriptionSchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategyTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt

Implement a SubscriptionExecutionStrategy that allows
for `Flow`s and `Publisher`s to be returned from
graphql schema elements, and can be processed as a
`Flow` by subscription consumers.  Relax restrictions
that look for `Publisher`s to also allow `Flow`s.
Fixes #358

Add native subscription support for coroutine Flows

---

docs/customizing-schemas/generator-config.md
docs/execution/introspection.md
docs/spring-server/spring-properties.md
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorConfig.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/SchemaGeneratorConfig.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederationAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLConfigurationProperties.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/DataFetcherIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/IntrospectionIT.kt
website/sidebars.json

Schema generator should provide an option to easily disable introspection queries. Add new `introspectionEnabled` Boolean option to `SchemaGeneratorConfig` that is enabled by default.
spring-server was also updated to expose `graphql.introspection.enabled` property that will automatically configure the `SchemaGeneratorConfig` with the specified value.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/651

[generator] allow disabling introspection query

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederatedSchemaAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/generatorExtensions.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/model/GraphQLResponse.kt

Renamed the federation config class to match the same pattern and reuse the imported html for the playground.
Initially a large change in https://github.com/ExpediaGroup/graphql-kotlin/pull/652

[spring] Refactor config classes and internal functions

---

docs/writing-schemas/scalars.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt

Our current logic was not checking whether function return type was annotated with `@GraphQLID` annotation so it was not possible to return `ID` scalar type.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/668

[generator] support returning GraphQL ID scalar from functions

---

.github/workflows/maven.yml
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilder.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/FunctionBuilderTest.kt

Backport to 1.x.x
Our current logic was not checking whether function return type was annotated with @GraphQLID annotation so it was not possible to return ID scalar type.
* https://github.com/ExpediaGroup/graphql-kotlin/pull/669
* https://github.com/ExpediaGroup/graphql-kotlin/issues/668

[generator] support returning GraphQL ID scalar from functions 1.x.x

---

build.gradle.kts
docs/plugins/gradle-plugin.md
gradle.properties
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/KotlinExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTask.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/resources/introspectionResult.json
plugins/graphql-kotlin-plugin-core/README.md
plugins/graphql-kotlin-plugin-core/build.gradle.kts
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com.expediagroup.graphql.plugin/introspectSchema.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/IntrospectSchemaTest.kt
plugins/graphql-kotlin-plugin-core/src/test/resources/introspectionResult.json
settings.gradle.kts
website/sidebars.json

This is an initial PR that introduces new `graphql-kotlin` Gradle plugin with schema introspection functionality. This new plugin task runs introspection query against target GraphQL endpoint and generates GraphQL schema based on the results.
PR size is very large due to the inclusion of raw introspection results that are used for testing of `plugin-core` and `gradle-plugin` projects. Those two files combined account for ~2800 lines of code.
NOTE: This is an attempt to split up https://github.com/ExpediaGroup/graphql-kotlin/pull/595 into more manageable pieces. Subsequent PRs will follow with additional functionality.
None

new gradle plugin with introspect schema task

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt

The `ContextWebFilter` did a simple string compare to match the path. Instead we should use a proper `PathParser` to check the route and provide additional options like being case-insensitive and ignoring trailing slashes
https://github.com/ExpediaGroup/graphql-kotlin/issues/672

Allow for trailing slashes on context filter

---

examples/federation/base-app/README.md

The command to execute the base app was incorrect. It had two preceding colons, not one.

Incorrect Execution Command for base-app

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLError.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/SimpleKotlinGraphQLErrorTest.kt

Based on the [Graphql spec](https://spec.graphql.org/June2018/#sec-Errors), error response should contain list of locations if error can be associated with particular point in the requested GraphQL document. We should not populate it if `locations` information is unavailable.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/675

[server] GraphQL Error response type should allow null locations

---

examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/query/SimpleQuery.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt

The underlying issue is due to a bug in how we print out SDL - basically if you have escape characters they will be printed out in nicely formatted String intended for output. This unfortunately leads to invalid SDL as those comments will no longer be valid Strings. You can see the issue in the SDL that gets printed out at the startup when you use comments like:
```kotlin
@GraphQLDescription("Comment with pattern: `^\\+[1-9]\\d{7,14}$")
fun commentsWithEscapeCharacters() = "escaping \\"
```
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/666
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/667

[generator] explicitly escape special characters in SDL

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExtendsDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ExternalDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/FieldSet.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/KeyDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/ProvidesDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/RequiresDirective.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/extensions/graphQLSchemaExtensions.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateDirective.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLDirectiveContainerExtensionsKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/extensions/GraphQLSchemaExtensionsKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/FieldSetTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/ServiceTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/FederatedSchemaValidatorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateProvidesDirectiveKtTest.kt

Since the extends directive is always used in federation on the Query object we should always have the directive definition in the schema. However it may already be added if the generated schema uses it, so only add the definition if it is not yet defined
The schema we generate today will still work on the server, it just fails if you happen to run through the generated SDL through the Apollo CLI or Gateway.
N\A

Add extends directive if not defined

---

.github/workflows/release.yml
build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts

Recent RC releases were failing to publish sonatype but were successfully publish Gradle plugin. Attempting to publish plugin only after successful sonatype publish by explicitly specifying tasks to execute. Unfortunately cannot easily configure the order using `build.gradle.kts` as `finalizedBy` clause will always run finalized tasks regardless whether previous one succeeded or not.
New release command
`./gradlew :initializeSonatypeStagingRepository publish :closeAndReleaseRepository publishPlugins -Pversion=${NEW_VERSION}`

[build] update release process to publish Gradle plugin after sonatype publish

---

docs/writing-schemas/enums.md

I doubt this is terribly common, but I figured it's nice to document more examples of schema generator hooks. I also struggled with missing the `.java` to get it to work.

docs: add recipe for using willGenerateGraphQLType with java enums

---

plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt

Update generated client query method from `<operationName>` to simple `execute`, e.g. given operation name `HelloWorldQuery` we would end up generating it as `HelloWorldQuery.helloWorldQuery`, instead we will now generate it as `HelloWorldQuery.execute`.

[plugin] update generated GraphQL client execute query method

---

docs/plugins/gradle-plugin.md
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/main/kotlin/com/example/UUIDScalarConverter.kt
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt

In order for Maven to recognize complex objects all their fields need to be annoated with `@Parameter` annotation.
Additonal changes
- add debug messages for logging generate client task/mojo configuration
- update integration tests to validate custom scalar logic
- update Gradle task `converters` parameter to match Maven MOJO parameter

[plugin] fix generate client MOJO converter parameter

---

docs/client/client-customization.md
docs/client/client-features.md
docs/client/client-overview.md
graphql-kotlin-client/README.md
graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-maven-plugin/README.md
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt
website/sidebars.json

* Update the client result class to be called `Result`
* Add the client docs to the docs website

[docs] GraphQL client documentation and configuration fixes

---

plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts

Enable publish of Gradle plugin to Maven Central.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/715

[build] publish Gradle plugin to Maven Central

---

docs/plugins/maven-plugin.md
examples/client/maven-client/pom.xml
plugins/graphql-kotlin-maven-plugin/README.md
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/download-sdl/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/generate-test-client/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/introspect-schema/pom.xml
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/DownloadSDLMojo.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateTestClientMojo.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/IntrospectSchemaMojo.kt

Maven plugins generally follow `hyphen-name` for defining different Mojos and build lifecycle phases. Updating GraphQL Kotlin Maven plugin to follow the convention.
N/A

[plugin] update Maven Mojo names to follow hyphen-name

---

docs/plugins/gradle-plugin.md
examples/client/gradle-client/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt

Updating from:
```
graphql {
endpoint = "http://localhost:8080/graphql"
packageName = "com.example.generated"
```
to
```
graphql {
client {
endpoint = "http://localhost:8080/graphql"
packageName = "com.example.generated"
}
}
```
This will allow us to create separate `schema` configuration block in the future.
Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/705

[plugins] Update Gradle plugin extension to separate client and schema generation

---

docs/writing-schemas/scalars.md
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/SimpleQueries.kt
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/model/ScalarWrapper.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateScalar.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/scalars/ID.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateScalarTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/NodeGraphTest.kt
plugins/graphql-kotlin-maven-plugin/pom.xml

Rename the package to `com.expediagroup.graphql.scalars` so that we can create a new common module `graphql-kotlin-types` that will use `com.expediagroup.graphql.types`
N\A

Move id to scalars package

---

build.gradle.kts

Current logic was incorrectly attaching project sources+javadoc to the Maven publication. Since Gradle plugin produces two publications -> plugin + plugin marker both of them were uploaded with attached plugin sources+javadoc jars.

[build] fix publishing of Gradle plugin marker

---

build.gradle.kts

Our current build does not upload Gradle plugin jar artifact to Sonatype. Reverting back to the original publication logic - originally had an issue with mutliple artifacts sharing the coordinates, checking if that is still an issue. If nothing else works we might need to disable Sonatype publish of Gradle artifact for now.

[build] attempt to use default mavenJava publication for plugin

---

docs/client/client-overview.md

Fix client configuration that was missed when updating https://github.com/ExpediaGroup/graphql-kotlin/pull/724.
Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/738

[docs] fix client configuration

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt

Client generator did not generate `mutation` and `subscription` codes due to missing .name property call on enums, so changed that part

[plugins] fix GraphQLClientGenerator findRootType bug

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt

With the graphql-java 15 update, there was a new printer option to not include directive definitions so we can use that instead of a regex
https://github.com/ExpediaGroup/graphql-kotlin/pull/731

Replace regex with printer option

---

plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGenerateClientTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojoTest.kt
plugins/graphql-kotlin-plugin-core/README.md
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generateClient.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLTestUtils.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt

Type aliases are unique per package so in order to ensure consistency we should generate separate file that will contain all String type aliases for custom scalars/IDs. Currently we generate typealiases per query file which means that if there are multiple queries referencing IDs (or custom scalars without custom mappers) we end up with invalid generated code due to the type aliases clash.
With this PR also update default anonymous operation handling to use enclosing file name as the class name (instead of generic `AnonymousQuery/AnonymousMutation`).
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/746

[plugin] generate separate file containing type aliases

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt

We were incorrectly specifying normalized operation name to be sent as part of the request instead of passing in the original one from the query. This lead to runtime failures when operation name was not starting with an upper case or was not specified at all.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/756

[client] fix operation name in the GraphQL request

---

docs/blogs-and-videos.md
docs/getting-started.md
docs/schema-generator/customizing-schemas/deprecating-schema.md
docs/schema-generator/customizing-schemas/documenting-fields.md
docs/schema-generator/customizing-schemas/excluding-fields.md
docs/schema-generator/customizing-schemas/renaming-fields.md
docs/schema-generator/execution/async-models.md
docs/schema-generator/execution/exceptions.md
docs/schema-generator/writing-schemas/arguments.md
docs/schema-generator/writing-schemas/enums.md
docs/schema-generator/writing-schemas/interfaces.md
docs/schema-generator/writing-schemas/lists.md
docs/schema-generator/writing-schemas/nested-arguments.md
docs/schema-generator/writing-schemas/scalars.md
docs/schema-generator/writing-schemas/unions.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQuery.kt
website/sidebars.json

Take another pass at documentation cleanup
* Remove graphql descriptions in pages that are about other topics
* Rename top level page names
* Add proper header levels
N\A

Clean up docs

---

docs/schema-generator/writing-schemas/scalars.md

Add some messages about common issues for scalars so they are searchable in the search bar.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/771

Update scalars docs with common issues

---

docs/client/client-customization.md
graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/Application.mustache
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt

Update client to allow specifying optional Ktor HttpRequestBuilder block that allows usage of DSL for specifying custom headers as well as provide some additional configuration options like timeouts per request, specify URL query parameters as well as custom attributes that could be referenced from the feature pipeline.
After client is generated we can configure it as follows:
```kotlin
val client = GraphQLClient(
url = URL("http://localhost:8080/graphql"),
engineFactory = OkHttp,
mapper = jackson
) {
// existing global client customization through Ktor HttpClientConfig
engine {
config {
connectTimeout(10, TimeUnit.SECONDS)
readTimeout(60, TimeUnit.SECONDS)
writeTimeout(60, TimeUnit.SECONDS)
}
}
install(Logging) {
logger = Logger.DEFAULT
level = LogLevel.HEADERS
}
}
// create client for …
```

[client] expose request builder to allow customization per query execution

---

docs/federated/federated-directives.md

The GraphQL spec does now support repeatable directives but we are tracking support here:
https://github.com/ExpediaGroup/graphql-kotlin/issues/590

Update the @key directive notes

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/utils/functionReturnTypes.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/utils/FunctionReturnTypesKtTest.kt

There was a bug in the schema generator config that errored out on a `Publisher<DataFetcherResult<T>>`
https://github.com/ExpediaGroup/graphql-kotlin/pull/742
https://github.com/ExpediaGroup/graphql-kotlin/issues/608

[generator] Support subscriptions of Publisher<DataFetcherResult<T>>

---

docs/schema-generator/execution/optional-undefined-arguments.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/mutation/OptionalInputMutation.kt
website/sidebars.json

Add example code to show how to check the difference between a client not sending a value or explicitly passing in null
https://github.com/ExpediaGroup/graphql-kotlin/issues/783

[example] Add example of undefined input vs null

---

gradle.properties
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/InvalidPackagesException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/ClassScanner.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/state/ClassScannerTest.kt

Fail with a new exception `InvalidPackagesException` when the `supportedPackages` config doesn't contain any valid packages. Also edit the exception message to add quotes around the package so the common error that `.properties` files should not use quotes is clear.
This does not cause any new exceptions, it just catches errors earlier instead of failing in the `TypesCache`
i.e.
```properties
graphql.packages=foo.bar
graphql.packages="foo.bar"
```
```
The configured packages do not contain any valid classes: ""foo.bar""
```
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/791

[generator] Add invalid packages exception

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check.yml
.github/workflows/release.yml

The latest action config no longer requires a token for public repositories. This means we can delete the secret if this action works. I also made the formatting of other actions the same in newlines and spacing
https://github.com/codecov/codecov-action

Update codecov action to latest config

---

build.gradle.kts
codecov.yml

Codecov is looking in the directories for the xml reports. HTML reports are still generated for easier debugging
https://github.com/codecov/example-kotlin
Failed action that finds no reports: https://github.com/ExpediaGroup/graphql-kotlin/runs/847614672?check_suite_focus=true#step:8:24

Generate xml report for codecov

---

examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/Application.kt
examples/spark/src/main/kotlin/com/expediagroup/graphql/examples/spark/schema/LoginMutationService.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Fruit.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kParameterExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/FieldExtenstionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KParameterExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt

Polymorphic types (interface, union) are not supported as input types yet, and a `List<>` of those types is also unsupported. However a `List<Interface>` or `ArrayList<Union>` currently passes schema generation then fails at run time. We should instead catch this at generation.
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/799

Valid polymorphic types in lists as input

---

docs/schema-generator/customizing-schemas/renaming-fields.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Selection.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/model/Widget.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/SimpleQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateEnum.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/FieldExtenstionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateEnumTest.kt

`@GraphQLName` was supported for enum classes and object fields but not on enum fields. It is possible to support changing the name in the generator, library users will just also have to add the Jackson annotations to inform the execution engine of the name change
https://github.com/ExpediaGroup/graphql-kotlin/issues/493

Support renaming of enum values

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLInputObjectTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateVariableTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateVariableTypeSpecIT.kt

When generating client we can set default `null` value to the optional nullable input arguments.
Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/781

[client] set default null value for input arguments

---

docs/client/client-customization.md
graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt

Makes `GraphQLClient` an open class so end users can override `execute` method to provide some additional custom logic as needed.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/800

[client] open up GraphQL client

---

detekt.yml
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt
graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/AdditionalType.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/AdditionalType.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInterfaceTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/scalars/IDTest.kt

Allow for the `additionalTypes` to include input types. This change is backwards compatible.
This is helpful when generating our "shared types" in Expedia Group as we want to include both the input and output types in the micro schemas.
Possible clean up issue for 4.0.0, needs more discussion if what we have is good enough: https://github.com/ExpediaGroup/graphql-kotlin/issues/818

[generator] Update additional types to work with input types

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kClassExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/PolymorphicTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/SchemaGeneratorTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KClassExtensionsTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt

Add new hooks setting that will allow you to override the `isValidAdditionalType` check in the `addAdditionalTypesWithAnnotation` method and when adding additional types from the `generateInterface` implementations.
https://github.com/ExpediaGroup/graphql-kotlin/issues/818

Add new hook to override the isValidAdditionalType check

---

docs/federated/federated-schemas.md

Link to Federated Schemas is broken on [Federated Schemas documentation page](https://expediagroup.github.io/graphql-kotlin/docs/federated/federated-schemas)
N/A

[documentation] Fixing broken link to federated schemas

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kPropertyExtensions.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KPropertyExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt

Copy logic from `3.x.x` branch
Update the property generator code to check the getters for the `@GraphQLIgnore` annotation. This means that any Kotlin property can use both `@GraphQLIgnore` and `@get:GraphQLIgnore`, but it also solve the issue with directive arguments that the generated JVM code only has annotation on the argument getters.
https://github.com/ExpediaGroup/graphql-kotlin/pull/763

[2.x.x] Include java getters for ignore checks

---

gradle.properties

Just bumps the version in `gradle.properties` that is used for CI. Release builds use version from tags anyway.

[build] officially start targeting 4.0.0

---

examples/client/gradle-client/build.gradle.kts
examples/client/maven-client/pom.xml
examples/client/server/build.gradle.kts
gradle.properties
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kTypeExtensions.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/KotlinDirectiveWiringFactoryTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/KTypeExtensionsKtTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/FlowSubscriptionSchemaGeneratorHooksTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt

This is a simple update of the version and does not yet truly take advantage of any of the newer features but it looks like with just a couple warning fixes we can update as a backwards compatible change. We are also not using any `1.4` specific features so this should be able to be used in `1.3.x` apps
https://kotlinlang.org/docs/reference/whatsnew14.html
https://github.com/Kotlin/kotlinx.coroutines/releases

Update to kotlin 1.4

---

docs/schema-generator/execution/optional-undefined-arguments.md
graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/OptionalInput.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/kTypeExtensions.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooks.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateArgumentTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/OptionalInputTest.kt

In the GraphQL world, input types can be optional which means that the client can either:
* Not specify a value at all
* Send null explicitly
* Send the non-null type
This is in contrast with the JVM world where objects can either have some specific value or don't have any value (i.e. are `null`). As a result, when using default serialization logic it is not possible to distinguish between missing/unspecified value and explicit `null` value.
This PR introduces new `OptionalInput` sealed class wrapper that when used for query arguments will be automatically deserialized to `Undefined` object if argument was not specified OR to `Defined` wrapper class when argument was specified (including explicit null).
Resolves: #783

[generator] built-in support for optional input

---

clients/graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/converter/ScalarConverter.kt
docs/client/client-customization.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/hooks/CustomSchemaGeneratorHooks.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/ScalarQuery.kt
plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/UUIDScalarConverter.kt
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/main/kotlin/com/example/UUIDScalarConverter.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLCustomScalarTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt

Custom GraphQL scalars can be serialized as any of the other built-in scalars (i.e. int, float, etc). Changed method signatures to accept `Any` when converting to scalar, and produce `Any` when generating JSON value.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/816

[client] update ScalarConverter to accept any objects

---

build.gradle.kts
graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/state/ClassScanner.kt

We are getting compile errors in the different builds. We need to include the reflection dependency in the different sub libraries and in the test deps for the th plugin
```
> Task :graphql-kotlin-gradle-plugin:compileTestKotlin
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
/home/runner/.gradle/wrapper/dists/gradle-6.3-bin/8tpu6egwsccjzp10c1jckl0rx/gradle-6.3/lib/kotlin-stdlib-1.3.70.jar (version 1.3)
/home/runner/.gradle/wrapper/dists/gradle-6.3-bin/8tpu6egwsccjzp10c1jckl0rx/gradle-6.3/lib/kotlin-stdlib-common-1.3.70.jar (version 1.3)
/home/runner/.gradle/wrapper/dists/gradle-6.3-bin/8tpu6egwsccjzp10c1jckl0rx/gradle-6.3/lib/kotlin-stdlib-jdk8-1.3.70.jar (version 1.3) …
```

Include reflection as a dependency for all subprojects

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/CompanyService.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/dataloaders/DataLoaderConfiguration.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataLoaderQuery.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscription.kt
examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt
gradle.properties
graphql-kotlin-spring-server/build.gradle.kts
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandler.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionState.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/responseExtensions.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionProtocolHandlerTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/ApolloSubscriptionSessionStateTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/execution/SubscriptionWebSocketHandlerIT.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/extensions/GeneratorExtensionsKtTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/SubscriptionRoutesConfigurationIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojoTest.kt

When updating to the latest spring boot version our subscription tests are failing. I can reproduce this with just the jump to Spring Boot `2.2.7`. 
The issue is that the `StepVerifier`s do not complete the publisher so the test stays running in the background and never completes. I have re-worked how to capture the published events in the tests, as well as fixed a bug in the subscription code that was not sending the `COMPLETE` event. However this still hangs when we are trying to process multiple events. 
The [line here](https://github.com/ExpediaGroup/graphql-kotlin/compare/master...smyrick:subscriptions-tests?expand=1#diff-d5e812810c739e39574a5826d45b46a8R86), using `toMono` stop the publisher after just one event which is why it fails when attempting to check the second message. …

Fix subscriptions messaging and tests

---

gradle.properties
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
plugins/graphql-kotlin-maven-plugin/build.gradle.kts

We are hitting some library and plugin issues with incompatibilities between Kotlin versions. Downgrading back to 1.3.72 for now, we will revisit update to 1.4 sometime in the future.
Update to 1.4 https://github.com/ExpediaGroup/graphql-kotlin/pull/844

[build] revert Kotlin version to 1.3.72

---

.github/workflows/release.yml
website/package-lock.json
website/package.json
website/pages/en/versions.js

We should update the docs versions on every code release. We can then come back manually and delete excess version numbers, but the docs should always reflect the latest
Original issue here: https://github.com/ExpediaGroup/graphql-kotlin/pull/767

Update docs on library release

---

graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLRoutesConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/PlaygroundRouteConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SdlRouteConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SubscriptionAutoConfiguration.kt

Create a separate bean for the `/sdl` route so we don't need to pass the schema bean to the `GraphQLRoutesConfiguraiton`. This also makes it clear the beans that can be enabled and disabled from the classes

Add separate configuration for SDL route

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt

It looks like the application/json accept header is set by `install(feature = JsonFeature)` on line 48 as well as `accept(ContentType.Application.Json)` on line 54. This causes a duplicate Accept header during the introspection query Gradle task. 
Spring handles the duplicate Accept header, but Jersey returns an 400 Bad Request when receiving the header.`Accept: application/json;application/json`
I have not created an issue.

[client] Remove duplicate header

---

clients/graphql-kotlin-ktor-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLKtorClient.kt

This header is already added with `install(JsonFeature) { }`
See https://github.com/ExpediaGroup/graphql-kotlin/pull/865
https://github.com/ExpediaGroup/graphql-kotlin/pull/867

[client] Remove duplicate accept header

---

graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt

Copy changes over to `3.x.x` branch
It looks like the application/json accept header is set by `install(feature = JsonFeature)` on line 48 as well as `accept(ContentType.Application.Json)` on line 54. This causes a duplicate Accept header during the introspection query Gradle task. 
Spring handles the duplicate Accept header, but Jersey returns an 400 Bad Request when receiving the header.`Accept: application/json;application/json`
https://github.com/ExpediaGroup/graphql-kotlin/pull/865

[3.x.x][client] Remove duplicate header

---

.github/workflows/pr-check-docs.yml
.github/workflows/publish-latest-docs.yml
.github/workflows/release-code.yml
.github/workflows/release-docs.yml
.github/workflows/release.yml

Split the GH Actions for releasing docs and code so we can trigger them independently on failure. Also the push works now with the actions username but for consistency sake we can use the eg-osss user
https://github.com/ExpediaGroup/graphql-kotlin/commit/6c1c53fbe1a9476b59aa0c1f5a4f13169d98f348

Separate release docs and code 

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/NestedQueries.kt
examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/query/NestedQueriesIT.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt

Allow properties to have `@GraphQLName` to change the name of the type in the schema and queries
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/866

Fix issue with GraphQLName on properties

---

website/package-lock.json
website/package.json

Dependabot security alert for transitive deps
https://github.com/ExpediaGroup/graphql-kotlin/network/alert/website/package-lock.json/bl/open

Add dependency for security alert

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
plugins/graphql-kotlin-plugin-core/src/test/resources/testSchema.graphql

We were incorrectly using simple class name for the type lookup as all classes are wrapped in some root type (i.e. `Query.MyClass`) whereas GraphQL type name was just the actual type. We were also incorrectly comparing selection sets as we were not unwrapping selection sets of the children fields.
Fixes: https://github.com/ExpediaGroup/graphql-kotlin/issues/864

[client] fix generation of duplicate classes

---

examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt

Update the unit test to send an INIT message for each subscription

Start each subscription with init message

---

clients/graphql-kotlin-ktor-client/src/test/kotlin/com/expediagroup/graphql/client/GraphQLKtorClientTest.kt
clients/graphql-kotlin-spring-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLWebClient.kt
clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/GraphQLWebClientTest.kt

Currently GraphQLWebClient throws NoSuchElementException for non-200 with
empty body response (i.e 401 Unauthorized) instead of propagating the error.
This change makes use of WebClient.retrieve to throw exception on
non-sucessful HTTP responses to keep inline with KtorClient.
GraphQL always uses HTTP status 200 so other status like 4xx or 5xx should
be treated as failure and it does not need to unmarshal response body.

[client] Throw error on non-successful HTTP responses

---

clients/graphql-kotlin-spring-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLWebClient.kt

Apply default codecs for JSON encoder/decoder without overwriting whole exchange strategies.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/899

[client] update GraphQLWebClient to correctly apply codecs

---

docs/plugins/gradle-plugin.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLDownloadSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGenerateClientTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLIntrospectSchemaTaskIT.kt

Originally extension was using Kotlin lambdas for some configuration which worked fine when used from Kotlin script (`build.gralde.kts`) but it could not be easily used from Groovy scripts (`build.gradle`). By changing from lambda with a receiver to a Groovy Action the resulting code will be translated using SAM conversion that makes it possible to configure the extension using Kotlin lambda or Groovy closure.
Resolves: #893
Discussion: #892

[plugin] update Gradle plugin extension to use Actions

---

docs/client/client-overview.md

refactor(doc): fix a small typo
Just a smart-ass typo fix to also try the contribution convention
None

[docs] fix small typo

---

docs/plugins/gradle-plugin.md
docs/plugins/maven-plugin.md
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt

In order to keep extension logic consistent, all extension configuration fields can be explicitly set. Fields with return type of a collection now only accept immutable collections and it is no longer possible to add elements directly to a field.
Previous configuration allowed both
```
graphql {
client {
// set new headers map
headers = mutableMapOf("foo" to "bar")
// add individual entries
headers["foo"] = "bar"
// set new list of query files
queryFiles = mutableListOf(file("foo.graphql"))
// add files individually
queryFiles.add(file("foo.graphql"))
}
}
```
Updated configuration only allows setting immutable collections
```
graphql {
client {
headers = mapOf("foo" to "bar")
queryFiles = listOf(file("foo.graphql"))
}
}
```
Resolves …

[plugin] Update Gradle extension to accept immutable lists

---

clients/graphql-kotlin-ktor-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLKtorClient.kt
clients/graphql-kotlin-spring-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLWebClient.kt

When client was used in multithreaded environment it was possible to encounter `ConcurrentModificationException` when multiple threads attempted to compute parameterized type.
None

[client] update parameterizedType cache to use concurrent hash map

---

graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt

3.x.x backports:
* https://github.com/ExpediaGroup/graphql-kotlin/pull/913
* https://github.com/ExpediaGroup/graphql-kotlin/pull/916
Fixes: https://github.com/ExpediaGroup/graphql-kotlin/issues/903

[3.x.x] backport fixes for client concurrency and custom scalars bug

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLTestUtils.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt

When custom scalars (with converters) were referenced multiple times from selection set (e.g. from a common fragment) we would attempt to unwrap the converted scalar type when comparing generated object properties and next selection set fields. This that even though it was the same selection we could still end up with multiple duplicate classes. Added explicit check to verify whether unwrapped property type is auto converted scalar type.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/903

[plugin] fix client generation when selecting custom scalars

---

docs/plugins/gradle-plugin.md
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt

Adds ability to specify custom query file directory (previously we had to explicitly provide a list of query files).
```kotlin
graphql {
client {
endpoint = "http://localhost:8080/graphql"
package = "com.example"
queryFileDirectory = "${project.projectDir}/src/main/resources/queries"
}
}
```
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/886

[plugin] support query file directory in Gradle extension

---

plugins/graphql-kotlin-plugin-core/build.gradle.kts
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/DeprecatedFieldsSelectedException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/InvalidFragmentException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/InvalidPolymorphicQueryException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/InvalidSelectionSetException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/MultipleOperationsInFileException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/UnknownFieldSelectedException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/exceptions/UnknownGraphQLTypeException.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/extensions/DocumentExtensions.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLInterfaceTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLObjectTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLUnionTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateInterfaceTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generatePropertySpecs.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLUnionTypeSpecIT.kt

Changes
* use typed exceptions instead of generic `RuntimeException`
* validate whether fragments are valid
Related: https://github.com/ExpediaGroup/graphql-kotlin/issues/903

[plugin] improve client generation exception handling

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateDirective.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateEnum.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputObject.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateMutation.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateObject.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateSubscription.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateUnion.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt

When generating a schema you can have an annotation on any part of the schema, assuming you haven't set the Target, so if you are restricting the directive locations to only specific places they may still be added to the schema and then fail generation as they are added to invalid locations. While this could be viewed as a customer error, this is more of an issue with graphql-kotlin because we can have input and output objects with the same directives and things like the KeyDirective from federation are only valid on output. So in that case we shouldn't fail if someone uses the type as input elsewhere, it will still not be marked as a federation type for the input
Copy changes from https://github.com/ExpediaGroup/graphql-kotlin/pull/924 to the master branch

[generator] Only add directives with valid locations

---

plugins/graphql-kotlin-maven-plugin/build.gradle.kts

Prevents a failure from maven on a fresh checkout that the maven plugin is not available in maven local for the plugin integration tests. Occurs on `./gradlew build` when the maven local repository is empty.
```
[INFO] [ERROR] Failed to execute goal com.expediagroup:graphql-kotlin-maven-plugin:4.0.0-SNAPSHOT:introspect-schema (default) on project graphql-kotlin-introspect-schema-mojo-timeout-test: Execution default of goal com.expediagroup:graphql-kotlin-maven-plugin:4.0.0-SNAPSHOT:introspect-schema failed: Timed out waiting for 100 ms -> [Help 1]
```

Ensure artifact is published to maven before maven integration tests

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateArgument.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateDirective.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateEnum.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateFunction.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputObject.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInterface.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateMutation.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateObject.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateProperty.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateSubscription.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateUnion.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateDirectiveTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateEnumTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateInputObjectTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateObjectTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateQueryTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/utils/differentLocationDirectives.kt

When generating a schema you can have an annotation on any part of the schema, assuming you haven't set the Target, so if you are restricting the directive locations to only specific places they may still be added to the schema and then fail generation as they are added to invalid locations. While this could be viewed as a customer error, this is more of an issue with graphql-kotlin because we can have input and output objects with the same directives and things like the KeyDirective from federation are only valid on output. So in that case we shouldn't fail if someone uses the type as input elsewhere, it will still not be marked as a federation type for the input

[3.x.x][generator] Only add directives with valid locations

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/exceptions/ConflictingFieldsException.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateMutation.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateQuery.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateSubscription.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateMutationTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateQueryTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateSubscriptionTest.kt

Since Operation types (mutation, mutation, subscription) can be implemented in plural classes, there are chances to make mistake by implementing plural operation classes with same function name. 
This PR catches such grammar errors on schema generation.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/921

feat: catching field name collision on schema generation

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateFieldSelection.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateFieldSet.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateFieldSetKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateRequiresDirectiveKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedKeyDirectiveIT.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedRequiresDirectiveIT.kt

When we have a large nested field selection it can be difficult to know where the issue is. This updates the error message to log the exact typo or missed field name
Before:
```
@key(fields = foo { bar { baz { vale } } }) directive on Parent specifies invalid field set - field set specifies fields that do not exist
```
After
```
@key(fields = foo { bar { baz { valu } } }) directive on Parent specifies invalid field set - field set specifies field that does not exist, field=valu
```
N\A

[federation] Update error message for invalid field selection

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateFieldSelection.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/validation/validateFieldSet.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateFieldSetKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/ValidateRequiresDirectiveKtTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedKeyDirectiveIT.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/validation/integration/FederatedRequiresDirectiveIT.kt

When we have a large nested field selection it can be difficult to know where the issue is. This updates the error message to log the exact typo or missed field name
Before:
```
@key(fields = foo { bar { baz { vale } } }) directive on Parent specifies invalid field set - field set specifies fields that do not exist
```
After
```
@key(fields = foo { bar { baz { valu } } }) directive on Parent specifies invalid field set - field set specifies field that does not exist, field=valu
```
4.x.x changes - https://github.com/ExpediaGroup/graphql-kotlin/pull/932/files

[3.x.x] Update error message for invalid field selection

---

graphql-kotlin-spring-server/src/main/resources/graphql-playground.html

Hello,
My brand uses a security context provided by cookies.
When opening the playground from a first party domain name (from the domain name having the graphql endpoints),
I want to have the auth cookie sent to the server without having to specify it in the "http headers" section of the playground
auth and graphql-kotlin jira tickets in my brand.

fix(spring-server): adding credentials by default

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/exceptions/CustomDataFetcherExceptionHandler.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQuery.kt
gradle.properties
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/ServiceQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/federationDirectives.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategy.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/directives/DirectiveTests.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateFunctionTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GenerateObjectTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/types/GeneratePropertyTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/hooks/SchemaGeneratorHooksTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/exception/KotlinDataFetcherExceptionHandlerTest.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLEnumTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generatePropertySpecs.kt

Update to `graphql-java` v16 (see: https://github.com/graphql-java/graphql-java/releases/tag/v16.0 for details).
`graphql-java` added new validations that now fail schema generation if objects (e.g. query) doesn't have any fields. Unfortunately this complicates federation generation logic as it is possible to have federated service without any regular queries. As a workaround, we now add `_service` field during query generation to ensure that it will always have at least one single field. As a side effect we now have to add some additional String manipulations to generate valid federated SDL.
https://github.com/graphql-java/graphql-java/issues/2107

update to graphql java 16

---

plugins/graphql-kotlin-plugin-core/README.md
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGeneratorContext.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/extensions/DocumentExtensions.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLObjectTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateInterfaceTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generatePropertySpecs.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/resources/testSchema.graphql

Fixes logic to generate the self-referencing types. We were caching both generated `TypeSpecs` (class implementation) and `ClassNames` (class references) but we were doing so in wrong order. We rely on `ClassNames` and its selection set to determine whether the underlying type was already generated but we populated `ClassName` AFTER generating the type. This meant that if a type had a self-reference it would trigger generation of outer type first and then attempt to generate its own self reference but since `ClassName` was not yet generated it would generate the child type with the same name and then overwrite it with the generated parent. This lead to incorrect classes being generated as shown in original (invalid) `verify we can generate nested objects` test (note: that single type was …

[plugin] fix generation of self referencing types

---

examples/spring/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/ContextWebFilter.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/GraphQLContextFactoryIT.kt

Small typo in the subscription code constant and adds an example unit test
N\A

fixes typo and adds tests for subscription (context)

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/GraphQLContext.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLExecutionConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/GraphQLContextFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/extensions/requestExtensions.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/context/ContextWebFilterTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/extensions/RequestExtensionsKtTest.kt

Some time ago we updated our `GraphQLContext` parameter handling logic from requiring explicit `@GraphQLContext` parameter annotation to requiring context classes to implement our marker interface but we never updated our fallback logic. By default, `spring-server` created `EmptyGraphQLContext` context factory with a fallback to `graphql-java` `GraphQLContext` that could never be specified as function parameter as it (obviously) did not implement our interface.
Updating default generated `GraphQLContext` to more usable `DefaultGraphQLContext` that holds concurrent hash map of arbitrary elements (similar to `graphql-java` default).
Issue found in https://github.com/ExpediaGroup/graphql-kotlin/issues/945

[server] update default GraphQLContext

---

docs/plugins/gradle-plugin.md
docs/plugins/maven-plugin.md
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTask.kt
plugins/graphql-kotlin-maven-plugin/README.md
plugins/graphql-kotlin-maven-plugin/src/integration/basic-setup/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/pom.xml
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/RetrieveSchemaAbstractMojo.kt

Simplifying Maven plugin configuration by allowing customizing the downloaded/introspected schema file name. Current logic did not allow renaming the default file (from `target/schema.graphql`) and required explicitly specifying the schema file for the client generation mojo. This was confusing as when `download-sdl`/`introspect-schema` mojo was used together with `generate-client` one we had to specify target schema always pointing to the default one. Updated logic so that specifying custom schema file name will now apply to all tasks. `generate-client` mojo was also updated to use default `target/schema.graphql` file if schema file is not specified.
In order to keep it consistent, Gradle `downloadSDL` and `introspectSchema` tasks were updated to allow specifying custom `outputFile`s …

[plugins] allow renaming of the downloaded/introspected schema

---

build.gradle.kts

See:
* https://github.com/gradle/gradle/issues/15406
* https://blog.autsoft.hu/a-confusing-dependency/

[build] deprioritize jcenter in favor of maven central

---

docs/federated/federation-tracing.md
docs/spring-server/spring-graphql-context.md
gradle.properties
graphql-kotlin-federation/build.gradle.kts
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/FederationGraphQLContext.kt
graphql-kotlin-spring-server/build.gradle.kts
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/FederatedSchemaAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/SchemaAutoConfiguration.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/GraphQLContextFactory.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/QueryHandler.kt
website/sidebars.json

For federation we need to send back tracing metrics to get usage reporting. We can use Apollo's library: https://github.com/apollographql/federation-jvm
This adds a new `FederationGraphQLContext` and a `FederationGraphQLContextFactory` that are conditionally added if federation is enabled. Since they implement the base interfaces we already had we don't need to change the code in `ContextWebFilter` or the spring execution to use them differently. It will just be on federation users to implement the `FederationGraphQLContextFactory` now instead of the `GraphQLContextFactory` if they want tracing support.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/418

[3.x.x] Add federation context and tracing support

---

website/pages/en/versions.js

The current versions page links do not work: https://expediagroup.github.io/graphql-kotlin/versions
N\A

Update versions page links and test

---

docs/schema-generator/execution/subscriptions.md
docs/spring-server/subscriptions.md
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategy.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategyTest.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/GraphQLSchemaConfiguration.kt

`FlowSubscriptionExecutionStrategy` was available in the schema-generator library but we never integrated it with the spring-server. Since all our subscription handlers are based on the publisher API, I also updated flow subscription strategy to return publisher as well. This is a breaking for the existing flow subscription strategy users but without this change we would need to rewrite all our subscription handling logic to support flow natively (which we should do eventually when/if we move away from `graphql-java` based execution).
Explicit casts are required due to the type erasure and also Java reliance on site-variance vs Kotlin declaration-variance.
https://github.com/ExpediaGroup/graphql-kotlin/issues/358
https://github.com/ExpediaGroup/graphql-kotlin/discussions/970

[server] add support for flow subscriptions

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt

`graphql-java` version 16 updated their introspection query to support repeatable directives. Updated introspection query can only be executed against servers that are running latest version of `graphql-java`. Adding old version of the introspection query as we dont need repeatable directive info for generating the client code

[plugins] update introspection query

---

plugins/graphql-kotlin-plugin-core/build.gradle.kts
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGenerator.kt

`graphql-kotlin-plugin-core` was transitively pulling in the full dependencies for Spring, Netty and data-loader which are not required for its functionality.
This change eliminates 25 build dependencies:
- before: https://scans.gradle.com/s/bjgr6gnkaf3i6/build-dependencies
- after: https://scans.gradle.com/s/ojywargwsvkpk/build-dependencies
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/930

[build] exclude unnecessary plugin dependencies

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/OptionalInput.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/OptionalInputTest.kt

Additional unit test that verifies deserialization of nested optional input arguments. Added a convenient `toString` on the `OptionalInput.Undefined` and `OptionalInput.Defined`.
See https://github.com/ExpediaGroup/graphql-kotlin/issues/954 for details

[generator] additional test for nested optional input values

---

docs/schema-generator/execution/optional-undefined-arguments.md
docs/schema-generator/writing-schemas/arguments.md
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/OptionalInputTest.kt
graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/spring/execution/SpringDataFetcher.kt

Add support for Kotlin default values. By calling functions with the `callBy` methods instead we can pass a map of `KParameters`. Then if one of the params is optional and it is not sent a value from GraphQL input we can exclude that parameter from the map, which mean the default value will be used.
Kotlin
```kotlin
fun print(message: String? = "hello"): String? = message
```
GraphQL
```graphql
query PrintMessages {
first: print(message = "foo") # foo
second: print(message = null) # null
third: print # hello
}
```
This info will not be [conveyed in the schema](https://graphql.org/learn/schema/#arguments), but it simplifies the logic needed for optional arguments. If you still need to have logic for the default values I recommend using the `OptionalInput` wrapper, since you will still not …

Support default Kotlin values

---

docs/plugins/hooks-provider.md
gradle.properties
plugins/schema/graphql-kotlin-federated-hooks-provider/README.md
plugins/schema/graphql-kotlin-federated-hooks-provider/build.gradle.kts
plugins/schema/graphql-kotlin-federated-hooks-provider/src/main/kotlin/com/expediagroup/graphql/plugin/schema/hooks/FederatedSchemaGeneratorHooksProvider.kt
plugins/schema/graphql-kotlin-federated-hooks-provider/src/main/resources/META-INF/services/com.expediagroup.graphql.plugin.schema.hooks.SchemaGeneratorHooksProvider
plugins/schema/graphql-kotlin-hooks-provider/README.md
plugins/schema/graphql-kotlin-hooks-provider/build.gradle.kts
plugins/schema/graphql-kotlin-hooks-provider/src/main/kotlin/com/expediagroup/graphql/plugin/schema/hooks/SchemaGeneratorHooksProvider.kt
plugins/schema/graphql-kotlin-sdl-generator/README.md
plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/test/FederatedGraphQLServer.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/test/SimpleQuery.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/test/hooks/CustomFederatedHooks.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/test/hooks/TestSchemaGeneratorHooksProvider.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/resources/META-INF/services/com.expediagroup.graphql.plugin.schema.hooks.SchemaGeneratorHooksProvider
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/resources/application.yml
plugins/schema/graphql-kotlin-sdl-generator/src/main/kotlin/com/expediagroup/graphql/plugin/schema/GenerateSDL.kt
plugins/schema/graphql-kotlin-sdl-generator/src/main/kotlin/com/expediagroup/graphql/plugin/schema/hooks/SchemaGeneratorHooksProvider.kt
plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/graphql/plugin/schema/GenerateSDLTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/test/SimpleGraphQLServer.kt
plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/test/SimpleQuery.kt
plugins/schema/graphql-kotlin-sdl-generator/src/test/resources/application.yml
settings.gradle.kts
website/sidebars.json

`graphql-kotlin-sdl-generator` module can be used to generate GraphQL schema build artifact directly from your source code. Module scans the classpath for classes implementing `graphql-kotlin-types` marker interfaces (`Query`, `Mutation` and `Subscription`) and then uses that information to generate a schema using `graphql-kotlin-schema-generator`. By default, this module will generate the schema using `NoopSchemaGeneratorHooks`. If your project uses custom hooks or needs to generate the federated GraphQL schema, you will need to provide an instance of `SchemaGeneratorHooksProvider` that will be used to create an instance of your custom hooks.
`SchemaGeneratorHooksProvider` is a service provider interface that exposes a single `hooks` method to generate an instance of …

[plugins] create sdl-generator module that can generate graphql schema

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check-docs.yml
.github/workflows/pr-check.yml
.github/workflows/publish-latest-docs.yml
.github/workflows/release-code.yml
.github/workflows/release-docs.yml

GH actions default to 6 hour timeout per workflow. Since steps occassionally get stuck, we end up manually cancelling and re-running those workflows.
Based on the https://github.com/ExpediaGroup/graphql-kotlin/actions our workflows average time
* PR check / CI - ~10-12 minutes -> adding timeout of 30 minutes
* PR check docs / Publish latest docs / Release docs  - ~1 min -> adding timeout of 10 minutes
* Release code - ~15 minutes -> adding timeout of 1h
N/A

[build] specify timeouts for GH workflows

---

clients/graphql-kotlin-client/src/main/kotlin/GraphQLClient.kt
clients/graphql-kotlin-client/src/main/kotlin/converter/ScalarConverter.kt
clients/graphql-kotlin-ktor-client/src/main/kotlin/GraphQLKtorClient.kt
clients/graphql-kotlin-ktor-client/src/test/kotlin/GraphQLKtorClientTest.kt
clients/graphql-kotlin-spring-client/src/main/kotlin/GraphQLWebClient.kt
clients/graphql-kotlin-spring-client/src/test/kotlin/GraphQLWebClientTest.kt
docs/client/client-customization.md
docs/client/client-features.md
docs/client/client-overview.md
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLClientIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/Application.mustache
plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/JUnit.mustache
plugins/graphql-kotlin-maven-plugin/src/integration/basic-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt

Moving `GraphQLKotlinKtorClient` and `GraphQLKotlinWebClient` to their specific `ktor` and `spring` packages. Also simplifying project structure as per https://kotlinlang.org/docs/reference/coding-conventions.html#directory-structure.
See https://github.com/ExpediaGroup/graphql-kotlin/discussions/1000 for details.

[client] move GraphQLKotlinClient implementations to specific packages

---

.github/workflows/pr-check.yml
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTaskIT.kt

Enables https://github.com/actions/upload-artifact to upload all generated build reports (detekt, jacoco, ktlint, junit) on build failure. Currently we only have access to build logs which may not provide enough information about the failure. If this works as expected we will enable this on the main CI build as well.
N/A

[build] enable GH action to upload build reports on failure

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check.yml
.github/workflows/release-code.yml

Enables https://github.com/actions/upload-artifact to upload all generated build reports (detekt, jacoco, ktlint, junit) on build failure. Currently GH actions do not allow access to their workspace and we only have access to build logs which may not provide enough information about the failure.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1011

[build] upload failure reports on CI and release workflows

---

docs/schema-generator/writing-schemas/interfaces.md
docs/schema-generator/writing-schemas/unions.md

Add some clarification that interfaces can not be used as arguments and will throw an exception
N\A

Add note on interface as arguments

---

docs/schema-generator/execution/fetching-data.md
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcherTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GeneratePropertyTest.kt

`graphql-java` [PropertyDataFetcher](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/PropertyDataFetcher.java) is the default data fetcher/resolver that will automatically resolve fields on target POJOs. It does so by using reflections to find out the target getter function that needs to be invoked - it accepts a property name and attempts to find matching getter in available class methods.
Since we are generating the schema directly from the source code, when we process the target property we already know which field it is so we can invoke it direcly and skip the redundant reflection logic from `graphql-java`. As a bonus we also address the ambiguity of accessing properties that use `is` prefix (as described in …

[generator] create Kotlin PropertyDataFetcher

---

docs/server/graphql-request-parser.md
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorGraphQLRequestParser.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorServer.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServer.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServerRequest.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServerResponse.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/GraphQLServerTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLRoutesConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLRequestParser.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLRequestParserTest.kt

Add support for handling both individual GraphQL requests (current) as well as batch requests (new) that specify a list of `GraphQLRequest`s in their HTTP body. Single context is created for batch requests and each one of the requests has to provide valid response.
N/A

[server] support batch requests

---

docs/client/client-customization.md
docs/client/client-overview.md
docs/plugins/gradle-plugin-tasks.md
docs/plugins/gradle-plugin-usage.md
docs/plugins/maven-plugin-goals.md
docs/plugins/maven-plugin-usage.md
generator/graphql-kotlin-federation/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateTestClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
website/sidebars.json

Per Gradle docs (https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_migration_guidelines) we should only mutate current task inside configuration action (i.e. when configuring `generateClient/generateTestClient` we should not modify `compileKotlin/compileTestKotlin` tasks by adding the explicit `dependsOn` clause).
Changes:
* Updating task configurations to use lazy providers instead of direct values.
* Updating client generation tasks to be finalized by compile Kotlin tasks.
* Updating task classpath configurations to apply to ALL tasks and not just registered tasks (i.e. if you register your own task it still should use custom configuration)
* Separated `graphqlGenerateClient` and `graphqlGenerateTestClient` into their own …

[plugin] updates to Gradle plugin tasks configuration avoidance

---

clients/graphql-kotlin-client/README.md
clients/graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClientRequest.kt
clients/graphql-kotlin-ktor-client/README.md
clients/graphql-kotlin-ktor-client/src/main/kotlin/com/expediagroup/graphql/client/ktor/GraphQLKtorClient.kt
clients/graphql-kotlin-ktor-client/src/test/kotlin/com/expediagroup/graphql/client/ktor/GraphQLKtorClientTest.kt
clients/graphql-kotlin-spring-client/README.md
clients/graphql-kotlin-spring-client/src/main/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClient.kt
clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClientTest.kt
docs/client/client-customization.md
docs/client/client-features.md
docs/client/client-overview.md
examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/gradle/Application.kt
examples/client/maven-client/src/main/kotlin/com/expediagroup/graphql/examples/client/maven/Application.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLClientIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLCustomScalarTypeAliasIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLCustomScalarTypeSpecIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLDocsIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLEnumTypeSpecIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLInterfaceTypeSpecIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateGraphQLUnionTypeSpecIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/types/GenerateVariableTypeSpecIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/Application.mustache
plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/JUnit.mustache
plugins/graphql-kotlin-maven-plugin/src/integration/basic-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/complete-setup/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GraphQLMavenPluginTest.kt
settings.gradle.kts

Refactor of GraphQL client to support batch operations.
Instead of injecting an instance of GraphQL client to a generated operation class, generated classes are now simple POJOs that represent underlying GraphQL request. This change breaks the tight coupling between generated classes and client implementation and allows clients to execute arbitrary `GraphQLClientRequest`s.
Old generated model
```kotlin
class HelloWorldQuery(
private val graphQLClient: GraphQLKtorClient<*>
) {
suspend fun execute(requestBuilder: HttpRequestBuilder.() -> Unit = {}): GraphQLResponse<HelloWorldQuery.Result> =
graphQLClient.execute(HELLO_WORLD_QUERY, "HelloWorldQuery", null, requestBuilder)
data class Result(
val helloWorld: String
)
}
```
New generated model
```kotlin
class HelloWorldQuery: …
```

[client] Batch query support

---

examples/build.gradle.kts
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorGraphQLContextFactory.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/context/MyGraphQLContext.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/context/MyGraphQLContextFactory.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/execution/MySubscriptionHooks.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/subscriptions/SimpleSubscription.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/GraphQLContext.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLContextFactory.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/requestExtensions.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/RequestExtensionsKtTest.kt
servers/graphql-kotlin-spring-server/build.gradle.kts
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/SubscriptionAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLContextFactory.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionHooks.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandler.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionSessionState.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringSubscriptionGraphQLContextFactory.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/context/GraphQLContextFactoryIT.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandlerTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionWebSocketHandlerIT.kt
website/docs/schema-generator/execution/contextual-data.md
website/docs/server/graphql-context-factory.md
website/docs/server/graphql-request-handler.md
website/docs/server/graphql-request-parser.md
website/docusaurus.config.js

There are two issues we are fixing here:
* The `GraphQLContextFactory` should support `suspend` functions
* Subscriptions need to support getting a null context from the factory
Supporting `suspend` functions is easy enough. We just updated the interface. However that also means in `ApolloSubscriptionProtocolHandler` we need to be able to run the suspend function in a class that deals with reactor `Flux`. Once we generate the context it could come back as `null`. If it does our old logic was to return a class `DefaultGraphQLContext`. However, this was now blowing up because if you had a custom context of type `MyCustomContext` and used that as an argument in your subscription functions, graphql-java was throwing an illegal argument exception because we were trying to pass …

Generate context with suspend and nullable in subscriptions

---

.github/workflows/release-docs.yml

remove reference to old `docs` folder

fix release-docs workflow

---

examples/server/ktor-server/README.md
examples/server/spring-server/README.md

Incorrect gradle target for executing, or building, the example spring server. Updated to correct targets:
` ./gradlew :spring-server:build`
`./gradlew :spring-server:bootRun`

Incorrect Gradle Target for Executing/Building the Example Spring Server

---

examples/federation/base-app/src/main/resources/application.yml
examples/federation/extend-app/src/main/resources/application.yml
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/context/MyGraphQLContext.kt
generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/FederatedGraphQLContext.kt
gradle.properties
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/FederatedSchemaAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringDataFetcher.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLContext.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLContextFactory.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/FederationConfigurationTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/context/GraphQLContextFactoryIT.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringDataFetcherTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLContextTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt
website/docs/schema-generator/federation/federation-tracing.md
website/docs/server/graphql-context-factory.md
website/docs/server/spring-server/spring-beans.md
website/docs/server/spring-server/spring-graphql-context.md
website/docs/server/spring-server/spring-properties.md
website/sidebars.json

For federation we need to send back tracing metrics to get usage reporting. We can use Apollo's library: https://github.com/apollographql/federation-jvm
This adds a new `FederatedGraphQLContext` to the `graphql-kotlin-federation` package. It also creates a new `SpringGraphQLContext` and `SpringGraphQLContextFactory` that implement these required methods.
If users to do not have a custom context, they just need to set `graphq.federation.tracing.enabled=true`.
If there is a custom context, it should extend `SpringGraphQLContext` and also still have the properties set.
Since we are changing the required type of `SpringGraphQLContextFactory` this is a major change in the `4.x.x` branch.
Reimplements https://github.com/ExpediaGroup/graphql-kotlin/pull/962 for merge conflicts
Support in 3.x.x …

Add support for federated tracing

---

website/docs/client/client-serialization.mdx

Introspection is the default way of obtaining the GraphQL schema. Updating docs to reflect this.
N/A

[docs] update serialization docs to use introspection

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/SubscriptionAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLSubscriptionHandlerTest.kt

Pass the `DataLoaderRegistryFactory` to the subscription handler so for each request we can generate a `DataLoaderRegistry` to give to graphql-java
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/602

Add data loader registry to subscription execution

---

clients/graphql-kotlin-client-jackson/src/main/kotlin/com/expediagroup/graphql/client/jackson/GraphQLClientJacksonSerializer.kt
clients/graphql-kotlin-client-jackson/src/test/kotlin/com/expediagroup/graphql/client/jackson/GraphQLClientJacksonSerializerTest.kt
clients/graphql-kotlin-client-jackson/src/test/kotlin/com/expediagroup/graphql/client/jackson/data/EnumQuery.kt
clients/graphql-kotlin-client-jackson/src/test/kotlin/com/expediagroup/graphql/client/jackson/data/enums/TestEnum.kt
clients/graphql-kotlin-client-serialization/build.gradle.kts
clients/graphql-kotlin-client-serialization/src/main/kotlin/com/expediagroup/graphql/client/serialization/GraphQLClientKotlinxSerializer.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/GraphQLClientKotlinXSerializerTest.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/EnumQuery.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/FirstQuery.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/OtherQuery.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/PolymorphicQuery.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/ScalarQuery.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/enums/TestEnum.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/polymorphicquery/BasicInterface.kt
clients/graphql-kotlin-client-serialization/src/test/kotlin/com/expediagroup/graphql/client/serialization/data/scalars/UUID.kt
clients/graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/serializer/GraphQLClientSerializer.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLEnumTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/enums/enums/CustomEnum.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/enums/enums/CustomEnum.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/enums/CustomEnum.kt
plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql

Update client generation logic to always generate enums in UPPERCASE and then use corresponding Jackson (`@JsonProperty`) or kotlinx-serialization (`@SerialName`) annotation to convert those back to expected schema values. This allows us to support enum values that cannot be used directly in Kotlin (i.e. `name` and `ordinal`) as they would clash with built in methods.
This PR also resolves incorrect serialization of requests when using `kotlinx-serialization`. We were applying our custom `AnySerializer` to serialize the requests which was in turn incorrectly serializing enums and custom scalars. I changed the logic to construct correct `KSerializer` based on the specified request.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1075

[client] generate enums in UPPERCASE and fix kotlinx request serialization

---

.github/workflows/release-code.yml

This is a follow up to https://github.com/ExpediaGroup/graphql-kotlin/pull/1091 which seems to be working fine.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1091

[build] update release build to automatically release to nexus

---

website/docs/server/graphql-context-factory.md
website/docs/server/spring-server/spring-graphql-context.md

Add docs explaining that the context should be extended from the Spring specific classes when using `graphql-kotlin-spring-server`
Using the new [Docusaurus Admonitions](https://docusaurus.io/docs/next/markdown-features/admonitions)
https://github.com/ExpediaGroup/graphql-kotlin/issues/1096

Add docs on the spring specific context requirements

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/PlaygroundRouteConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandler.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/subscriptionUtils.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionUtilsKtTest.kt

The playground route is being set as `/null/graphql` this is because the default value is being set as the string value `"null"` and not a strict null value
https://github.com/ExpediaGroup/graphql-kotlin/pull/1098

Fix playground route logic

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/exceptions/InvalidWrappedTypeException.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kParameterExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kTypeExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcherTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KParameterExtensionsKtTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KTypeExtensionsKtTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/OptionalInputTest.kt

When we have an optional input of lists or arrays it would have a casting exception if the input was converted to a linked hash map or array.
This resolves this issue by first checking for the optional input type, then reusing the same code we have for converting all the other arguments, including lists and arrays.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1100

Support OptionalInput of any list or array

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLObjectTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/enums/EnumQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/enums/EnumQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/FirstQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/SecondQuery.kt

While we clearly were using wrong package name for referencing enum member. I don't know why the test cases were generating code without that invalid reference (generated code is compared against the sources stored under `test/data` directory).
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1106

[client] fix unknown enum import

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/model/DataLoaderQueryModel.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/DataLoaderQuery.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/SimpleQuery.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateProperty.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GeneratePropertyTest.kt

Add support for overriding the return type of properties with the `willResolveMond` hook. We now call this hooks in `generateProperty` so KClass properties can also support things like `Set` overrides.
We probably could look into renaming the hook `willResolveReturnType` in v5.
https://github.com/ExpediaGroup/graphql-kotlin/discussions/1110

Call hooks for return type on properties

---

website/docs/server/graphql-server.md

Just a small typo in the documentation.

Fixed typo "reccomend" => "recommend"

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLObjectTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/enums/EnumQuery.graphql
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/enums/EnumQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/enums/enums/OtherEnum.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/enums/EnumQuery.graphql
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/enums/EnumQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/enums/enums/OtherEnum.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/FirstQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/SecondQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql

We are providing default `__UNKNOWN_VALUE` value for enums. When generating references to this default value using kotlinpoet `MemberName` it was adding redundant explicit import of that enum value. If there were multiple fields asking for different enums then compilation would fail with multiple imports of `__UNKNOWN_VALUE`. Updated logic to use the explicit `TypeName` of the enum and `Name` of the constant.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1114

[client] support selection of multiple enums

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FlowSubscriptionExecutionStrategy.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/FlowSubscriptionExecutionStrategyTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandler.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/SubscriptionConfigurationTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLSubscriptionHandlerTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/ApolloSubscriptionProtocolHandlerTest.kt

Update `FlowSubscriptionExecutionStrategy` to support Kotlin `Flow` natively (i.e. convert publishers to flows vs old logic of converting flows to publishers). While the Reactor `Flux` has a concept of subscriber context (and has full interop with Kotlin `Flow`), generic `Publisher` does not. This means that whenever we convert to a publisher we loose any contextual data that was available. This PR makes minimal changes to get our Spring server working with the updated subscription execution strategy.
TLDR Reverts the changes from #972 and updates the server to use the original flow subscription handler.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1116
https://github.com/ExpediaGroup/graphql-kotlin/pull/972

update FlowSubscriptionExecutionStrategy to support flow natively

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/annotations/GraphQLValidObjectLocations.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/exceptions/InvalidObjectLocationException.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInputObject.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateObject.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/utils/validateObjectLocation.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateInputObjectTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateObjectTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/utils/ValidateObjectLocationKtTest.kt
website/docs/schema-generator/customizing-schemas/restricting-input-output.md
website/sidebars.json

Kotlin classes can be used as GraphQL input types, output types, or both. If you want to enforce that a Kotlin class only be used as an input or output type, include this annotation, `@GraphQLValidObjectLocations`, with the preferred location parameter.
By default, classes will be allowed as both input and output types.
We also use this feature internal at Expedia Group but had a custom annotation. This feature is handy to have in the open source library.
N\A

Add valid locations annotation 

---

website/docs/client/client-serialization.mdx

While updating the graphql client to the new version I ran into a small confusion with the documentation. After some research I would assume that there was a copy/paste error and the Class was not renamed. So I thought I will create a Pull Request for this :)

Fix Classname of ktor client

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generateClient.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/exceptions/SchemaUnavailableException.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/GenerateInvalidClientIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLTestUtils.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateClientAction.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateClientParameters.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTask.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt

Simply allow loading the schema file from your classpath, this allows you to include a maven dependency that stores your graphql SDLs as a package.
```xml
<plugin>
<groupId>com.expediagroup</groupId>
<artifactId>graphql-kotlin-maven-plugin</artifactId>
<version>4.0.0-SNAPSHOT</version>
<dependencies>
<dependency>
<groupId>com.expedia.schemas</groupId>
<artifactId>schemas</artifactId>
</dependency>
</dependencies>
<executions>
<execution>
<goals>
<goal>generate-client</goal>
</goals>
<configuration>
<packageName>com.expedia.graphql.generated.foobarservice</packageName>
<schemaFile>expedia-schemas/foobar-service/schema.graphql</schemaFile>
<queryFileDirectory>${project.basedir}/src/main/resources/queries</queryFileDirectory>
</configuration>
</execution>
</executions>
</plugin>
```
I would …

Client Generation - Allow schema to be on the classpath

---

.github/dependabot.yml
.github/workflows/pr-check.yml

Add a dependabot file and exclude JVM checks when only MD files are changed

Add dependabot file to restrict to gradle

---

plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/downloadSchema.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/introspectSchema.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/DownloadSchemaTest.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/IntrospectSchemaTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTaskIT.kt

It looks like using CIO engine causes some issues with the classpath (https://github.com/ExpediaGroup/graphql-kotlin/issues/1084). Unsure what is the root cause of the classpath issue - it looks like CIO engine relies on coroutines-core `native-mt` vs regular artifact that we pull in. Switching to a different engine seems to resolve the classpath issue.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1084

[plugin] change tasks HttpClient engine from CIO to Apache

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactory.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/directives/KotlinFieldDirectiveEnvironment.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/directives/KotlinSchemaDirectiveEnvironment.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateArgument.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateEnum.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInputObject.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInputProperty.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInterface.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateObject.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateScalar.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateUnion.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinDirectiveWiringFactoryTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinSchemaDirectiveEnvironmentTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/KotlinSchemaDirectiveWiringTest.kt

To override datafetchers for all fields in an object using a directive, the environment should expose the `GraphQLCodeRegistry`.
Or at least the only way of overriding datafetchers from a directive on an object was by iterating over the fields and setting the datafetcher.
Something like this I expect to work:
```kt
override fun onObject(environment: KotlinSchemaDirectiveEnvironment<GraphQLObjectType>): GraphQLObjectType {
val obj = environment.element
val reg = environment.codeRegistry
val expressionArgument = environment.directive.getArgument("expression")
val expressionString = expressionArgument?.value as? String ?: return obj
val authorizationManager = authorizationManagerForExpression(expressionString)
obj.fieldDefinitions.forEach { field ->
val fetcher = reg.getDataFetcher(obj, …
```

pass code registry to all directive environments

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/subscriptions/SimpleSubscription.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateScalar.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateScalarTest.kt

Extended scalars were deprecated in `graphql-java` v15 in favor of separate `graphql-java-extended-scalars` project. Extended scalars are problematic as clients have to explicitly know how to handle them and what they represent. Due to the all the drawbacks, instead of automatically providing support for deprecated functionality, users should explicitly opt-in into this functionality by using custom hooks.

[generator] remove extended scalars

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/utils/functionReturnTypes.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/utils/FunctionReturnTypesKtTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/DataFetcherResultListTest.kt

A fix for the schema generator to support List<DataFetcherResult<T>> as a return for functions, most notably to support local  context. GraphQL-Java supported using DataFetcherResult as an item for list fields with this [PR](https://github.com/graphql-java/graphql-java/pull/1567)
[Issue 1146](https://github.com/ExpediaGroup/graphql-kotlin/issues/1146)

Added ability to return lists of DataFetcherResults in functions with Schema Generator

---

examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/KtorGraphQLServer.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/ktorGraphQLSchema.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/BookQueryService.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/CourseQueryService.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/UniversityQueryService.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/dataloaders/BookDataLoader.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/dataloaders/CourseDataLoader.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/dataloaders/UniversityDataLoader.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/models/Book.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/models/Course.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/models/University.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/models/User.kt

Long has been removed as a supported scalar so the Ktor example needed some updates.
Here is a fully query with variables working after updates

Fix issues with Long in schema

---

plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
website/docs/plugins/gradle-plugin-tasks.mdx

Update Gradle plugin to allow client generation by specifying local schema file in the extension. Using extension with local schema file is equivalent to configuring the `GraphQLGenerateClientTask` directly.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1136: Allow schema to be on the classpath
https://github.com/ExpediaGroup/graphql-kotlin/pull/1190: Add local schema file support to Gradle plugin

Add local schema file support to Gradle plugin extension

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/DataFetchingEnvironmentExtensionsKtTest.kt

Added `getValuesFromDataLoader` helper function to make it easier to call `loadMany`. This works very similar to `getValueFromDataLoader`, but accepts a list of keys and returns a list of values. `getLoaderName` is created because both functions lookup the DataLoader instance the same way.

getValuesFromDataLoader helper function

---

gradle.properties

Kotlinx.html is now publishing to Maven central and we have removed deps on Jcenter so we need to make sure we are using the latest version to get the one in maven central
https://github.com/Kotlin/dokka/releases/tag/v1.5.0
https://github.com/ExpediaGroup/graphql-kotlin/runs/3146969635?check_suite_focus=true#step:6:38

Update dokka to 1.5

---

plugins/graphql-kotlin-gradle-plugin/README.md
plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateTestClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAndroidIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTaskIT.kt
website/docs/plugins/gradle-plugin-tasks.mdx
website/docs/plugins/gradle-plugin-usage.mdx

By changing `queryFileDirectory` input from a String to a Directory and dropping support for providing schema file path in favor of explicit schema file, Gradle will now be able to correctly monitor task inputs to to determine whether the task is up-to-date.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1232

[plugin] update generateClientTasks to correctly monitor inputs

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/annotations/GraphQLUnion.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/exceptions/InvalidCustomUnionException.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/annotationExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCache.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateFunction.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateGraphQLType.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInterface.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateList.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateProperty.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateUnion.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCacheTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateUnionTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/CustomUnionAnnotationTest.kt

Since the schema can be generated from code you can use existing Kotlin classes from common libraries to define shared models. However if you want to declare an object defined in the library as implementing some new interface or union in your service it is not possible, since we can't modify the class definition to add Kotlin code to it.
These changes would allow us to use `Any` as the return type in the schema but then, through annotations, modify the schema return type to match the new class we want to use.
For example in an SDL-First world you could have this Kotlin class defined in some library
```kotlin
data class SharedModel(val foo: String)
```
And then write your schema as the following
```graphql
interface CustomServiceInterface {
foo: String!
}
type SharedModel implements …
```

Backport GraphQLUnion to 4.x.x

---

website/versioned_docs/version-4.x.x/schema-generator/writing-schemas/unions.md

The changes in the linked PR below are to the 4.x.x branch for the code, but the docs site is always run off the master branch so we need to make two separate PRs.
https://github.com/ExpediaGroup/graphql-kotlin/pull/1234

Backport Union changes to 4xx docs

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/exceptions/MissingArgumentException.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/invalid/missing_argument/MissingArgumentQuery.graphql
plugins/client/graphql-kotlin-client-generator/src/test/data/invalid/missing_argument/exception.txt

Inputs to queries/mutations are either hard coded inside the queries OR provided through variables. As such we never checked for field definition inputs as we only generate simple POJOs that represent the output type results.
This PR adds logic to calculate all required field definition inputs and verifies that selection set specifies them all.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1237

[client] verify selection sets specify all required inputs

---

clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClientTest.kt

It looks like runners used for Actions occasionally might be getting busy and as a result our unit test logic does not encounter timeout. Bumping up the WireMock response delay to address it.

junit fix - bump up the query timeout

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check.yml
.github/workflows/release-code.yml
build.gradle.kts
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KTypeExtensionsKtTest.kt

New version of Dokka supports Java 9+ so we can just run a single build using current LTS (11) with targetJVM 1.8

[build] update to build on Java 11 with targetJVM 1.8

---

examples/build.gradle.kts
examples/client/gradle-client/build.gradle.kts
examples/client/gradle-client/src/main/kotlin/com/expediagroup/graphql/examples/client/gradle/ULocaleScalarConverter.kt
examples/client/gradle-client/src/main/resources/ExampleQuery.graphql
examples/client/maven-client/pom.xml
examples/client/maven-client/src/main/kotlin/com/expediagroup/graphql/examples/client/maven/ULocaleScalarConverter.kt
examples/client/maven-client/src/main/resources/ExampleQuery.graphql
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/Application.kt
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/SimpleQueries.kt
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/model/ScalarWrapper.kt
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/scalars/ULocaleCoercing.kt
examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/scalars/UUIDCoercing.kt
examples/client/src/integration/wiremock/__files/schema.graphql
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/exceptions/InvalidSelectionSetException.kt
plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql

Test PR to show ULocale client scalar converters

Test scalar converters with Ulocale

---

plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGeneratorContext.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLCustomScalarTypeAlias.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLInputObjectTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateJacksonOptionalInputScalarSerializer.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateVariableTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalar_input/CustomScalarInputQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalar_input/inputs/ScalarWrapperInput.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalar_input/scalars/OptionalScalarInputSerializer.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalar_input/CustomScalarInputQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalar_input/inputs/ScalarWrapperInput.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/FirstQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/SecondQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/inputs/ComplexArgumentInput.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/variables/KotlinXInputQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/variables/inputs/SimpleArgumentInput.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/GenerateKotlinxClientIT.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLTestUtils.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars/src/main/kotlin/com/expediagroup/scalars/ScalarWrapper.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars/src/test/kotlin/com/expediagroup/scalars/CustomScalarApplicationTests.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars/src/test/resources/CustomScalarsQuery.graphql
website/docs/client/client-customization.mdx
website/docs/client/client-features.mdx

Update client generation logic to support serializing optional scalar input.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1263

[client] support optional scalar input

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/FieldSet.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt

When generating federated base schema (i.e. without extended types), we were manually adding invalid required federated types (e.g. directive definitions). Generated federated schema was correct when directives were generated from the annotations. Manually added federated directives were incorrectly specifying their arguments as nullable `_FieldSet`.
SDL is printed as a debug information at a startup and can also be generated using one of our plugins. Depenendng how you use this federated SDL, this may or may not be a problem - Apollo federation 1.0 does not allow re-definition of the types across schemas so federated system types have to be scrubbed from published schema SDL and at runtime relies on `_service` query that returns modified SDL (again without federated directives). …

[federation] fix non-federated schema SDL

---

generator/graphql-kotlin-schema-generator/build.gradle.kts
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kFunctionExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateFunction.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KFunctionExtensionsKtTest.kt

This PR updates `FunctionDataFetcher` so that it logs a warning when injecting a `GraphQLContext`.  This functionality is [deprecated](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/website/docs/schema-generator/execution/contextual-data.md#interface-injection-deprecated).  Unlike the `GraphQLContext` interface itself, which is annotated `@deprecated, there is no compile or runtime time warning when using `GraphQLContext` interface injection in a query or mutation.
* discussion: #1305
* supersedes: #1306

[generator] add runtime warning on deprecated context usage

---

plugins/client/graphql-kotlin-client-generator/README.md

Fix links to latest released version for `graphql-kotlin-client-generator`. It was pointing to old module that was renamed.
N/A

[docs] fix readme links for client generator

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateGraphQLObjectTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generatePropertySpecs.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateTypeName.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/IncludeSkipDirectivesQuery.graphql
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/IncludeSkipDirectivesQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/enums/CustomEnum.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/include_skip_directives/includeskipdirectivesquery/ScalarWrapper.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/input_lists/InputListQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/scalar_typealias/scalaraliasquery/ScalarWrapper.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/customscalarquery/ScalarWrapper.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/object/complexobjectquery/ComplexObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/firstquery/ComplexObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/firstquery/ScalarWrapper.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/secondquery/ScalarWrapper.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/object/complexobjectquery/ComplexObject.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/settings.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/main/kotlin/com/expediagroup/directives/Application.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/main/kotlin/com/expediagroup/directives/SimpleQuery.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/main/resources/application.yml
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/test/kotlin/com/expediagroup/directives/ApplicationTest.kt
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/src/test/resources/IncludeSkipQuery.graphql
plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/JUnitQuery.graphql
plugins/graphql-kotlin-gradle-plugin/src/test/resources/templates/JUnit.mustache

Update client generator logic to handle `@skip` and `@include` directives. If directives are specified they will override nullability of the underlying field to always be nullable. 
Supersedes: https://github.com/ExpediaGroup/graphql-kotlin/pull/1327
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1282

[client] support @include and @skip directives

---

examples/server/ktor-server/README.md
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/GraphQLModule.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/ktorGraphQLSchema.kt

Not having the GraphQL schema complete with directives caused me troubles (see linked PR)
In spring-server, the `/sdl` endpoint expose the GraphQL schema
If this commit is merged, it will be exposed as well in the ktor-server example
https://github.com/ExpediaGroup/graphql-kotlin/pull/1350

examples/ktor-server: expose GraphQL Schema at /sdl

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt

Various instrumentations (e.g. tracing) rely on `TrivialDataFetcher` distinction to skip their execution. Looks like we missed this when creating this data fetcher.
N/A

[generator] mark default PropertyDataFetcher as "trivial"

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateArgument.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInputProperty.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateInputPropertyTest.kt
website/docs/schema-generator/customizing-schemas/deprecating-schema.md

With recent GraphQL spec changes, deprecation should be supported on fields, input fields (new), arguments (new) and enum values. This change adds the support for deprecating input fields.
Argument deprecation is not supported as Kotlin `@Deprecated` is not applicable to parameters.
See https://youtrack.jetbrains.com/issue/KT-25643

[generator] support input field deprecation

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/exceptions/InvalidPropertyReturnTypeException.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/filters/propertyFilters.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/filters/PropertyFiltersTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateObjectTest.kt

Currently we don't support lambda parameters. Attempting to use a lambda property blows up with somewhat ambiguous messages (lambda return type is outside of supported packages/cannot calculate erasure type for suspendable lambda). Currently it was also not possible to filter out lambda properties using `@GraphQLIgnore` annotations as it was applied AFTER attempting to read lambda erasure type (which blows up as it cannot be calculated).
This PR adds new property filter that checks whether property is a lambda and throws `InvalidPropertyReturnTypeException` if it is. Also moved `@GraphQLIgnore` filter to be applied before we attempt to calculate JVM erasure (used to verify property type is not blacklisted).
Throwing exception from a filter might not be ideal but IMHO is a better …

[generator] filter lambda properties

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLContextExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLSchemaExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/GraphqlTypeExtensions.kt

In the `GraphQLContext` map we often use `KClass` as a key
```kotlin
environment.graphQlContext.getOrDefault(CoroutineScope::class, CoroutineScope(EmptyCoroutineContext))
```
adding some inline reified extension functions to reduce the verbosity to allow
```kotlin
// explicitly provide type
val scope = environment.graphQlContext.get<CoroutineScope>() // return nullable 
// type can also be inferred
val scope: CoroutineScope = environment.graphQlContext.get()
// provide default value, type inferred from default value
environment.graphQlContext.getOrDefault(CoroutineScope(EmptyCoroutineContext))
// provide lambda to compute default value, type inferred from default value
environment.graphQlContext.getOrElse { CoroutineScope(EmptyCoroutineContext) } 
```
Resolves …

feat: add GraphQLContext extension functions

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/filters/superclassFilters.kt
website/docs/getting-started.mdx
website/docs/schema-generator/writing-schemas/fields.md
website/docs/schema-generator/writing-schemas/interfaces.md
website/sidebars.js

`graphql-kotlin-schema-generator` automatically applies some basic filtering logic to exclude invalid properties/functions. Filters ensure that processed properties/functions are public, have valid name, are not ignored, etc.
Users can also provide some additional filtering logic to exclude properties/functions but they are currently applied before basic filters. This PR updates the filtering logic to apply basic filtering first and then apply custom validations.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1368

[generator] apply hooks after filtering properties and functions

---

gradle.properties

Update to latest version of `federation-jvm` that supports tracing based on new `GraphQLContext` map.

[build] update to latest federation-jvm

---

examples/server/spring-server/src/main/resources/META-INF/services/com.expediagroup.graphql.plugin.schema.hooks.SchemaGeneratorHooksProvider

The class name for the service provider is incorrect in example for SchemaGeneratorHooksProvider

Class name in SchemaGeneratorHooksProvider example

---

examples/federation/gateway/index.js
examples/federation/gateway/package-lock.json

Regenerate `package-lock` with latest deps and update gateway logic to use `supergraphSdl` syntax.

[examples] update federation gateway example to latest

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check-docs.yml
.github/workflows/pr-check.yml
.github/workflows/publish-latest-docs.yml
.github/workflows/release-code.yml

Mainly for using gradle-build-action to speed up build on CI, and bump action versions by the way.

Optimize CI a bit

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/Application.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/hooks/CustomSchemaGeneratorHooks.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/model/CustomScalarInput.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/model/MyValueClass.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/ScalarQuery.kt
website/docs/schema-generator/writing-schemas/scalars.md

It is often beneficial to create a wrapper around the underlying primitive type to better represent its meaning. Inline value classes can be used to optimize such use cases - Kotlin compiler will attempt to use underlying type directly whenever possible and only keep the wrapper classes whenever it is necessary.
In order to use inline value classes in your schema, you need to register it using hooks and also provide value unboxer that will be used by `graphql-java` when dealing with its wrapper object.
```kotlin
@JvmInline
value class MyValueClass(
val value: String
)
class MyQuery : Query {
fun inlineValueClassQuery(value: MyValueClass? = null): MyValueClass = value ?: MyValueClass("default")
}
class MySchemaGeneratorHooks : SchemaGeneratorHooks {
override fun …
```

[docs] documentation on inline value classes

---

website/docusaurus.config.js

Fixing docs by providing /docs ref for the Expedia logo
https://github.com/ExpediaGroup/graphql-kotlin/issues/1400

[docs] fix breaking page on Expedia logo click

---

README.md
executions/graphql-kotlin-dataloader-instrumentation/README.md
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/AbstractSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/SyncExecutionExhaustedInstrumentationParameters.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/ExecutionBatchState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/ExecutionStrategyState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/ExecutionStrategySyncState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/TestGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/AstronautService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/MissionService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/extensions/ListExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/repository/AstronautRepository.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/repository/MissionRepository.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

Adding a Custom Instrumentation that will dispatch a [DataLoaderRegistry](https://github.com/graphql-java/java-dataloader/blob/master/src/main/java/org/dataloader/DataLoaderRegistry.java), when the synchronous execution of all operations sharing the same `GraphQLContext` was **exhausted**
by **exhausted** it means that all the AST paths were visited until finding a leaf scalar or a non-trivial dataFetcher that returns a `CompletableFuture`
This Instrumentation keeps track on the state of each [ExecutionStrategy](https://www.javadoc.io/doc/com.graphql-java/graphql-java/18.0/graphql/execution/ExecutionStrategy.html) associated with an operation using the following data structure
This PR is related to [this discussion opened in graphql-java](https://github.com/graphql-java/graphql-java/discus …

feat: DataLoader Sync Execution Exhaustion Instrumentation

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/annotations/GraphQLUnion.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/annotationExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCache.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateGraphQLType.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateUnion.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/AnnotationExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCacheTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateUnionTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/CustomUnionAnnotationTest.kt
website/docs/schema-generator/writing-schemas/unions.md

the `@GraphQLUnion` annotation does not support directives. This is to add support by allowing it to be a meta-annotation where you can create an annotation for your union that you then annotate with `@GraphQLUnion` and directives
```
// Defined in some other library
class SharedModel(val foo: String)
// Our code
class ServiceModel(val bar: String)
@SomeDirective
@GraphQLUnion(
name = "CustomUnion",
possibleTypes = [SharedModel::class, ServiceModel::class],
description = "Return one or the other model"
)
annotation class CustomUnion
class Query {
@CustomUnion
fun getModel(): Any = ServiceModel("abc")
}
```

feat: support directives with the union annotation

---

gradle.properties

The MaxPermSize JVM argument was deprecated in JDK 8, per [this document](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html):
```
-XX:MaxPermSize=size
Sets the maximum permanent generation space size (in bytes). This option was deprecated in JDK 8, and superseded by the -XX:MaxMetaspaceSize option.
```
Thus, since JDK 8, this argument hasn't actually done anything, but has been relatively harmless all the same.
However, Java 17 actually outright removes this parameter. Running the repo's `gradlew` with Java 17 thus results in the following error:
```
% ./gradlew check
Starting a Gradle Daemon, 1 busy and 1 stopped Daemons could not be reused, use --status for details
FAILURE: Build failed with an exception.
* What went wrong:
Unable to start the daemon process.
This …
```

Remove deprecated XX:MaxPermSize JVM argument from gradle properties, causing failures with Java 17

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCache.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCacheKey.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/GraphQLKTypeMetadata.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateDirective.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateGraphQLType.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateDirectiveTest.kt
website/docs/schema-generator/customizing-schemas/directives.md

With the refactoring of our argument parsing logic (https://github.com/ExpediaGroup/graphql-kotlin/pull/1379) we dropped the support for the arrays. This had a side effect that directives could no longer be declared as accepting a list of arguments. Adding back support of arrays/varargs just for the directives.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1404

[generator] support directive array/vararg parameters

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateInputObjectTest.kt
website/docs/schema-generator/writing-schemas/arguments.md

Avoid adding the `Input`-suffix for classes restricted to being used as input objects only using the `@GraphQLValidObjectLocations`-annotation. Suffixing the type with `Input` is not necessary, since no name collision can happen here.
#1324

feat(generator): avoid adding `input`-suffix for input-only classes

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/annotationExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateGraphQLType.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooksTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/AnnotationExtensionsTest.kt

When using the `@GraphQLUnion` as a meta annotation, the KType is `Any` when the type for the field is being generated by reflection. The correct type is actually the annotation on the field with the `@GraphQLUnion` meta annotation. In this case, the type passed to the hook needs to be that annotation since that is the class with other annotations on it, which could be needed by the hook.

fix: willAddGraphQLTypeToSchema needs annotations from field

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateInputObjectTest.kt
website/docs/schema-generator/writing-schemas/arguments.md

After some discussion we decided to revert this PR given that will cause a Breaking Change and we don't see a particular improvement in doing this, indeed we believe that adding semantics (the Input suffix) to the type, will help to have a more verbose schema.

Revert "feat(generator): avoid adding `input`-suffix for input-only classes"

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/convertArgumentValue.kt
website/docs/schema-generator/writing-schemas/scalars.md

Value types can be represented in various ways:
1) Unwrapped, as the underlying type
2) Unwrapped, as a custom scalar type representing the value type
3) Wrapped, like a regular class
There are valid use cases for all 3, though in my opinion options number 2 and 3 are generally the best, as they maintain the extra type information provided by the value class in the schema.
Currently, the docs only discuss option 1, and option 2 is actually not possible.
This PR makes a minor change to the code to support option 2, and documents all 3 value class representations.
NOTE: While the code change works for me, I would like to add tests, but frankly I'm not sure of the best way to do so. Some guidance would be appreciated.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1370 …

Value type improvements

---

generator/graphql-kotlin-schema-generator/build.gradle.kts

allow minor releases of `graphql-java` from 17.2 until 18.0
[version declaration syntax](https://docs.gradle.org/current/userguide/single_versions.html)

feat: allow graphql java version range until v18

---

generator/graphql-kotlin-federation/README.md
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/FieldSet.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/KeyDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ProvidesDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/RequiresDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/types/_FieldSet.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/types/_Service.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/types/ServiceTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/federated-schemas.md

Per [Apollo Federation Spec](https://www.apollographql.com/docs/federation/federation-spec/), `_service` should return non-nullable `_Service` object type.
N/A

[generator] fix Federation _service query definition

---

examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/dataloaders/BookDataLoader.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/dataloaders/CourseDataLoader.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/dataloaders/UniversityDataLoader.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/dataloaders/CompanyDataLoader.kt
executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/AstronautService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/MissionService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/PlanetService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/ProductService.kt
executions/graphql-kotlin-dataloader/README.md
executions/graphql-kotlin-dataloader/build.gradle.kts
executions/graphql-kotlin-dataloader/src/main/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoader.kt
executions/graphql-kotlin-dataloader/src/main/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistryFactory.kt
executions/graphql-kotlin-dataloader/src/test/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistryFactoryTest.kt
executions/graphql-kotlin-dataloader/src/test/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistryTest.kt
generator/graphql-kotlin-schema-generator/build.gradle.kts
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/GraphQLRequestHandlerTest.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/RequestExtensionsKtTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/SchemaConfigurationTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLSubscriptionHandlerTest.kt
website/docs/server/data-loader/data-loader.md

originally we decided to have the `KotlinDataLoader` to allow passing the `BatchLoader` fn instead of the `DataLoader` instance because of the new Instrumentation to dispatch a `DataLoaderRegistry` in a more efficient way, so for that we had to decorate the `DataLoader` `CacheMap` before instantiating the `DataLoader`.
a PR in [graphql-java-dataloader](https://github.com/graphql-java/java-dataloader/pull/115) was merged to natively support what we where doing to the `CacheMap`, so we can go back to allow passing a `DataLoader`
so we can theorically go back to previous KotlinDataLoader implementation.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1457

[executions] KotlinDataLoader to provide DataLoader

---

generator/graphql-kotlin-schema-generator/build.gradle.kts
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/directives/DirectiveMetaInformation.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateDirective.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooksTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateDirectiveTest.kt

Add new `willGenerateDirective` hook that allows for special handling of directive to be build (including returning a prebuild definition). Needed to support Federation v2.

[generator] add willGenerateDirective hook

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/ExecutionContextExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/execution/AbstractExecutionLevelDispatchedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/AbstractSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/AstronautGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/AstronautService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

As `graphql-java` documentation highlights
https://www.graphql-java.com/documentation/batching#data-loader-only-works-with-asyncexecutionstrategy
`DataLoader` instrumentation only works with `AsyncExecutionStrategy`, so `Mutation` operations are excluded since those are executed with `AsyncSerialExecutionStrategy`

[executions] do not apply data loader instrumentation if execution is a Mutation

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/SubscriptionAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/SubscriptionConfigurationTest.kt
website/docs/schema-generator/execution/subscriptions.md
website/docs/schema-generator/federation/apollo-federation.mdx
website/docs/server/server-subscriptions.md
website/docs/server/spring-server/spring-subscriptions.md

Currently the `spring-server` automatically configures the subscription strategy that supports Kotlin `Flow`  but does not configure the hooks neccessary to use it. Updating `SubscriptionAutoConfiguration` to create `FlowSubscriptionSchemaGeneratorHooks` if bean is not available.
Cleaned up the federation docs to highlight that both hooks and execution strategy are needed for using `Flow`s in subscriptions. Added a note that the subscription protocol implemented in `spring-server` is deprecated.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1477

Update spring-server to use FlowSubscriptionSchemaGeneratorHooks

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/requestExtensions.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/RequestExtensionsKtTest.kt

add extensions to ExecutionInput to possibly receive extensions like APQ

feat: add extensions to ExecutionInput from GraphQLRequest

---

CONTRIBUTING.md

All other particles in headers are in small case, so "to" should be the same.
Also - smile, we created this contribution together with Eman Hammad, as part of our https://www.meetup.com/twosseng/
You can see the recording here:  https://tinyurl.com/bdednj3x

small letter case fix

---

build.gradle.kts

Specially useful when testing a debugging snapshots published to maven local repository

feat: publish sources for snapshots

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt

`_service { sdl }` query in Federation v2 should include schema `@link` information.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1476

[federation] fix service SDL to include schema @link info

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/BatchLoaderEnvironmentExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/BatchLoaderEnvironmentExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/BatchLoaderEnvironmentExtensionsTest.kt

extension function to allow BatchLoaderContext to access to a GraphQL Execution DataFetchingEnvironment,
specially useful if in your dataLoader you need to access to the DataFetchingEnvironment or the GraphQLContext inside of it to run batch logic, example: auth context, coroutines scope, etc.
```kotlin
DataLoaderFactory.newDataLoader { requests, environment: BatchLoaderEnvironment ->
val coroutineScope = environment.getGraphQLContext()?.get<CoroutineScope>()
coroutineScope.async {
// your batch logic for fetching data
}.asCompletableFuture()
}
```

feat: batchLoaderContext to access to dataFetchingEnvironment

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/KeyDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
website/docs/schema-generator/federation/federated-directives.md

Missed default value for the `resolvable` argument. Updated definition
```kotlin
directive @key(fields: _FieldSet!, resolvable: Boolean = true) repeatable on OBJECT | INTERFACE
```
N/A

[federation] fix @key fed v2 definition

---

build.gradle.kts
examples/gradle/wrapper/gradle-wrapper.properties
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FlowSubscriptionExecutionStrategy.kt
gradle.properties
gradle/wrapper/gradle-wrapper.properties
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGenerateClientIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAndroidIT.kt

Update to the latest dependencies. 
Fixed duplicate publication from `graphql-kotlin-gradle-plugin` - this was a warning before but latest version of `com.gradle.plugin-publish` treats it as a failure
NOTE: I did not update project to Kotlin v1.7 as I think that as a library we should target older version to allow for largest adoption.

[build] update to latest dependencies

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/model/Widget.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/annotations/GraphQLDeprecated.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/annotationExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/fieldExtenstions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/DirectiveTests.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/AnnotationExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/FieldExtenstionsKtTest.kt
website/docs/schema-generator/customizing-schemas/annotations.md
website/docs/schema-generator/customizing-schemas/deprecating-schema.md
website/docs/schema-generator/customizing-schemas/directives.md

Works the same than @Depcreated (which is still fine and supported)
but doesn't deprecate your own code, only deprecate in the client
Resolves #1492

Deprecate with @GraphQLDeprecated

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/convertArgumentValue.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/ConvertArgumentValueTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcherTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/OptionalInputTest.kt
website/docs/schema-generator/writing-schemas/arguments.md

filtering `targetConstructor` parameters to use the ones that are actually provided in the `inputMap` that way we can  rely on the default values for the parameters that are not specified
**IMPORTANT**
There is 1 scenario where default values is not going to work: 
Custom Scalars as they use kotlin value classes, regardless if the type is nullable or non nullable, `callBy` does not support constructors that have inline class parameters
see: 
https://youtrack.jetbrains.com/issue/KT-27598
it was partially fixed in: 
https://github.com/JetBrains/kotlin/pull/4746
will be included in kotlin 1.7
https://github.com/ExpediaGroup/graphql-kotlin/issues/1503

feat: filter arguments that are in the input

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/exceptions/MultipleConstructorsFound.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/convertArgumentValue.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/ConvertArgumentValueTest.kt

there are some use cases where no primary constructor will be defined, like in java classes, for those cases if no primaryConstructor is found use the first element on the constructors list, otherwise throw the error
https://github.com/ExpediaGroup/graphql-kotlin/issues/1515

feat: support argument types without primaryConstructor

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt

both `result` and `exception (t)` can be null depending on the execution result
this could cause some noise of implementation using this instrumentation

feat: mark ExecutionResult and Throwable as nullable

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt

Per issue #1522, the subscription handler likely was meant to be able
to be extended with the `executeSubscription` method overridden.
Resolves #1522

minor: Allow SpringGraphQLSubscriptionHandler to be extended

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/convertArgumentValue.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kParameterExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/execution/ConvertArgumentValueTest.kt

Treat nullable parameters that have no default value as if their default was set to null.
Nullable parameters that have a default value explicitly set will continue to use that as their default.
#1527

Make nullable parameters always optional

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
gradle.properties

Updated `FederatedSchemaGeneratorHooks` to use `ServiceSDLPrinter` provided by the `federation-jvm` in favor of our custom printer logic.

[federation] use federation-jvm ServiceSDLPrinter

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/OverrideDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt

`@override` directive is not repeatable. Fixing copy and paste bug.

[federation] fix override directive definition (v6)

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/OverrideDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt

`@override` directive is not repeatable. Fixing copy and paste bug.

[federation] fix override directive definition

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/FederatedTypeResolver.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/FederatedTypeSuspendResolver.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/resolverexecutor/FederatedTypePromiseResolverExecutor.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/resolverexecutor/FederatedTypeSuspendResolverExecutor.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/resolverexecutor/FederatedTypePromiseResolverExecutorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/resolverexecutor/FederatedTypeSuspendResolverExecutorTest.kt

Allowing each element in a `_entities` query batch to fail (by throwing an exception) without breaking the execution of the other representations
https://github.com/ExpediaGroup/graphql-kotlin/issues/1563

feat: graphQL errors per federated type element in batch

---

website/docs/schema-generator/writing-schemas/arguments.md

As part of an issue created within graphql-kotlin, we need to update the graphql-kotlin v6.x.x documentation stating that the custom scalars combined with optional/nullable types on constructors are not supported.
As a comment, this issue will get addressed once the update to Kotlin v1.7 is done.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1564

[docs] custom scalars & optional/nullable types

---

examples/gradle.properties

This option is failing builds locally for the examples project

[examples] Remove unrecognized JVM option

---

plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars_jackson/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/polymorphic_types_jackson/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt

following https://github.com/ExpediaGroup/graphql-kotlin/pull/1582/files

[build] update other references of springboot version

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
website/docs/schema-generator/federation/apollo-federation.mdx

We introduced Federation v2 support with opt-in mechanism in the `graphql-kotlin` v6 release. With v7 we can default to Federation v2 and subsequently drop Fed v1 support in `graphql-kotlin` v8.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1561

[federation] default to Federation v2

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generateClient.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGeneratorConfig.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateClientAction.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/config/GraphQLParserOptions.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateClientParameters.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/pom.xml
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt
website/docs/plugins/gradle-plugin-tasks.mdx
website/docs/plugins/maven-plugin-goals.md

Allows a user of the client generator to set the parser options for graphql-java. The base `generateClient()` function accepts a function type with receiver to customise the builder object, whilst the gradle and maven plugins provide an explicit list of (current) options permitted by graphql-java, with the exception of the [parsingListener](https://github.com/graphql-java/graphql-java/blob/13ab0009bd42b591bb4a542cd9c780a53515321d/src/main/java/graphql/parser/ParserOptions.java#L289).
Resolves #1526 
- I've picked fairly simple naming, but if we suspect any ambiguity of uses, or future collisions, it would be good to call that out so that it's clear this is configuration for the client generation only.
- Rather than abstract over `ParserOptions.Builder` the client module now exposes this …

Configure client generate parser options

---

examples/client/src/integration/wiremock/__files/schema.graphql
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ExtendsDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ExternalDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/InaccessibleDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/KeyDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ProvidesDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/RequiresDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/plugins/gradle-plugin-usage.mdx
website/docs/schema-generator/federation/apollo-federation.mdx
website/docs/schema-generator/federation/federated-directives.md

Fixed `@link` directive definition from:
```graphql
directive @link(url: String, import: [Import]) repeatable on SCHEMA
```
to
```graphql
directive @link(url: String!, import: [Import]) repeatable on SCHEMA
```
Cleaned up some federation docs as well.

[federation] fix @link definition and doc cleanup

---

examples/client/src/integration/wiremock/__files/schema.graphql
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/federated-schemas.md

`@extends` is no longer needed in Fed 2. 
Missed this in previous validation rule cleanup (https://github.com/ExpediaGroup/graphql-kotlin/pull/1581).

[federation] remove unnecessary extends on Fed 2 Query

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generateClient.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGeneratorConfig.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateClientAction.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/config/GraphQLParserOptions.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateClientParameters.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-client/pom.xml
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt
website/docs/plugins/gradle-plugin-tasks.mdx
website/docs/plugins/maven-plugin-goals.md

Backports #1526 to the v6 branch as this can be a blocker for the plugin usage if an API reaches a certain size.
#1526

(backport to v6) Configure client generate parser options (#1586)

---

examples/client/src/integration/wiremock/__files/schema.graphql
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt

All directive names should be prefixed with `@` as otherwise it leads to composition errors.

[federation] fix fed2 link directive imports and spec URL

---

examples/client/src/integration/wiremock/__files/schema.graphql
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/apollo-federation.mdx

Link imports should include `@` in the directive names, otherwise composition blows up.

[federation] fix fed2 link imports

---

.github/workflows/build-examples.yml
.github/workflows/build-libraries.yml
.github/workflows/continuous-integration.yml
.github/workflows/pr-check.yml
examples/client/maven-client/build.gradle.kts

CI and PR builds are very similar so we use reusable workflows to keep the build logic in single place. By separating regular build and examples build into separate jobs, we can now re-run those individually as needed.
See: https://docs.github.com/en/actions/using-workflows/reusing-workflows

[build] use reusable workflows to simplify actions

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ComposeDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/composeDirective/CustomSchema.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/ComposeDirectiveIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/apollo-federation.mdx
website/docs/schema-generator/federation/federated-directives.md

By default, Supergraph schema excludes all custom directives. Federation 2.1 adds new `@composeDirective` that can be used to instruct composition logic to preserve custom directives in the Supergraph schema.
```graphql
directive @composeDirective(name: String!) repeatable on SCHEMA
```
N/A

[federation] add support for Fed 2.1

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/requestExtensions.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/RequestExtensionsKtTest.kt

graphql-java [ExecutionInput Builder](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/ExecutionInput.java#L222) assings new `graphQLContext` map to the deprecated `context` Object if `context` was not specified, because of that the schema generation will fail when some deprecated resolvers that are still using the [GraphQLContext interface](https://github.com/ExpediaGroup/graphql-kotlin/blob/6.x.x/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/GraphQLContext.kt#L26) making the reflections to fail with `ClassCastException` (expecting an implementation of the interface but getting a GraphQLContext map class impl)

feat: make builder use null graphQLContext if null was provided

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/ExecutionBatchState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/ExecutionStrategyState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/AstronautGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/domain/Nasa.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

the `DataLoaderSyncExecutionExhaustedInstrumentation` is missing one use case that we didn't account for, which is calculating when a Leaf (Scalar, Enum) field is Asynchronous and it was Dispatched
https://github.com/ExpediaGroup/graphql-kotlin/issues/1610

feat: add missing async leafs use case to sync exhaustion

---

examples/server/spring-server/README.md
servers/graphql-kotlin-spring-server/build.gradle.kts
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLBrowserIDERouteConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphiQLRouteConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/PlaygroundRouteConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/resources/graphql-graphiql.html
website/docs/examples.md
website/docs/server/spring-server/spring-beans.md
website/docs/server/spring-server/spring-overview.mdx
website/docs/server/spring-server/spring-properties.md

[Prisma Labs Playground is deprecated](https://github.com/graphql/graphql-playground/issues/1366#issuecomment-1062088978) and we should use the official GraphQL IDE under GraphQL foundation
GraphiQL will now be the default IDE under the `/graphiql` endpoint, while Playground will still be available with explicit opt-in through configuration properties
```yml
graphql:
graphiql:
enabled: true
playground:
enabled: false
```
https://github.com/ExpediaGroup/graphql-kotlin/issues/1589

feat: add and use graphiql as default for browser IDE

---

servers/graphql-kotlin-spring-server/src/main/resources/graphql-graphiql.html

feat: add explorer and exporter plugins

---

gradle.properties
plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars_jackson/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/custom_scalars_kotlinx/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/jacoco/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/polymorphic_types_jackson/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/polymorphic_types_kotlinx/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/skip_include/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGenerateClientIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAndroidIT.kt

also updating 
- `kotlinxSerializationVersion`
- `springBootVersion`
- `springVersion`
spring-boot 2.7.7 uses
https://github.com/reactor/reactor/releases/tag/2020.0.26
so matching `reactor-core` and `reactor-kotlin-extensions` versions

[build] update to kotlin 1.7.21

---

build.gradle.kts
clients/graphql-kotlin-client-jackson/build.gradle.kts
clients/graphql-kotlin-client-serialization/build.gradle.kts
clients/graphql-kotlin-client/build.gradle.kts
clients/graphql-kotlin-ktor-client/build.gradle.kts
clients/graphql-kotlin-spring-client/build.gradle.kts
examples/build.gradle.kts
examples/client/build.gradle.kts
examples/client/gradle-client/build.gradle.kts
examples/client/maven-client/build.gradle.kts
examples/federation/products-subgraph/build.gradle.kts
examples/federation/reviews-subgraph/build.gradle.kts
examples/server/ktor-server/build.gradle.kts
examples/server/ktor-server/gradle.properties
examples/server/spring-server/build.gradle.kts
examples/settings.gradle.kts
executions/graphql-kotlin-automatic-persisted-queries/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader/build.gradle.kts
generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-schema-generator/build.gradle.kts
gradle.properties
gradle/libs.versions.toml
plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/graphql-kotlin-maven-plugin/build.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
servers/graphql-kotlin-server/build.gradle.kts
servers/graphql-kotlin-spring-server/build.gradle.kts

[Version Catalog](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog) is a preferred mechanism for declaring and sharing project dependencies. Once dependencies are defined in the `libs.versions.toml` file, they can be imported using type safe accessors.
Dependent projects (i.e. `examples`, Gradle plugin integration tests and federation compatibility) can also import same version catalog which further simplifies version management.

migrate build to version catalog

---

gradle/libs.versions.toml

[CVE-2022-3171](https://devhub.checkmarx.com/cve-details/CVE-2022-3171/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea&utm_term=maven)
https://github.com/ExpediaGroup/graphql-kotlin/issues/1608

chore: update federation-jvm version to 2.2.0

---

gradle.properties

patching 6.x.x to solve [CVE-2022-3171](https://devhub.checkmarx.com/cve-details/CVE-2022-3171/?utm_source=jetbrains&utm_medium=referral&utm_campaign=idea&utm_term=maven)
https://github.com/ExpediaGroup/graphql-kotlin/pull/1634
https://github.com/ExpediaGroup/graphql-kotlin/issues/1608

chore: update federation jvm to 2.2.0

---

servers/graphql-kotlin-spring-server/build.gradle.kts
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/FederatedSchemaAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/NonFederatedSchemaAutoConfiguration.kt
website/docs/server/spring-server/spring-properties.md

add a configuration property to allow clients to decide if they want to print or not schema after generator creates it.

feat: config property to print schema

---

servers/graphql-kotlin-spring-server/src/main/resources/graphql-graphiql.html

GraphiQL is breaking because the integrity hash is for a specific version but the script tag is attempting to download the newest version, which is no longer 2.2.0. This PR pins graphiQL bundle to 2.2.0 version.

fix: graphiql bundle version

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/dataFetchingEnvironmentExtensions.kt

https://github.com/ExpediaGroup/graphql-kotlin/issues/1649
will update both pre-release and 6.x.x docs in a separate PR against master

feat: pass graphQLContext as fallback if deprecated context is null

---

website/versioned_docs/version-6.x.x/schema-generator/execution/contextual-data.md

Fixed a tiny spelling mistake in the contextual-data documentation.

docs: arguments spelling mistake

---

website/docs/server/data-loader/data-loader.md
website/versioned_docs/version-6.x.x/server/data-loader/data-loader.md

adding an example of how to use DataLoaders and keep using suspendable functions
https://github.com/ExpediaGroup/graphql-kotlin/issues/986

chore: add example how to use data loaders with suspendable functions

---

servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt

Fixes that a plugin is applied globally, which is not really needed in this context
fixes #1683

fix(ktor-server): move plugin install to routing context

---

examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/GraphQLModule.kt
servers/graphql-kotlin-ktor-server/build.gradle.kts
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLConfiguration.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLRoutes.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLContextFactory.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParser.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLServer.kt
servers/graphql-kotlin-ktor-server/src/main/resources/graphql-graphiql.html
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
website/docs/server/ktor-server/ktor-configuration.md
website/docs/server/ktor-server/ktor-http-request-response.md
website/docs/server/ktor-server/ktor-overview.mdx

It appears that it is currently not possible to easily access the previously configured routes. This means that it is not possible to intercept our auto-configured routes to add some additional configuration (e.g. `Authentication`). This PR refactors the plugin to extract all routes into a separate extension functions that can be invoked by the users.
New plugin configuration will consist of 2 steps - (1) configuring server and (2) configuring routes.
```kotlin
fun Application.myGraphQLModule() {
install(GraphQL) {
// all schema, engine and server configuration go here
}
install(Routing) {
// configure routes
graphQLGetRoute()
graphQLPostRoute()
graphQLSDLRoute()
graphiQLRoute()
}
}
```
This refactor follows the same pattern as `Authentication` plugin.
Resolves: …

[ktor plugin] refactor route configuration

---

.github/workflows/build-examples.yml
.github/workflows/pr-check-docs.yml
.github/workflows/publish-latest-docs.yml

v2 is running (deprecated) Node 12 and will stop working in coming weeks.

chore: update actions/cache to v3

---

servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParser.kt
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParserTest.kt

We can rely on `ContentNegotiation` plugin to automatically parse incoming requests for us. We don't have to read incoming requests as plain text and then attempt to manually map it.

[ktor server] simplify KtorGraphQLRequestParser

---

plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt

Instead the gradle plugin would use compileKotlinJvm.
This is a temporary fix, but in the short-term, it would make the gradle plugin compatible with Multiplatform.
Fix of a Gradle error, that when running with Multiplatform, the Gradle plugin cannot find a task named "compileKotlin", which does not exist in a Multiplatform context.
#1139
#876

fix(gradle-plugin): compileKotlin does not exist in Multiplatform

---

.github/workflows/continuous-integration.yml

We are using https://github.com/release-drafter/release-drafter which requires `contents: write` + `pull-requests: read` permissions.
N/A

build: set permissions for release drafter

---

.github/workflows/publish-latest-docs.yml

We are using https://github.com/peaceiris/actions-gh-pages which requires `contents: write` permission.
We could potentially refactor this to use more generic `actions/upload-pages-artifact` + `actions/deploy-pages` that require more scoped permissions but unsure how much value it gets us.
We won't be able to publish new GH pages until this is fixed -> see https://github.com/ExpediaGroup/graphql-kotlin/actions/runs/4427684966/jobs/7765655027#step:6:1258

build: set permissions to deploy GH pages

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/execution/CustomDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateFunction.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateInterface.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateMutation.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateObject.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateQuery.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateSubscription.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateFunctionTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringKotlinDataFetcherFactoryProvider.kt

Update `KotlinDataFetcherFactoryProvider#functionDataFetcherFactory` signature to accept target KClass. This makes both factory signatures consistent.
This change will also enable auto-capturing GraalVM reflect metadata for all the resolvers.

BREAKING CHANGE(generator): update functionDataFetcherFactory to accept KClass

---

servers/graphql-kotlin-server/src/main/resources/graphql-graphiql.html

use jsdelivr in favor of unpkg which is being unstable lately because of cloudfare

feat: update graphiql packages cdn

---

buildSrc/src/main/kotlin/com.expediagroup.graphql.conventions.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts

* remove unnecessary publish to maven local on each jar build (it was required BEFORE we move moved all plugin integration tests to separate composite projects)
* use JVM test suite instead of a custom `Test` task

chore(build): gradle script cleanups

---

gradle/libs.versions.toml
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePlugin.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLPluginExtension.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateGraalVmMetadataAction.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/parameters/GenerateGraalVmMetadataParameters.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGraalVmMetadataTask.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTaskIT.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/graalvm/custom/GenerateGraalVmCustomScalarMetadataTest.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/graalvm/federated/GenerateGraalVmEntityMetadataTest.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/main/kotlin/com/expediagroup/graphql/plugin/graalvm/DefaultMetadataLoader.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/main/kotlin/com/expediagroup/graphql/plugin/graalvm/GenerateGraalVmMetadata.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/main/kotlin/com/expediagroup/graphql/plugin/graalvm/GenerateNativeImageConfiguration.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/main/kotlin/com/expediagroup/graphql/plugin/graalvm/ReflectMetadata.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/main/resources/default-reflect-config.json
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/test/kotlin/com/expediagroup/graphql/plugin/graalvm/integration/GenerateGraalVmMetadataTest.kt
plugins/server/graphql-kotlin-graalvm-metadata-generator/src/test/kotlin/com/expediagroup/graphql/plugin/graalvm/integration/HelloWorldQuery.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQL.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLConfiguration.kt

Create new Gradle task that automatically generates GraalVm reachability metadata for GraphQL Kotlin servers.
Following metadata files are generated:
* `native-image.properties`
* `reflect-config.json`
* `resource-config.json`
Usage:
```
plugins {
kotlin("jvm") version "1.7.21"
application
id("org.graalvm.buildtools.native") version "0.9.20"
id("com.expediagroup.graphql") version $graphQLKotlinVersion
}
// other build configuration goes here
graphql {
graalVm {
packages = listOf("com.example")
}
}
```

feat(plugin): new GraalVm metadata Gradle task

---

servers/graphql-kotlin-server/src/main/resources/graphql-graphiql.html

Resolve absolute url for graphiql subscriptions using window.location.href.
#1754

fix(server): Absolute urls for graphiql subscriptions

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/EntitiesDataFetcher.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/resolverexecutor/FederatedTypePromiseResolverExecutor.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/extensions/CompletableFutureExtensions.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/resolverexecutor/FederatedTypePromiseResolverExecutorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/extensions/CompletableFutureExtensionsKtTest.kt

the `FederatedTypePromiseResolver` was originally created with the `DataLoader` use case in mind, meaning that all returned `CompletableFuture`s are resolved synchronously, to let `DataLoader` dispatch mechanism to decide when to dispatch, so realistically, when using `DataLoader`s, there is not an scenario where a particular `CompletableFuture` might complete exceptionally.
However, nothing stops users to use the `FederatedTypePromiseResolver` without dataloaders, which means that now `CompletableFuture`s might complete exceptionally in a asynchronous way.
To solve that, create allSettled extension function 
```kotlin
fun List<CompletableFuture<out T>>.allSettled(): CompletableFuture<List<Result<T>>>
```
which will complete all promises even if one or more complete exceptionally. The …

feat: FederatedTypePromiseResolver to settle all promises regardless of errors

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateTypeName.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/alias_nested/AliasNestedQuery.graphql
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/alias_nested/AliasNestedQuery.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/alias_nested/aliasnestedquery/ComplexObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/alias_nested/aliasnestedquery/ComplexObject2.kt

See #1760 for a description of the problem this PR tries to fix.
I first created the new test case and then worked through the code to figure out where `ComplexObject` was wrongly deduplicated. `verifySelectionSet` in `generateTypeName.kt` came to the conclusion, that 
```gql
first: complexObjectQuery {
nameA: name
}
```
and
```gql
second: complexObjectQuery {
nameB: name
}
```
contain the same fields although they do not. Using `selection.alias` (if it exists) instead of `selection.name` in `calculateSelectedFields`  fixed the issue.
fixes #1760

fix: Improve alias handling in client generation

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

`dispatchIfNeeded` extension function was wrongly accessing to the `KotlinDataLoaderRegistry`, which is easily accesible from `DataFetchingEnvironment`
will cherry pick the fix to 6.x.x afterwards
https://github.com/ExpediaGroup/graphql-kotlin/issues/1765

fix: grab kotlinDataLoaderRegistry from environment

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

cherry picking https://github.com/ExpediaGroup/graphql-kotlin/pull/1767
https://github.com/ExpediaGroup/graphql-kotlin/issues/1765

fix: grab kotlinDataLoaderRegistry from environment (#1767)

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/ValidateFieldSelection.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateFieldSetSelection.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/requires/success/_5/LeafRequires.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/requires/success/_6/RecursiveExternalRequires.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/requires/success/_7/ExternalRequiresType.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/FederatedRequiresDirectiveIT.kt
website/docs/schema-generator/federation/federated-directives.md

Relaxing `@requires` and `@external` constraints. Previously ALL fields referenced from the `@requires` selection set had to be marked `@external`. This was too strict as it is possible to define `@requires` selection set against **local** object type with some `@external` fields. As a result only leaf fields (i.e. scalar/enum fields) have to be explicitly marked `@external` OR implicitly inherit `@external` characteristic through any of the leaf field ancestors.

fix(federation): relaxes `@requires` and `@external` constraints

---

examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/query/PolymorphicQueryIT.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt
gradle.properties

This is an special PR that will update [graphql-java version to 20.3](https://github.com/graphql-java/graphql-java/releases/tag/v20.3) which is an special release of graphql java with a change that reverts the stricter `parseValue` scalar coercion, since this was the only breaking change in v20, im updating `6.x.x`.
Have special interest in checking the performance improvements graphql-java 20 provides, like the `LightDataFetcher` interface and Performance Improvements by avoid object allocations.
more info
https://github.com/graphql-java/graphql-java/releases/tag/v20.0

feat: update graphql-java version with backwards compatible changes

---

servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/subscriptions/graphqlws/KtorGraphQLWebSocketProtocolHandlerTest.kt

Add artificial delay to Ktor subscription test to ensure coroutines can complete successfully within the timeout.

chore: fix flaky subscription test

---

servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/subscriptions/graphqlws/KtorGraphQLWebSocketProtocolHandlerTest.kt

Reverts ExpediaGroup/graphql-kotlin#1787
While actions running the PR checks worked it still fails on master :(

Revert "chore: fix flaky subscription test"

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionBatchState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ManualDataFetcher.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ManuallyCompletableLightDataFetcher.kt

Now that [PropertyDataFetcher](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt#L31) implements `LightDataFetcher` we need to make sure we respect that and on the `LEVEL_DISPATCHED` batching mechanism, decorate the DataFetcher properly depending if its `LightDataFetcher`, or just `DataFetcher`

feat: honor LightDataFetcher on by level batching logic

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionBatchState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ManualDataFetcher.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ManuallyCompletableLightDataFetcher.kt

Now that [PropertyDataFetcher](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt#L31) implements `LightDataFetcher` we need to make sure we respect that and on the `LEVEL_DISPATCHED` batching mechanism, decorate the DataFetcher properly depending if its `LightDataFetcher`, or just `DataFetcher`

feat: honor LightDataFetcher on by level batching logic (#1795)

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt

let the user decide if they want to call the supplier, and avoid having the library to make that choice

feat: avoid calling the DFE supplier in batching instrumentations

---

executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/ExecutionContextExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionBatchState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/Level.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt

Batching by LEVEL requires to calculate the height of all graphql documents in a batch request to be calculated before deciding of a certain level was dispatched, the reason is because a batch request could contain multiple and potentially different operations, with different levels, so, to decide if a level was dispatched, we need to know which operations in the batch request share the same level.
This PR will remove that logic, which was take it from the graphql-java [MaxDepthInstrumentation](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/analysis/MaxQueryDepthInstrumentation.java#L56).
Instead we will calculate the height on runtime, simplifying the dispatch by level instrumentation and removing some CPU usage by not doing an AST traversal to calculate …

feat(batching): avoid calculating document ast height in advance

---

executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/ExecutionContextExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionBatchState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/Level.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt

feat(batching): avoid calculating document ast height in advance (#1800)

---

servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/GraphQLRoutes.kt
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt

This is a small fix to set `graphql-transport-ws` subprotocol as (sensible) default for Ktor server `graphQLSubscriptionsRoute`. 
Without that line, users may encounter issues when sending requests using popular GQL clients like Apollo or even bundled GraphiQL UI, because of they are sending `Sec-Websocket-Protocol=graphql-transport-ws` header and that is being rejected by Ktor.
Users may still override this value, if needed
#1756

Ktor Server:  set "graphql-transport-ws" as default protocol to graphQLSubscriptionsRoute

---

examples/federation/supergraph.yaml

Pin composition to a specific version. Latest `rover` changes require either specific version or to wrap major in quotes.

fix federation composition integration

---

website/versioned_docs/version-6.x.x/server/data-loader/data-loader.md

`persistant`, an original word of data-loader page, seems typo of `persistent`.
written above
N/A

Update `data-loader` page to fix typo

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateDirective.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooksTest.kt

Adds new `didGenerateDirective` hook that is invoked AFTER generating the directive. This PR also fix directive generation logic to ensure hooks are only called once (when generating the directive). Previously we were always invoking `willGenerateDirective` hook regardless whether the directive was already generated or not (which lead to creation of new directive when modifying the directive in the new `didGenerateDirective` hook).
Type generation still suffers from the same bug (#1815)

feat(generator): introduce new didGenerateDirective hook

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooksTest.kt

Cleanup schema generation hooks to have proper BEFORE and AFTER generation hooks.
Changes:
* Rename existing `willBuildSchema` hook to `didBuildSchema` hook to indicate that it executes AFTER generating the schema.
* Add new `willBuildSchema` hook that executes BEFORE any schema generation logic kicks in

BREAKING(generator): use new willBuildSchema/didBuildSchema

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLRoutesConfiguration.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt

Most clients will request with `*/*` unless an any MediaType is specified.
However, the `*/*` was not taken into account in current implementation.
I change to keep `application/json` as default instead of `application/graphql-response+json`.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1831
https://github.com/ExpediaGroup/graphql-kotlin/issues/1573
https://github.com/ExpediaGroup/graphql-kotlin/pull/1699

Keep response content type to application/json as default instead of application/graphql-response+json

---

executions/graphql-kotlin-dataloader/src/main/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistry.kt

apply a synchronized lock over data loaders, the reactive stack could cause multiple threads trying to access to the same memory.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1837
https://github.com/ExpediaGroup/graphql-kotlin/issues/1819

feat: apply a thread safe lock over dataloaders

---

executions/graphql-kotlin-dataloader/src/main/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistry.kt

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/1838

feat: apply a thread safe lock over dataloaders (#1838)

---

.github/workflows/federation-integration.yml
examples/federation/supergraph.yaml
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/AuthenticatedDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/ComposeDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/RequiresScopesDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/Scope.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/types/Scope.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/compose/ComposeDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/link/LinkDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/requiresscope/RequiresScopesDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/types/ScopesTest.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooks.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateDirective.kt
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/apollo-federation.mdx
website/docs/schema-generator/federation/federated-directives.md

Adds support for [Apollo Federation v2.5](https://www.apollographql.com/docs/federation/federation-versions#v25).
Adds new `willApplyDirective`/`didApplyDirective` hooks that can be used to customize transformation of directive definition to applied directive. JVM does not support nested arrays as annotation arguments so we need to apply custom hooks to generate valid `@requiresScopes` directive. New hooks can also be used to filter out default arguments (#1830).
New federation directives
- `@authenticated` - indicates that target element is only accessible to the authenticated supergraph users
- `@requiresScopes` - indicates that target element is only accessible to the authenticated supergraph users with the appropriate JWT scopes
Note: due to the potential conflict on directive names …

feat: support Apollo Federation 2.5

---

executions/graphql-kotlin-dataloader/src/main/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistry.kt

improve thread safe issue for getCurrentFutures
current implementation get the values form cachemap for dataloaders.
And make it flatten. But when we get the values it's just iterator, not all the elements is obtained.
So when we run flatten, it traverse the each iterator, and it make ```ArrayIndexOutOfBoundException```
Following is error message
```
aused by: java.lang.ArrayIndexOutOfBoundsException: Index 279 out of bounds for length 279
at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
at java.base/java.util.ArrayList.addAll(ArrayList.java:670)
at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:116)
at kotlin.collections.CollectionsKt__IterablesKt.flatten(Iterables.kt:49) …
```

feat : handle thread safe issue for getCurrentFutures

---

servers/graphql-kotlin-server/src/main/resources/graphql-graphiql.html

removing plugins as they are incompatible with v3 -- non official plugins.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1854

chore: update graphiql 3.0.6

---

website/docs/server/server-subscriptions.md

Replaced Spring subscriptions URL with Ktor subscriptions.
#1863

fix: Ktor Subscriptions wrong url #1863

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/extensions/CompletableFutureExtensions.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/extensions/CompletableFutureExtensionsKtTest.kt

We noticed a big drop in performance after switching to the new `CompletableFuture` based `FederatedTypeResolver`. Our investigations led us to the implementation of `CompletableFutureExtension.allSettled` which has the following issues:
- Bug: It uses `CompletableFuture.supplyAsync` which looses all thread local data (as we switch to another thread pool we have no control over), which breaks most tracing frameworks and all other thread local usages
- Performance: 100 futures get wrapped into 100 separately scheduled futures, this is unnecessary as `thenApply` and `exceptionally` work without nesting of futures. This avoids non-neglegible overhead
I changed the accompanying test to expect another exception type as only `get()` throw a `ExecutionException`. This should not affect your …

Rewrite CompletableFutureExtension.allSettled to not use CompletableFuture.supplyAsync

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt

As of v2.4, Federation supports subscriptions. Our servers automatically configure hooks for subscription `Flow` support for non-federated schemas. We should update federated hooks to also support `Flow`.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1862

fix(federation): update federated hooks to support flow

---

generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateFieldSetSelection.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/data/integration/key/success/_6/EntityReferencingParent.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/integration/FederatedKeyDirectiveIT.kt

We are performing federated directive validations when generating GraphQL schema. This is an extra convenience as it gives us information about invalid schema sooner. Subgraph schemas will then be re-validated during the supergraph composition logic.
Currently it is possible to create `@key` that references the type still under construction (`GraphQLReferenceType`). Since we cannot validate fields on the type that doesn't exist yet, we cannot validate it either. Updating logic to log a warning when this happens and skip validation logic.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1858

fix(federation): skip fieldset validation when it includes type reference

---

generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/FederatedSchemaValidator.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/validation/validateFieldSetSelection.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/validation/FederatedSchemaValidatorTest.kt

We were previously validating usage of `@key`/`@requires`/`@provides` directives when constructing the schema. While it generally worked fine, it is possible to craft a schema when generated types still reference types under construction (see: https://github.com/ExpediaGroup/graphql-kotlin/issues/1858) and we would have to skip those validations. By moving the validation to the last phase of schema generation, we always have a valid GraphQL schema at that point with resolved references and we can apply validations against all entities at once so we can have single error message with all validations (vs failing the build for each invalid entity).
https://github.com/ExpediaGroup/graphql-kotlin/issues/1858

fix: move federation validations to didBuildSchema hook

---

website/docs/plugins/gradle-plugin-usage-graalvm.mdx
website/docs/plugins/maven-plugin-usage-graalvm.md

There is a small error in the Maven/Gradle native image documentation. The attribute `typeHierarchy` is part of the `schema` block but was previously in the `install(GraphQL)` scope
no issue

[Documentation] Fixed error in GraalVM native image docs

---

website/docs/schema-generator/execution/exceptions.md

Fixed broken link (404 Not Found) to GraphQL Java documentation
No issue

Fixed link to GraphQL documentation

---

clients/graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/extensions/AutomaticPersistedQueriesExtensions.kt
clients/graphql-kotlin-ktor-client/src/main/kotlin/com/expediagroup/graphql/client/ktor/GraphQLKtorClient.kt
clients/graphql-kotlin-spring-client/src/main/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClient.kt
executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/extensions/executionInputExtensions.kt

`MessageDiggest` is NOT thread safe, if multiple queries are being executed concurrently it might cause a race condition and send back a `PersistedQueryIdInvalid` error
https://opensource.expediagroup.com/graphql-kotlin/docs/server/automatic-persisted-queries/#errors
instead we will create a `MessageDigest` instance each time.

fix: create MessageDigest when needed

---

executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/cache/AutomaticPersistedQueriesCache.kt
executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/cache/DefaultAutomaticPersistedQueriesCache.kt
executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/provider/AutomaticPersistedQueriesProvider.kt

trying to implement a distributed cache mechanism for parsed and validated operations, in the `getOrElse` method is where we would be setting the operation into an external cache, for that, we need access to the actual operation, which is included in the `ExecutionInput`.
No more changes are needed given that the action of storing the parsed and validated operation is potentially async, but we don't care about the result.

feat: pass ExecutionInput to getOrElse method

---

executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/cache/AutomaticPersistedQueriesCache.kt
executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/cache/DefaultAutomaticPersistedQueriesCache.kt
executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/provider/AutomaticPersistedQueriesProvider.kt

trying to implement a distributed cache mechanism for parsed and validated operations, in the `getOrElse` method is where we would be setting the operation into an external cache, for that, we need access to the actual operation, which is included in the `ExecutionInput`.
No more changes are needed given that the action of storing the parsed and validated operation is potentially async, but we don't care about the result.

feat: pass ExecutionInput to getOrElse method (#1918)

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionWebSocketHandler.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionWebSocketHandlerTest.kt

When using Spring Server client tries to initiate subscription, but timeout occurs before sending `connection_init` message Kotlin coroutine fails with exception:
```
2024-01-22T11:14:05.757+02:00  INFO 20308 --- [           main] c.p.ApplicationKt   : Started ApplicationKt in 2.86 seconds (process running for 3.29)
Exception in thread "DefaultDispatcher-worker-2" java.util.NoSuchElementException: No value received via onNext for awaitFirst
at kotlinx.coroutines.reactive.AwaitKt$awaitOne$2$1.onComplete(Await.kt:282)
at reactor.core.publisher.StrictSubscriber.onComplete(StrictSubscriber.java:123)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
at reactor.netty.FutureMono$FutureSubscription.operationComplete(FutureMono.java:196)
at …
```

Handle subscription init timeout gracefully

---

gradle/libs.versions.toml

Ktor prior to 2.3.5 has a vulnerability: [CVE-2023-45613](https://ossindex.sonatype.org/vulnerability/CVE-2023-45613?component-type=maven&component-name=io.ktor%2Fktor-network-tls-jvm)

Update Ktor to 2.3.7

---

integration/maven-plugin-integration-tests/integration/generate-client/pom.xml
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/actions/GenerateClientAction.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/config/GraphQLParserOptions.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt
website/docs/plugins/gradle-plugin-tasks.mdx
website/docs/plugins/maven-plugin-goals.md

Enables configuration of the maxCharacters and maxParserDepth parser options for GraphQL Java. 
See [ParserOptions](https://github.com/graphql-java/graphql-java/blob/7c381cc9d61c1e1838a2487d9b24974c451f23a2/src/main/java/graphql/parser/ParserOptions.java#L13) for the values configured in graphql-java.
Extensions of #1586 with additional parameters that have been added to graphql-java.

feat: allow additional parser options in the gradle and maven plugins

---

plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/config/GraphQLParserOptions.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt

Previous val declaration for the additional parser options cannot be reassigned - they should be a var and not val.
#1925
#1586

fix: allow maven and gradle plugins to have new parser options values configurable

---

examples/federation/docker-compose.yaml
examples/federation/supergraph.yaml
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/Policy.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/PolicyDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/types/Policy.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/compose/ComposeDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/link/LinkDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/policy/PolicyDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/requiresscope/RequiresScopesDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/apollo-federation.mdx
website/docs/schema-generator/federation/federated-directives.md

Adds Federation v2.6 support
```graphql
directive @policy(policies: [[federation__Policy!]!]!) on
| FIELD_DEFINITION
| OBJECT
| INTERFACE
| SCALAR
| ENUM
scalar federation__Policy
```
`@policy` directive indicates to composition that the target element is restricted based on authorization policies that are evaluated in a Rhai script or coprocessor. Refer to the [Apollo Router article](https://www.apollographql.com/docs/router/configuration/authorization#policy) for additional details.
N/A

feat(federation): federation v2.6 support

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServer.kt

as soon as request was deserialized, move execution of operation out of the thread that routed the request (reactor netty http epoll thread in case of spring).

feat(servers): move execution out of reactor netty threads

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/execution/AbstractExecutionLevelDispatchedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/AbstractSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServer.kt

Remove operations that failed pre-executions from batching state, an operation can become invalid if parsing, validation or any other logic from preparsed document provider failed (such as persisted queries).

feat(batching): Exclude operations that failed pre-executions

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServer.kt

as soon as request was deserialized, move execution of operation out of the thread that routed the request (reactor netty http epoll thread in case of spring).

feat: execute graphQLRequest out of reactor netty threads ( cherry pick #1943)

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/execution/AbstractExecutionLevelDispatchedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/AbstractSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

Remove operations that failed pre-executions from batching state, an operation can become invalid if parsing, validation or any other logic from preparsed document provider failed (such as persisted queries).

feat(batching): Exclude operations that failed pre-executions (#1942)

---

website/docs/schema-generator/execution/data-fetching-environment.md

Fixed links and added info for `selectionSet`. It took me a while to find how to retrieve sub field information, so I figures it might help the next guy.

Fix links in documentation and add some additional info for DataFetchingEnvironment selectionSet

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/types/serializers/AnyNullableKSerializer.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/types/GraphQLServerRequestTest.kt

after graphql-kotlin 7.1.0, the following `GraphQLRequest` our team uses started to fail.
```kotlin
GraphQLRequest(
"query(${'$'}id: ID!) { ... }",
variables = mapOf("id" to ID("1"))
)
```
this is because `kotlinx.serialization` is recently introduced instead of Jackson, but `ID` serialization is missing, so it is converted to `JsonNull`.
since `ID` is built-in scalar type, i think `ID` serialization should be supported.
add serialization logic to `AnyNullableKSerializer` 
N/A

Support built-in `ID` type serialization in `GraphQLServerRequest`

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
website/docs/schema-generator/customizing-schemas/renaming-fields.md

Currently input types are always suffixed with `Input` which is problematic as there are use cases where users might want to provide different custom name. This change adds check whether specified type is input only and if thats the case it does not attempt to add `Input` suffix.
Supersedes https://github.com/ExpediaGroup/graphql-kotlin/pull/1949

feat: ability to specify `@GraphQLName` on input types w/o suffix

---

examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/BookQueryService.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/CourseQueryService.kt
examples/server/ktor-server/src/main/kotlin/com/expediagroup/graphql/examples/server/ktor/schema/UniversityQueryService.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/DataLoaderQuery.kt
executions/graphql-kotlin-automatic-persisted-queries/src/test/kotlin/com/expediagroup/graphql/apq/fixture/ProductGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/AstronautGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/ProductGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/AstronautService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/MissionService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/PlanetService.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/datafetcher/ProductService.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/execution/EntitiesDataFetcher.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/EntitiesDataFetcherTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/DirectiveTests.kt
gradle/libs.versions.toml
integration/graalvm/common-graalvm-server/src/main/kotlin/com/expediagroup/graalvm/schema/AsyncQuery.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/GraphQLRequestHandlerTest.kt

Follow up to https://github.com/ExpediaGroup/graphql-kotlin/pull/1967 to use an official graphql java release.

feat: Use official graphql java 22 version

---

buildSrc/settings.gradle.kts
buildSrc/src/main/kotlin/com.expediagroup.graphql.conventions.gradle.kts
clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClientTest.kt
examples/buildSrc/src/main/kotlin/com.expediagroup.graphql.examples.conventions.gradle.kts
executions/graphql-kotlin-automatic-persisted-queries/build.gradle.kts
generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-schema-generator/build.gradle.kts
gradle/libs.versions.toml
integration/graalvm/spring-graalvm-server/build.gradle.kts
integration/gradle-plugin-android-test/app/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/custom-scalars-jackson/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/custom-scalars-kotlinx/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/jacoco/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/ktor-jackson/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/ktor-kotlinx/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/polymorphic-types-jackson/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/polymorphic-types-kotlinx/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/skip-include/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/webclient-jackson/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/webclient-kotlinx/build.gradle.kts
integration/maven-plugin-integration-tests/integration/basic-setup/pom.xml
plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
plugins/server/graphql-kotlin-graalvm-metadata-generator/build.gradle.kts
servers/graphql-kotlin-ktor-server/build.gradle.kts
website/package-lock.json
website/package.json

* Fix Gradle deprecations and warnings
* Make coverage rules more lenient
* Fix website vulnerabilities
| Library | Vulnerability | Severity |
|-|-|-|
| braces | CVE-2024-4068 | HIGH |
| express | CVE-2024-29041 | MEDIUM |
| follow-redirects | CVE-2024-28849 | |
| webpack-dev-middleware | CVE-2024-29180 | HIGH |
| ws | CVE-2024-37890 | |
* Improve dependency management
* Please test all updates and changes extensively to prepare for Kotlin 2 compatibility
* Please try to restore the 3 skipped tests after Kotlin 1.9 upgrade
* Anchor `#dispatching-by-level` doesn't exist anymore in website/docs/server/data-loader/data-loader-instrumentation.mdx
* Old code should be reformatted so all those many exceptions can be removed from `.editorconfig

fix: Vulnerabilities and warnings

---

generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/exception/FederatedRequestFailure.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/exception/InvalidFederatedRequest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/exception/FederatedRequestFailureTest.kt

Per GraphQL spec error location should only be specified IF it can point to a valid location (i.e. starting with positive column/row). We were incorrectly returning `-1,-1` location.

fix(federation): Federation errors should not return invalid locations

---

.github/workflows/build-examples.yml
.github/workflows/build-libraries.yml
.github/workflows/federation-integration.yml
.github/workflows/graalvm-integration.yml
.github/workflows/http-spec-compliance.yml
.github/workflows/plugin-it.yml
.github/workflows/release-code.yml

Old actions were deprecated.
Supersedes https://github.com/ExpediaGroup/graphql-kotlin/pull/1982
Supersedes https://github.com/ExpediaGroup/graphql-kotlin/pull/1981

chore: update to use new Gradle actions

---

plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateClientTask.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateTestClientTask.kt

- We can leverage caching in Gradle for `GraphQLGenerateClientTask` and `GraphQLGenerateTestClientTask` by annotating them with `@CacheableTask` 
- Also annotate `schemaFile`, `queryFileDirectory`, `queryFiles` with `@PathSensitive(PathSensitivity.RELATIVE)` for the purposes of normalization so that outputs can be reused for caching
- Gradle docs: https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/CacheableTask.html

Make GraphQLGenerateClientTask and GraphQLGenerateTestClientTask cacheable

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt

Example: a persisted query is found, but operationName in the http request is not in the persisted document, causing an unknown operation exception (UnknownOperationException).
Exceptions are converted into graphQL errors at later point, initially thought those errors from exceptions would be in the execution result.

feat(batching): remove execution if a given operation completes with an exception

---

executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/AbstractSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/SyncExecutionExhaustedInstrumentationParameters.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/AstronautGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

Cover the scenario where the sync execution is exhausted after an execution exception, as the execution that thrown the exception could be the last one to execute synchronous code.

feat(batching): check if execution was exhausted when there are errors

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/AbstractSyncExecutionExhaustedInstrumentation.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/execution/SyncExecutionExhaustedInstrumentationParameters.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/fixture/AstronautGraphQL.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/DataLoaderLevelDispatchedInstrumentationTest.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

https://github.com/ExpediaGroup/graphql-kotlin/pull/2009

feat(batching): v6 check if execution was exhausted when there are errors

---

executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

when attempting to remove an execution from the concurrent map (executions) we need to make sure that the executions map is locked, that way we will guarantee the atomic calculation of of synchronous execution exhausted state

feat: synchronize executions when attempting to remove an entry

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2013

feat(batching): v6 synchronize executions when attempting to remove an entry

---

bom/README.md
bom/build.gradle.kts
settings.gradle.kts
website/docs/getting-started.mdx

Adding a support on `graphql-kotlin-bom`
Generated BOM looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>com.expediagroup</groupId>
<artifactId>graphql-kotlin-bom</artifactId>
<version>8.0.0-SNAPSHOT</version>
<packaging>pom</packaging>
<name>graphql-kotlin-bom</name>
<description>BOM (Bill Of Materials) for graphql-kotlin</description>
<dependencies>
<dependency>
<groupId>com.expediagroup</groupId>
<artifactId>graphql-kotlin-automatic-persisted-queries</artifactId>
<version>8.0.0-SNAPSHOT</version>
<scope>compile</scope> …
```

feat: Support graphql-kotlin-bom

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServer.kt

Reverts ExpediaGroup/graphql-kotlin#1943
this context switching is causing CPU usage increase.

Revert "feat(servers): move execution out of reactor netty threads"

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
website/docs/schema-generator/customizing-schemas/renaming-fields.md

Reverts ExpediaGroup/graphql-kotlin#1960

Revert "feat: ability to specify `@GraphQLName` on input types w/o suffix"

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
website/docs/schema-generator/customizing-schemas/renaming-fields.md

Reverts ExpediaGroup/graphql-kotlin#1963
https://github.com/ExpediaGroup/graphql-kotlin/issues/2031

Revert "feat: ability to specify `@GraphQLName` on input types w/o suffix (#1…"

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
website/docs/schema-generator/customizing-schemas/renaming-fields.md

Reverts ExpediaGroup/graphql-kotlin#1962
https://github.com/ExpediaGroup/graphql-kotlin/issues/2031

Revert "feat: ability to specify `@GraphQLName` on input types w/o suffix (#1960)"

---

plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/GraphQLClientGenerator.kt
plugins/client/graphql-kotlin-client-generator/src/main/kotlin/com/expediagroup/graphql/plugin/client/generator/types/generateInterfaceTypeSpec.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_same_selections/UnionSameSelections.graphql
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_same_selections/UnionSameSelections.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_same_selections/unionsameselections/EGDSProductRatingShowTextAction.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_same_selections/unionsameselections/EGDSStandardLink.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_same_selections/unionsameselections/ProductRatingSupportingMessage.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_same_selections/unionsameselections/ProductSupportingMessage.kt
plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql

https://github.com/ExpediaGroup/graphql-kotlin/issues/2050

feat: fix duplicated classes in packages and duplicated properties in constructors from interfaces (#2051)

---

website/docs/getting-started.mdx

Hi, I noticed that the Apollo Federation link is broken on the Getting Started page. This PR is to update the link.

docs: Update Apollo Federation link

---

examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/query/APQQueryIT.kt
servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParser.kt
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParserTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLRequestParser.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/execution/SpringGraphQLRequestParserTest.kt

According to the GraphQL APQ flow description, GET requests containing only SHA-256 hash of the query should be checked in cache and respond with PERSISTED_QUERY_NOT_FOUND error if request is not cached.
Both Ktor and Spring server implementations didn't handle this first query without a query param.
I tried to implement the change without breaking existing behaviours, as a query param is expected to take precedence over post body, for example, as in one of the tests in RouteConfigurationIT.
https://github.com/ExpediaGroup/graphql-kotlin/issues/2065

feat: implemented persisted queries for GET methods with only SHA-256 hash of query string

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateArgument.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/directives/DirectiveTests.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateArgumentTest.kt
website/versioned_docs/version-8.x.x/schema-generator/customizing-schemas/deprecating-schema.md

This PR enables support for using the `@GraphQLDeprecated` annotation on arguments, allowing the generated GraphQL schema to include the `@deprecated` directive.  
- Updated `generateArgument.kt ` to mark argument as deprecated if the DeprecationReason is present.
- Added tests to validate the correct behavior when marking arguments as deprecated.  
The GraphQL spec now officially supports applying `@deprecated` on arguments, enabling better API evolution without breaking existing clients. This change aligns the library with the latest spec, giving developers a built-in way to signal argument deprecations.  
- [GraphQL Spec - Deprecated Arguments](https://spec.graphql.org/October2021/#sec--deprecated) ](https://spec.graphql.org/draft/#sec--deprecated) …

Add support for generated @deprecated arguments from @GraphQLDeprecated

---

gradle/libs.versions.toml
servers/graphql-kotlin-server/src/benchmarks/kotlin/GraphQLServerRequestBatchDeserializationBenchmark.kt
servers/graphql-kotlin-server/src/benchmarks/kotlin/GraphQLServerRequestDeserializationBenchmark.kt
servers/graphql-kotlin-server/src/benchmarks/kotlin/GraphQLServerResponseBatchSerializationBenchmark.kt
servers/graphql-kotlin-server/src/benchmarks/kotlin/GraphQLServerResponseSerializationBenchmark.kt
servers/graphql-kotlin-server/src/benchmarks/resources/StarWarsDetailsResponse.json
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/types/GraphQLServerResponse.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/types/GraphQLServerRequestTest.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/types/GraphQLServerResponseTest.kt

benchmarks 
GraphQLRequest deserialization jackson vs fastjson2
GraphQLResponse serialization Jackson vs fastjson2

feat: update fastjson2

---

website/docs/schema-generator/writing-schemas/enums.md

Was using the docs and this caught me out, you have to set the enum name when building a new GraphQLEnumValueDefinition otherwise you will receive `Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]* - was 'null'`

docs: include name when creating GraphQLEnumValueDefinition

---

generator/graphql-kotlin-schema-generator/build.gradle.kts
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/testSchemaConfig.kt
servers/graphql-kotlin-spring-server/build.gradle.kts
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLExecutionConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringKotlinDataFetcherFactoryProvider.kt
website/docs/schema-generator/execution/fetching-data.md

Inspired by https://github.com/graphql-java/graphql-java/pull/3754.
Currently, graphql-kotlin, through the [KotlinDataFetcherFactoryProvider](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt#L62) creates a [PropertyDataFetcher](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/PropertyDataFetcher.kt) per source's property.
This instance is created [every single time ](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/GraphQLCodeRegistry.java#L100)the graphql-java …

feat: SingletonPropertyDataFetcher, avoid allocating a PropertyDataFetcher per property per graphql operation

---

generator/graphql-kotlin-schema-generator/build.gradle.kts
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/testSchemaConfig.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLExecutionConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/execution/SpringKotlinDataFetcherFactoryProvider.kt

cherry-pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2079

feat(7.x.x):  SingletonPropertyDataFetcher, avoid allocating a PropertyDataFetcher per property per graphql operation

---

gradle/libs.versions.toml
integration/graalvm/maven-graalvm-server/build.gradle.kts
integration/maven-plugin-integration-tests/build.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
plugins/server/graphql-kotlin-graalvm-metadata-generator/build.gradle.kts

Fix integration test
Keep running issues with this error for `:graphql-kotlin-sdl-generator:integrationTest` and `:graphql-kotlin-graalvm-metadata-generator:integrationTest`

fix: fix integration test with missing junit-platform-launcher

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt

Adding a missing use case when the registered resolver during schema generation is from a Parent class, while on runtime the resolve object could be an instance of a Child class, as a result, the resolver won't be available in the getters cache.
This PR will attempt to resolve the getter using reflection and it will store it in the getters cache, if not getter found after checking the cache and checking the object class with reflection then a message log will be printed

fix: register getter on runtime when field is of a parent type

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/ToSchemaTest.kt

Adding a missing use case when the registered resolver during schema generation is from a Parent class, while on runtime the resolve object could be an instance of a Child class, as a result, the resolver won't be available in the getters cache.
This PR will attempt to resolve the getter using reflection and it will store it in the getters cache, if not getter found after checking the cache and checking the object class with reflection then a message log will be printed
cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2091

fix: register getter on runtime when field is of a parent type (#2091)

---

examples/client/server/src/main/kotlin/com/expediagroup/graphql/examples/client/server/FederatedQuery.kt
examples/federation/README.md
examples/federation/docker-compose.yaml
examples/federation/reviews-subgraph/src/main/kotlin/com/expediagroup/graphql/examples/federation/reviews/ReviewsQuery.kt
examples/federation/supergraph.yaml
generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederationVersionUtils.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/OverrideDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/authenticated/AuthenticatedTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/compose/ComposeDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/contact/ContactDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/interfaceObject/InterfaceObjectTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/link/LinkDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/override/OverrideDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/policy/PolicyDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/requiresscope/RequiresScopesDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/apollo-federation.mdx
website/versioned_docs/version-7.x.x/schema-generator/federation/apollo-federation.mdx
website/versioned_docs/version-8.x.x/schema-generator/federation/apollo-federation.mdx
website/versioned_docs/version-8.x.x/schema-generator/federation/federated-directives.md

Support federation v2.7. Here's [directive details](https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/reference/directives)
Support [progressive @override directive](https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/reference/directives#progressive-override). 
These directives will require specific federation versions to generate schema. 
1. `@authenticate` directive is generated from `2.5+` 
2. `@requiresScopes` directive is generated from `2.5+` 
3. `@policy` directive is generated from `2.6+` 
4. `@composeDirective` directive is generated from `2.1+` 
5. `@interfaceObject ` directive is generated from `2.6+` 
6. `@override` directive with 2nd argument of `label` from `2.7`

feat: add label as optional arg to @override directive

---

examples/federation/README.md
examples/federation/docker-compose.yaml
examples/federation/reviews-subgraph/src/main/kotlin/com/expediagroup/graphql/examples/federation/reviews/ReviewsQuery.kt
examples/federation/supergraph.yaml
generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorHooks.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/FederationVersionUtils.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/LinkDirective.kt
generator/graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/generator/federation/directives/OverrideDirective.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/authenticated/AuthenticatedTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/compose/ComposeDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/contact/ContactDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/interfaceObject/InterfaceObjectTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/link/LinkDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/override/OverrideDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/policy/PolicyDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/requiresscope/RequiresScopesDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/execution/ServiceQueryResolverTest.kt
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
website/docs/schema-generator/federation/apollo-federation.mdx
website/versioned_docs/version-7.x.x/schema-generator/federation/apollo-federation.mdx
website/versioned_docs/version-8.x.x/schema-generator/federation/apollo-federation.mdx
website/versioned_docs/version-8.x.x/schema-generator/federation/federated-directives.md

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2088 to 8.x.x

feat(8.x.x): support federation 2.7 (#2088)

---

website/versioned_docs/version-8.x.x/schema-generator/writing-schemas/scalars.md

Removed the duplicated "up" in the docs.

docs: Removed the duplicated "up"

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kParameterExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kTypeExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCache.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KParameterExtensionsKtTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KTypeExtensionsKtTest.kt

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2109 for 7.x.x branch
https://github.com/ExpediaGroup/graphql-kotlin/issues/1570

feat: try isAssignableFrom instead of DFS isSubclassOf
