README.md
src/main/kotlin/com/expedia/graphql/KotlinDataFetcher.kt
src/main/kotlin/com/expedia/graphql/schema/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/exceptions/CouldNotGetNameOfEnumException.kt

Update information in the README and javadocs.

docs: add more documentation and javadocs

---

README.md

* Clean up invalid kotlin code
* Wrap the annotation headers in code formatting
* Add new section for `@Deprecated` documentation

update annotation docs

---

README.md
example/pom.xml
example/src/main/kotlin/com.expedia.graphql.sample/Application.kt
example/src/main/kotlin/com.expedia.graphql.sample/context/MyGraphQLContext.kt
example/src/main/kotlin/com.expedia.graphql.sample/context/MyGraphQLContextBuilder.kt
example/src/main/kotlin/com.expedia.graphql.sample/extension/CustomSchemaGeneratorHooks.kt
example/src/main/kotlin/com.expedia.graphql.sample/model/Animal.kt
example/src/main/kotlin/com.expedia.graphql.sample/model/ContextualResponse.kt
example/src/main/kotlin/com.expedia.graphql.sample/model/Widget.kt
example/src/main/kotlin/com.expedia.graphql.sample/mutation/Mutation.kt
example/src/main/kotlin/com.expedia.graphql.sample/mutation/SimpleMutation.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/ContextualQuery.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/CustomScalarQuery.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/PolymorphicQuery.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/Query.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/SimpleQuery.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/WidgetQuery.kt
pom.xml
src/main/kotlin/com/expedia/graphql/annotations/GraphQLContext.kt
src/main/kotlin/com/expedia/graphql/annotations/GraphQLDirective.kt
src/main/kotlin/com/expedia/graphql/annotations/GraphQLExperimental.kt
src/main/kotlin/com/expedia/graphql/annotations/GraphQLIgnore.kt
src/main/kotlin/com/expedia/graphql/annotations/GraphQLInstrumentationIgnore.kt
src/main/kotlin/com/expedia/graphql/schema/KotlinDataFetcher.kt
src/main/kotlin/com/expedia/graphql/schema/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/SchemaGeneratorConfig.kt
src/main/kotlin/com/expedia/graphql/schema/directives/ExperimentalDirective.kt
src/main/kotlin/com/expedia/graphql/schema/schemaAnnotations.kt

* sample example app that exposes queries/mutations used in the README
* fixes selection of data fetcher for classes implementing interfaces
* add support for directives

Add example app

---

src/main/kotlin/com/expedia/graphql/annotations/GraphQLID.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/defaultGraphQLScalars.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt

This PR addresses the issue #51

Add support for GraphQL Scalar ID

---

src/main/kotlin/com/expedia/graphql/schema/exceptions/InvalidSchemaException.kt
src/main/kotlin/com/expedia/graphql/toSchema.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt

Documents https://github.com/ExpediaDotCom/graphql-kotlin/issues/57 with unit tests

test: add more unit tests for checks

---

detekt_baseline.xml
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/state/SchemaGeneratorState.kt
src/test/kotlin/com/expedia/graphql/schema/generator/DirectiveTests.kt

Some more clean up so we can continue breaking up `SchemaGenerator`

refactor: add schema state

---

pom.xml
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/schemaFilters.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchenaFiltersTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/TypesCacheTest.kt
src/test/kotlin/com/expedia/graphql/schema/models/KGraphQLTypeTest.kt

* Some internal code clean up and adding more unit tests.
* Also add jacoco, even if it is not the best with Kotlin generated code, it can still be helpful on basic functions.

feat: add jacoco reports with tests

---

pom.xml
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/test/kotlin/com/expedia/graphql/schema/generator/DirectiveTests.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/schema/hooks/SchemaGeneratorHooksTest.kt

to be sure that all the unit tests are executed properly

Reconfigure surefire plugin

---

detekt_baseline.xml
src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/enumType.kt
src/test/kotlin/com/expedia/graphql/schema/generator/types/EnumTypeTest.kt

Adds missing description & deprecation annotation processing for enum classes and values.
Closes #76

Descriptions & deprecation for enums

---

src/main/kotlin/com/expedia/graphql/schema/extensions/annotationExtensions.kt
src/test/kotlin/com/expedia/graphql/schema/generator/DirectiveTests.kt

Resolves https://github.com/ExpediaDotCom/graphql-kotlin/issues/79

Remove directive info from descriptions

---

.travis.yml
.travis/deploy.sh
pom.xml

https://coveralls.io/github/ExpediaDotCom/graphql-kotlin

test: push reports to codecov.io

---

example/pom.xml
example/src/main/kotlin/com.expedia.graphql.sample/dataFetchers/SpringDataFetcherFactory.kt
example/src/main/kotlin/com.expedia.graphql.sample/query/NestedQueries.kt
pom.xml
src/main/kotlin/com/expedia/graphql/schema/generator/directive/DirectiveWiringHelper.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/GraphQLTypeExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/TypesCacheTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/directive/DirectiveWiringHelperTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/models/KGraphQLTypeTest.kt

Resolves https://github.com/ExpediaDotCom/graphql-kotlin/issues/92

Update to GraphQL Java 11

---

example/src/main/kotlin/com.expedia.graphql.sample/query/SimpleQuery.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kClassExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/kTypeExtensions.kt
src/main/kotlin/com/expedia/graphql/schema/generator/SchemaGenerator.kt
src/main/kotlin/com/expedia/graphql/schema/generator/TypeBuilder.kt
src/main/kotlin/com/expedia/graphql/schema/generator/TypesCache.kt
src/main/kotlin/com/expedia/graphql/schema/generator/types/ListTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/KClassExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/PolymorphicTests.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/types/ListTypeTest.kt

Resolves https://github.com/ExpediaDotCom/graphql-kotlin/issues/90

Add support for Kotlin builtin arrays of primitives

---

example/pom.xml
pom.xml

Following the steps here: https://github.com/ExpediaDotCom/graphql-kotlin/wiki/Release
https://github.com/ExpediaDotCom/graphql-kotlin/releases/tag/0.0.26

0.0.27-SNAPSHOT

---

src/main/kotlin/com/expedia/graphql/extensions/deepName.kt
src/main/kotlin/com/expedia/graphql/schema/extensions/graphQLTypeExtensions.kt
src/test/kotlin/com/expedia/graphql/schema/dataFetchers/CustomDataFetcherTests.kt
src/test/kotlin/com/expedia/graphql/schema/extensions/GraphQLTypeExtensionsTest.kt
src/test/kotlin/com/expedia/graphql/schema/generator/SchemaGeneratorTest.kt
src/test/kotlin/com/expedia/graphql/schema/hooks/SchemaGeneratorHooksTest.kt

It's a very handy utility method

fix: make deepName public

---

.travis.yml

Need to run install so that snapshot is available for example to compile

build: compile example as well

---

example/pom.xml
pom.xml

* Mockk `1.8.9.kotlin13` -> `1.8.13.kotlin13`
* jackson-module-kotlin `2.9.3` -> `2.9.8`
* RxJava (test) `2.1.0` -> `2.2.4`
* Exclude kotlin reflect from dependencies so we have a single tested version

build: update versions

---

example/pom.xml
pom.xml

Update the snapshot after [0.0.29](https://github.com/ExpediaDotCom/graphql-kotlin/releases/tag/0.0.29) release

build: 0.0.30-SNAPSHOT

---

src/main/kotlin/com/expedia/graphql/toSchema.kt

We imported the wrong exception to throw

fix: label correct exception

---

README.md

doc: update maven central link

---

example/pom.xml
pom.xml

First commit after release https://github.com/ExpediaDotCom/graphql-kotlin/releases/tag/0.0.30

build: 0.0.31-SNAPSHOT

---

example/pom.xml
pom.xml

Release https://github.com/ExpediaDotCom/graphql-kotlin/releases/tag/0.0.31

0.0.32-SNAPSHOT

---

example/src/main/kotlin/com/expedia/graphql/sample/validation/DataFetcherExecutionValidator.kt
src/main/kotlin/com/expedia/graphql/KotlinDataFetcher.kt
src/main/kotlin/com/expedia/graphql/hooks/DataFetcherExecutionPredicate.kt
src/test/kotlin/com/expedia/graphql/KotlinDataFetcherTest.kt
src/test/kotlin/com/expedia/graphql/dataFetchers/DataFetchPredicateTests.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/134
Remove multiple abstract methods in favor of a single interface method

refactor: simplify predicate

---

src/main/kotlin/com/expedia/graphql/generator/types/InterfaceTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/ObjectTypeBuilder.kt
src/test/kotlin/com/expedia/graphql/integration/NodeGraphTest.kt
src/test/kotlin/com/expedia/graphql/integration/RecursiveInterfaceTest.kt
src/test/kotlin/com/expedia/graphql/integration/RecursiveUnionTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/141

fix: recursive interfaces

---

README.md

We have the wiki but it is not easily findable

doc: update readme with example

---

example/pom.xml
pom.xml

Next PR after release https://github.com/ExpediaDotCom/graphql-kotlin/releases/tag/0.0.32
This PR will save us the manual step of doing this everytime https://github.com/ExpediaDotCom/graphql-kotlin/pull/142

build: 0.0.33-SNAPSHOT

---

example/pom.xml
pom.xml

Woohoo! Automatic branches! https://travis-ci.org/ExpediaDotCom/graphql-kotlin/builds/479606179

travis: Upgrade to next snapshot (Build 542)

---

example/pom.xml
pom.xml

travis: Upgrade to next snapshot (Build 565)

---

.travis/update-version.sh

Old message
```
travis: Upgrade to next snapshot (Build 565)
```
New message
```
build: 0.0.33-SNAPSHOT (Travis Build 565)
```

feat: add version number to travis commit message

---

example/pom.xml
pom.xml

build: 0.1.1-SNAPSHOT (Travis Build 577)

---

src/main/kotlin/com/expedia/graphql/extensions/deepName.kt

There is a util function already that does this for us

refactor: simplify the deep name logic

---

detekt.yml
example/pom.xml
example/src/main/kotlin/com/expedia/graphql/sample/Application.kt
example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/CustomDataFetcherFactoryProvider.kt
example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/SpringDataFetcherFactory.kt
pom.xml
src/main/kotlin/com/expedia/graphql/SchemaGeneratorConfig.kt
src/main/kotlin/com/expedia/graphql/exceptions/CouldNotCastArgumentException.kt
src/main/kotlin/com/expedia/graphql/generator/types/MutationTypeBuilder.kt
src/main/kotlin/com/expedia/graphql/generator/types/QueryTypeBuilder.kt

Also add some very small changes that I have in my subscriptions branch that have no affect on behavior

Update library versions

---

src/test/kotlin/com/expedia/graphql/execution/FunctionDataFetcherTest.kt

This is the one main section we do not have coverage. Unit test changes only.

test: add a unit test for missing coverage

---

example/README.md

Add instructions in the folder for more context

Create example README

---

README.md

Keeping documentation up-to-date with more relevant terminology.

docs: update the readme

---

.github/release-drafter.yml

Using a GitHub app to do the release templating https://github.com/toolmantim/release-drafter

docs: add release template

---

src/main/kotlin/com/expedia/graphql/generator/extensions/kClassExtensions.kt
src/test/kotlin/com/expedia/graphql/generator/extensions/KClassExtensionsTest.kt

Fixes https://github.com/ExpediaDotCom/graphql-kotlin/issues/204

fix: allow for abstract properties and functions

---

.travis.yml

We need to allow other branches to be built and tags to trigger builds on all branches. I can then release 0.6.2 which should trigger a new tag and new release/publish

Update travis config on 0.6.x branch for tag release

---

.mvn/wrapper/maven-wrapper.properties

Upgrade the maven wrapper version. This will hopefully make builds just slightly faster with the latest maven version

upgrade maven wrapper version

---

.travis/update-version.sh

Add some more logging to the script because running the steps locally performs the correct changes

Add debug logging to update-versions.sh

---

graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/datafetchers/SpringDataFetcherFactory.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooks.kt
graphql-kotlin-spring-example/src/main/kotlin/com/expedia/graphql/sample/query/PolymorphicQuery.kt
graphql-kotlin-spring-example/src/test/kotlin/com/expedia/graphql/sample/extension/CustomSchemaGeneratorHooksTest.kt

No impact on any library code. All example app changes

fix some compile warnings

---

pom.xml

Update the Maven settings of contributors to the EG Open Source email and name

Update contributors to generic EG

---

.github/workflows/maven.yml

Try a simple Github action for PR checks

Github action for PR check

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
pom.xml

We need to update the script so that it also updates all the examples or just remove the version from the examples and pull the version from parent

build: 1.0.0-RC7-SNAPSHOT (Travis Build 991)

---

.travis/update-version.sh

just add everything as it publishes to new branch that has to be still manually merged

another attempt to fix update-version.sh script

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

:champagne: The script finally works!

build: 1.0.0-RC11-SNAPSHOT (Travis Build 1101)

---

LICENSE

Update the company name to match the Expedia Group open source standard and the name we use in all the source file license headers
[CONTRIBUTING.md](https://github.com/ExpediaGroup/graphql-kotlin/blob/master/CONTRIBUTING.md)

Update company name in license

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

Update to the next snapshot version

build: 1.0.0-RC12-SNAPSHOT (Travis Build 1148)

---

.github/workflows/publish-docs.yml

Publish the docusaurus build to the `gh-pages` branch on checkin

Create publish docs action

---

README.md

Update the link to the main url that will never be changed

Update README documentation link

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

build: 1.0.1-SNAPSHOT (Travis Build 1195)

---

docs/server/spring-beans.md
docs/server/spring-properties.md

[docs] update spring-server configuration details

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

build: 1.2.2-SNAPSHOT (Travis Build 1253)

---

detekt.yml
pom.xml

Update to the latest versions
Attempt to fix: https://github.com/ExpediaGroup/graphql-kotlin/issues/443

Upgrade dokka version

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

build: 1.2.3-SNAPSHOT (Travis Build 1265)

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/CustomDirectiveWiringFactory.kt
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/DirectiveBuilder.kt

Remove the guava library since all we are using it for is the case format changes
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/459

Remove guava for Kotlin builtin decapitalize

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

build: 1.3.1-SNAPSHOT (Travis Build 1294)

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

build: 1.4.1-SNAPSHOT (Travis Build 1303)

---

docs/blogs-and-videos.md
website/sidebars.json

Set up a page where we can reference other posts that may provide more details and examples

[docs] Add new blogs & videos page

---

docs/blogs-and-videos.md

[docs] Add GraphQL Summit 2019 video

---

.mvn/wrapper/maven-wrapper.properties

Update mvn wrapper version

---

examples/federation/base-app/src/test/kotlin/com/expediagroup/graphql/examples/model/WidgetTest.kt
examples/federation/extend-app/src/test/kotlin/com/expediagroup/graphql/examples/extend/WidgetTest.kt
examples/spring/pom.xml
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcherTest.kt
pom.xml

Update dependencies and update the build script to force unit tests in all packages, even examples

Update dependency versions

---

.github/workflows/publish-package.yml

Add a new action that published to Github package registry on release

Create publish GH Packages action

---

examples/federation/base-app/pom.xml
examples/federation/extend-app/pom.xml
examples/federation/pom.xml
examples/pom.xml
examples/spring/pom.xml
graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml
pom.xml

While we don't have timeline for releasing 2.0.0 this will allow us to start merging breaking API changes.

update to next major release

---

graphql-kotlin-federation/README.md

Updated broken links in the doc

---

docs/customizing-schemas/directives.md
docs/examples.md
docs/execution/data-fetching-environment.md
docs/getting-started.md
docs/writing-schemas/nested-queries.md
docs/writing-schemas/scalars.md

Fix some doc links. Going to update a few more

Update doc links

---

website/core/Footer.js
website/package-lock.json
website/package.json
website/sidebars.json
website/siteConfig.js

MIT License states that we just need to reference the license to use the source code. Expedia is free to add its own license on top of that.

Update website depencies and license notice

---

docs/getting-started.md
docs/server/spring-overview.md
website/sidebars.json

Update the overview page and provide more info for the subscription settings

Update the spring server docs

---

.github/workflows/pr-check.yml

Trying to fix the GH Action PR check
Build is failing here: https://github.com/ExpediaGroup/graphql-kotlin/pull/496

Update PR check formatting

---

docs/writing-schemas/interfaces.md

Update the interface docs on multiple level interfaces
https://github.com/ExpediaGroup/graphql-kotlin/issues/419

Update interface docs

---

graphql-kotlin-federation/pom.xml
graphql-kotlin-schema-generator/pom.xml
graphql-kotlin-spring-server/pom.xml

Add coverage checks in the build so they are not just checked on PRs

[build] enforce jacoco coverage check at build time

---

docs/execution/subscriptions.md
docs/server/subscriptions.md
website/sidebars.json

Update the docs for subscriptions describing the subprotocol we are using and link to this new page from the schema docs

Update subscription documentation

---

.github/workflows/pr-check.yml
.github/workflows/publish-docs.yml

Update the Github actions to use `checkout@v2` 
https://github.com/actions/checkout/releases/tag/v2.0.0

GitHub Actions checkout v2

---

docs/execution/contextual-data.md
docs/execution/data-fetching-environment.md
docs/execution/exceptions.md
docs/execution/fetching-data.md
docs/execution/subscriptions.md
docs/writing-schemas/scalars.md
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/query/DataAndErrorsQuery.kt
website/sidebars.json

Add information about execution and how to return partial data
None

[docs] information about execution and how to return partial data

---

.github/workflows/pr-check-docs.yml

Github Action checks out the repository and attempts to run [docusaurus-build](https://docusaurus.io/docs/en/commands#docusaurus-build) command.

[build] configure GH action PR check for documentation updates

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check-docs.yml
.github/workflows/pr-check.yml
README.md

Splitting up the GH action so we can link to a proper badge as otherwise it would show the last build status from either a PR check or master build.

[build] split GH continuous integration action in PR and master build

---

.github/workflows/release.yml

[build] fix release workflow

---

build.gradle.kts
graphql-kotlin-federation/build.gradle.kts
graphql-kotlin-schema-generator/build.gradle.kts
graphql-kotlin-spring-server/build.gradle.kts

Add missing jacoco test coverage verification

[build] enforce jacoco coverage

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGenerator.kt

Open FederatedSchemaGenerator to allow additional customization from #593 in federated schemas as well.

Open FederatedSchemaGenerator

---

.github/workflows/publish-docs.yml
website/siteConfig.js

Fix the publish docs action by pushing the correct directory
#617

[docs] Fix publish directory

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt

- changed the do-while loop to while loop. 
- for design quality, moved to creation of new currentlyProcessedTypes inside while loop vs reusing them.

refactor generateAdditionalTypes()

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties

Update dependencies to latest versions as well as Gradle wrapper. There was not jar update with the wrapper change.

Update dependencies to latest versions

---

docs/spring-server/subscriptions.md

Update subscriptions.md formatting on subtitle
None

Update subscriptions.md formatting on subtitle

---

build.gradle.kts

[build] dropping idea plugin as it keeps messing up my workspace

---

gradle.properties

release notes
https://github.com/classgraph/classgraph/releases

classgraph 4.8.78

---

.github/workflows/continuous-integration.yml

Have the CI action run on the older version branches like `1.x.x` and `2.x.x`
n\a

Run CI on support branches

---

graphql-kotlin-client/README.md
graphql-kotlin-client/src/main/kotlin/com/expediagroup/graphql/client/GraphQLClient.kt
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojo.kt

* client implements closeable
* fix GenerateClientMojo custom scalar parameter definition to match annotation
#707

GraphQL client fixes

---

.github/workflows/continuous-integration.yml

The valid config option is `file` not `yml`
https://github.com/codecov/codecov-action
Warning message: https://github.com/ExpediaGroup/graphql-kotlin/actions/runs/115991229
```
Unexpected input 'yml', valid inputs are ['name', 'token', 'file', 'flags', 'fail_ci_if_error']
```

Update codecov config

---

examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/LowercaseSchemaDirectiveWiring.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/SpecificValueOnlySchemaDirectiveWiring.kt
examples/spring/src/main/kotlin/com/expediagroup/graphql/examples/directives/StringEvalSchemaDirectiveWiring.kt
gradle.properties
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/AnyTest.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/directives/KotlinFieldDirectiveEnvironment.kt
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensions.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/extensions/GraphQLSchemaExtensionsTest.kt
graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/spring/routes/RouteConfigurationIT.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/introspectSchema.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/IntrospectSchemaTest.kt

https://github.com/graphql-java/graphql-java/releases/tag/v15.0

update to graphql-java 15.0

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategy.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/execution/FlowSubscriptionExecutionStrategyTest.kt

In graphql-java 15, changes were made to SubscriptionExecutionStrategy
to allow for DataFetcherResults to be returned, and to instrument
the results of a subscription properly.  This updates the Flow
strategy with the same changes and adds tests for both changes.
See https://github.com/graphql-java/graphql-java/pull/1804
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/608

Port graphql-java 15 subscription changes to Flow strategy

---

docs/plugins/gradle-plugin.md
plugins/graphql-kotlin-gradle-plugin/README.md

[docs] fix copy+paste error on downloadSDL task

---

examples/federation/gateway/package-lock.json
examples/federation/gateway/package.json

Upgrade dependency versions of the example gateway
https://github.com/ExpediaGroup/graphql-kotlin/pull/751
https://github.com/ExpediaGroup/graphql-kotlin/pull/752

Upgrade federation gateway dependency versions

---

README.md
docs/federated/apollo-federation.md
docs/getting-started.md
docs/schema-generator/execution/contextual-data.md
docs/schema-generator/schema-generator-getting-started.md
docs/spring-server/http-request-response.md
docs/spring-server/spring-overview.md
graphql-kotlin-federation/README.md
graphql-kotlin-schema-generator/README.md
graphql-kotlin-spring-server/README.md
website/sidebars.json

This is by no-means a complete update of the docs, but this at least creates some basic pages that we can continue to add content to.
See https://github.com/ExpediaGroup/graphql-kotlin/issues/765

[docs] Add server http req/res page

---

README.md
docs/blogs-and-videos.md

Added a new README section for blog posts with two recent posts
n/a

[docs] add 2 blog posts to readme

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/directives/KeyDirective.kt

Update Javadoc to clarify repeated directive issue.
follow up to https://github.com/ExpediaGroup/graphql-kotlin/pull/787/

[federation] update @key directive javadoc

---

.github/workflows/release.yml

This PR does not include any functional changes.

[build] update release build secrets

---

graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/types/generateInputProperty.kt
graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/OptionalInputSchemaTest.kt

Do not unwrap the additional types for either nullability or lists
Fixes https://github.com/ExpediaGroup/graphql-kotlin/issues/828

[generator] Nullability additional input checks

---

docs/blogs-and-videos.md

Add the recorded virtual conference video for GOTO Chicago 2020
N\A

Add GOTO Chicago video

---

README.md
docs/schema-generator/execution/contextual-data.md
docs/spring-server/spring-graphql-context.md
graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/execution/FunctionDataFetcher.kt

Documentation: Fix typos and a broken link

---

graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/test/integration/InterfaceOfInterfaceTest.kt

Just adding an additional unit test for documentation and verification purposes
N\A

Add test to verify interface implementations can be ignored

---

docs/graphql-java-comparison.md
website/sidebars.json

Add a basic page the shows a comparison between creating a schema in graphql-java and graphql-kotlin.
https://github.com/ExpediaGroup/graphql-kotlin/issues/765

[docs] Add a comparison to graphql-java

---

plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLClientIT.kt
plugins/graphql-kotlin-plugin-core/src/test/resources/testSchema.graphql

Backport of https://github.com/ExpediaGroup/graphql-kotlin/pull/883 to 3.x.x branch
Fixes: #864

[client][3.x.x] fix generation of duplicate classes

---

README.md

README: fix broken URL

---

graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorHooks.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/execution/EntityResolver.kt
graphql-kotlin-federation/src/main/kotlin/com/expediagroup/graphql/federation/types/_Entity.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/FederatedSchemaGeneratorTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/execution/FederatedQueryResolverTest.kt
graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/federation/types/EntityTest.kt

Refactor the code to use constants and separate into functions. Just some small minor improvements 
N\A

Refactor federation code for readability

---

examples/build.gradle.kts
examples/federation/base-app/build.gradle.kts
examples/federation/extend-app/build.gradle.kts
examples/spark/build.gradle.kts
examples/spring/build.gradle.kts
gradle.properties

Also updates Jackson dependency to `2.11.3`.
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/850

[server] update to SpringBoot 2.3

---

docs/plugins/gradle-plugin.md

refactor(doc): change to intended syntax usage

---

docs/schema-generator/execution/fetching-data.md

Fix some typos and links in the data fetching docs
N\A

Update data fetching docs

---

plugins/graphql-kotlin-plugin-core/README.md
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/GraphQLClientGeneratorContext.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/extensions/DocumentExtensions.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateGraphQLObjectTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateInterfaceTypeSpec.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generatePropertySpecs.kt
plugins/graphql-kotlin-plugin-core/src/main/kotlin/com/expediagroup/graphql/plugin/generator/types/generateTypeName.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLInputObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/kotlin/com/expediagroup/graphql/plugin/generator/types/GenerateGraphQLObjectTypeSpecIT.kt
plugins/graphql-kotlin-plugin-core/src/test/resources/testSchema.graphql

See: https://github.com/ExpediaGroup/graphql-kotlin/pull/948 for details
Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/941

[3.x.x/plugins] backport fix for generation of self referencing types

---

examples/README.md

[docs] fixing examples readme

---

README.md

Removing generic OSS EG email in favor of discussions and slack.

[docs] update contact info

---

examples/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/6.7.1/release-notes.html

[build] update Gradle version to 6.7.1

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check-docs.yml
.github/workflows/pr-check.yml
.github/workflows/publish-latest-docs.yml
.github/workflows/release-code.yml
.github/workflows/release-docs.yml

Timeouts were put under `jobs` instead of `jobs.<job_name>`

[build] fix GH action timeouts

---

examples/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

https://docs.gradle.org/6.8/release-notes.html

[build] update Gradle wrapper to 6.8

---

examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/subscriptions/SimpleSubscriptionIT.kt

Attempt at making runtime more consistent for `SimpleSubscriptionIT` we can have a single client that connects to the running port that can execute different requests
Failing PR tests, not locally.

Update simple subscription test to use single client

---

build.gradle.kts
clients/graphql-kotlin-ktor-client/build.gradle.kts
clients/graphql-kotlin-spring-client/src/test/kotlin/com/expediagroup/graphql/client/spring/GraphQLWebClientTest.kt
docs/client/client-customization.md
examples/build.gradle.kts
examples/server/ktor-server/build.gradle.kts
examples/server/ktor-server/gradle.properties
examples/server/spring-server/src/test/kotlin/com/expediagroup/graphql/examples/server/spring/subscriptions/SimpleSubscriptionIT.kt
generator/graphql-kotlin-federation/build.gradle.kts
generator/graphql-kotlin-schema-generator/build.gradle.kts
gradle.properties
plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginAbstractIT.kt
servers/graphql-kotlin-spring-server/build.gradle.kts
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SpringGraphQLSubscriptionHandler.kt

Dependency updates:
* Kotlin 1.4.21
* Kotlin Coroutines 1.4.2
* Spring Boot 2.4.2
* Ktor 1.5
JaCoCo branch coverage dropped because of https://github.com/jacoco/jacoco/issues/1126, once new version of Jacoco is released we can bump it up again.
https://github.com/gradle/gradle/issues/15893 - Issue with missing Gradle module metadata when referencing Maven local
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/1020

[build] update to Kotlin 1.4, Spring Boot 2.4.2 and Ktor 1.5

---

generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/CompletableFutureTest.kt

Just a simple unit test addition. No code changes
https://github.com/ExpediaGroup/graphql-kotlin/discussions/1029

Add tests to show use of completable future wrappers

---

gradle.properties

Update to the latest version which includes some bug fixes
https://github.com/graphql-java/graphql-java/releases/tag/v16.2

Update graphql-java 16.2

---

website/static/index.html

Resolves: https://github.com/ExpediaGroup/graphql-kotlin/issues/1043

[docs] updating invalid refresh link in index.html

---

.github/workflows/continuous-integration.yml
.github/workflows/pr-check-docs.yml
.github/workflows/pr-check.yml
.github/workflows/publish-latest-docs.yml
.github/workflows/release-docs.yml
website/package.json
website/static/index.html

Update the build commands and publishing directory for GH Actions
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/1054

Update website publish

---

website/static/index.html

Update redirect: https://expediagroup.github.io/graphql-kotlin/
https://github.com/ExpediaGroup/graphql-kotlin/pull/1055

Update index redirect

---

website/docs/schema-generator/customizing-schemas/advanced-features.md
website/docusaurus.config.js
website/static/index.html
website/versioned_docs/version-3.x.x/schema-generator/customizing-schemas/advanced-features.md
website/versioned_docs/version-4.x.x/schema-generator/customizing-schemas/advanced-features.md

https://github.com/ExpediaGroup/graphql-kotlin/pull/1056

Add docs back to url

---

website/static/index.html

Add trailing slash

---

website/docs/server/spring-server/spring-subscriptions.md

Add some basic docs around when and how the subscription hooks can be used.
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/586

Add documentation for subscription hooks

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/PlaygroundRouteConfiguration.kt

Reactive context-path added to Playground Route configuration.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1097

Reactive context-path added to Playground

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/OptionalInputQuery.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateArgumentTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/OptionalInputTest.kt

Add unit tests and examples for optional input arguments. This does not fix any issues as I can not reproduce the issue. I am investigating further on the other open PR
https://github.com/ExpediaGroup/graphql-kotlin/pull/1100

Add unit tests for optional input wrappers

---

examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/hooks/CustomSchemaGeneratorHooks.kt
examples/server/spring-server/src/main/kotlin/com/expediagroup/graphql/examples/server/spring/query/SimpleQuery.kt
website/docs/schema-generator/writing-schemas/lists.md

Add docs and examples for how to include support for `Set`, even if it is not recommended
https://github.com/ExpediaGroup/graphql-kotlin/issues/201
https://github.com/ExpediaGroup/graphql-kotlin/discussions/1110

Add docs for set support

---

website/docs/blogs-and-videos.md

[docs] add case studies

---

website/docs/schema-generator/customizing-schemas/directives.md

The link was dead, so I updated it.

fix: update link to example app

---

RELEASING.md
website/docs/schema-generator/execution/async-models.md
website/versioned_docs/version-3.x.x/contributors/release-proc.md
website/versioned_docs/version-3.x.x/schema-generator/execution/async-models.md

Replace old references to ExpediaDotCom with ExpediaGroup

---

website/docs/schema-generator/customizing-schemas/generator-config.md

Update links and page layout for config and hooks

Update links for config and hooks

---

clients/graphql-kotlin-client-serialization/build.gradle.kts
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/hooks/FlowSubscriptionSchemaGeneratorHooksTest.kt
gradle.properties
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/interface_diff_selection_sets/differentselectionsetquery/BasicInterface.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/interface_diff_selection_sets/differentselectionsetquery/BasicInterface2.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/interface_impl_diff_selection_sets/differentselectionsetquery/BasicInterface.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/interface_impl_diff_selection_sets/differentselectionsetquery/BasicInterface2.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/interface_named_fragments/interfacewithnamedfragmentsquery/BasicInterface.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/object_diff_selection_set/differentselectionsquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/object_diff_sub_selection/differentsubselectionquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/object_diff_sub_selection/differentsubselectionquery/DetailsObject2.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/object_named_fragments/objectwithnamedfragmentquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/reuse_types/reusedtypesquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/generator/union_diff_selection_set2/differentselectionsetquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/custom_scalars/scalars/UUID.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/interface/interfacewithinlinefragmentsquery/BasicInterface.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/jackson/object/complexobjectquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/custom_scalars/scalars/UUID.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/firstquery/DetailsObject.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/multiple_queries/scalars/UUID.kt
plugins/client/graphql-kotlin-client-generator/src/test/data/kotlinx/object/complexobjectquery/DetailsObject.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLDownloadSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLIntrospectSchemaTaskIT.kt

Update to Kotlin 1.5 and all its recommend peer dependencies
https://kotlinlang.org/docs/releases.html#release-details

Update to kotlin 1.5

---

generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/utils/FunctionReturnTypesKtTest.kt

Add a few more unit tests to catch any possible breaking edge cases mentioned in https://github.com/ExpediaGroup/graphql-kotlin/pull/1150
https://github.com/ExpediaGroup/graphql-kotlin/pull/1150#discussion_r633867794

Update unit tests for lists of lists

---

website/docs/schema-generator/writing-schemas/arguments.md

Update the docs with some more clear descriptions and links to newer features.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1202

Update docs on arguments to make it clear defaults are required

---

website/docs/server/spring-server/spring-schema.md

Fix invalid link in documentation

---

website/docs/plugins/gradle-plugin-usage.mdx

Broken link to code
Resolves https://github.com/ExpediaGroup/graphql-kotlin/issues/1205

Fix the scalar converter link

---

clients/graphql-kotlin-client-serialization/build.gradle.kts
gradle.properties

Publishing of the latest release is failing because of nested dependecies trying to resolve this pom which doesn't exist
https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
https://github.com/ExpediaGroup/graphql-kotlin/actions/workflows/release-code.yml

Update dependecy versions

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/FunctionDataFetcher.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/KotlinDataFetcherFactoryProvider.kt

Simplify passing variables into coroutine scope, use other
Dispatcher etc.
No related issue. *Possibly* helpful to https://github.com/line/armeria/issues/3785

Expose CoroutineContext as constructor argument

---

examples/federation/base-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/base/schema/Widget.kt
examples/federation/base-app/src/test/kotlin/com/expediagroup/graphql/examples/federation/base/schema/WidgetTest.kt
examples/federation/extend-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/extend/schema/Widget.kt
examples/federation/extend-app/src/main/kotlin/com/expediagroup/graphql/examples/federation/extend/schema/WidgetResolver.kt
examples/federation/gateway/package-lock.json
examples/federation/gateway/package.json

Add example of how to use the requires directive and show it works with array

Add example which requires an external array

---

gradle.properties

Fixes #1272, which was caused by a classgraph issue:
https://github.com/classgraph/classgraph/issues/579
Upgrading to classgraph 4.2.131 corrects this problem.
Fixes #1272

Upgrade classgraph to 4.2.131

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/utils/functionReturnTypes.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/utils/FunctionReturnTypesKtTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/DataFetcherResultListTest.kt

Updated schema generator to support return DataFetcherResult of list of DataFetcherResult

---

.github/release-drafter.yml

https://github.com/release-drafter/release-drafter/pull/1013

Release drafter now supports putting "other changes" in a category

---

website/docs/server/spring-server/spring-overview.mdx

May need to search throughout docs to find any other similar broken links.

Fix broken link

---

website/docs/server/data-loaders.md

Fix typo in data-loaders.md

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/SchemaGenerator.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/annotations/GraphQLUnion.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/annotationExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCache.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateGraphQLType.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/types/generateUnion.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/hooks/SchemaGeneratorHooksTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/AnnotationExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCacheTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/types/GenerateUnionTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/test/integration/CustomUnionAnnotationTest.kt
website/docs/schema-generator/writing-schemas/unions.md

Cherry pick into 5.x.x
https://github.com/ExpediaGroup/graphql-kotlin/pull/1424
https://github.com/ExpediaGroup/graphql-kotlin/pull/1437

feat: support directives with union

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/filters/callableFilters.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/filters/propertyFilters.kt

adopting more inclusive language

use more inclusive terms

---

build.gradle.kts
gradle.properties
servers/graphql-kotlin-server/build.gradle.kts
servers/graphql-kotlin-server/src/benchmarks/kotlin/GraphQLRequestBenchmark.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLServer.kt
servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/extensions/requestExtensions.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/GraphQLServerTest.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/extensions/RequestExtensionsKtTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/subscriptions/SubscriptionWebSocketHandlerIT.kt
settings.gradle.kts

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/1301 to allow concurrent execution of batched requests on 5.x.x

feat:concurrent graphql server

---

website/package-lock.json
website/package.json

This is just a dependency bump to the released version of docusaurus.

[docs] update to v2.0.0 docusaurus

---

examples/client/src/integration/wiremock/__files/schema.graphql
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLSchemaExtensionsTest.kt
gradle.properties
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/DownloadSchemaTest.kt
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/IntrospectSchemaTest.kt
plugins/client/graphql-kotlin-client-generator/src/test/resources/introspectionResult.json
plugins/client/graphql-kotlin-client-generator/src/test/resources/testSchema.graphql
plugins/graphql-kotlin-gradle-plugin/src/integration/android/androidGraphQLClient/app/schema.graphql
plugins/graphql-kotlin-gradle-plugin/src/integration/client-generator/jacoco/schema.graphql
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/GraphQLGradlePluginIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/GraphQLGenerateSDLTaskIT.kt
plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/IntrospectionResult.json
plugins/graphql-kotlin-gradle-plugin/src/test/resources/mocks/schema.graphql
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/generate-sdl/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/introspectionResult.json
plugins/graphql-kotlin-maven-plugin/src/integration/wiremock/__files/testSchema.graphql
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/graphql/plugin/schema/GenerateSDLTest.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt

https://github.com/graphql-java/graphql-java/releases/tag/v19.1
most of changes are because of this PR to fix a typo in skip directive in graphql-java
https://github.com/graphql-java/graphql-java/pull/2915

feat: update graphql-java 19.1

---

website/docusaurus.config.js

[docs] update current version label to 7.x.x

---

website/docs/server/data-loader/data-loader-instrumentation.mdx

Update documentation of custom `DataLoaderInstrumentation`s
https://github.com/ExpediaGroup/graphql-kotlin/issues/1557

chore: update instrumentation documentation

---

gradle.properties

https://github.com/spring-projects/spring-boot/releases/tag/v2.7.5
ChangeSet: https://github.com/spring-projects/spring-boot/compare/v2.7.2...v2.7.5

update spring-boot to 2.7.5

---

servers/graphql-kotlin-spring-server/src/main/resources/graphql-graphiql.html

https://github.com/OneGraph/graphiql-explorer

feat: add graphiql explorer plugin

---

.github/workflows/federation-compatibility.yml

See: https://github.com/marketplace/actions/apollo-federation-subgraph-compatibility
N/A

build: fed compatibility test action should fail if any test failed

---

clients/graphql-kotlin-client-jackson/build.gradle.kts
clients/graphql-kotlin-client-serialization/build.gradle.kts
clients/graphql-kotlin-ktor-client/build.gradle.kts
clients/graphql-kotlin-spring-client/build.gradle.kts
executions/graphql-kotlin-dataloader-instrumentation/build.gradle.kts
generator/graphql-kotlin-federation/build.gradle.kts
gradle/libs.versions.toml
plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/graphql-kotlin-maven-plugin/build.gradle.kts
plugins/schema/graphql-kotlin-federated-hooks-provider/build.gradle.kts
plugins/schema/graphql-kotlin-hooks-provider/build.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/build.gradle.kts
servers/graphql-kotlin-server/build.gradle.kts
servers/graphql-kotlin-spring-server/build.gradle.kts
settings.gradle.kts

See: https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:type-safe-project-accessors

build: use typesafe project accessors

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/FederatedSchemaAutoConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/NonFederatedSchemaAutoConfiguration.kt

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/1641
will update v6 docs after this

feat: config property to print schema

---

website/versioned_docs/version-6.x.x/server/spring-server/spring-properties.md

follow up PR of https://github.com/ExpediaGroup/graphql-kotlin/pull/1645

chore: update v6 docs with printSchema config

---

website/docs/schema-generator/federation/federated-directives.md
website/versioned_docs/version-6.x.x/schema-generator/federation/federated-directives.md

docs: update `@composeDirective` usage documentation

---

.github/workflows/federation-integration.yml
.github/workflows/pr-check-federation.yml

build: fix fed action permissions

---

examples/server/ktor-server/README.md
examples/server/spring-server/README.md

https://github.com/ExpediaGroup/graphql-kotlin/discussions/1761

chore: update examples README to point to graphiql

---

website/versioned_docs/version-6.x.x/schema-generator/writing-schemas/arguments.md

Update arguments docs with DFE link

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt

feat: avoid calling the DFE supplier in batching instrumentations

---

integration/gradle-plugin-integration-tests/client-generator/multiple-tasks/build.gradle.kts
integration/gradle-plugin-integration-tests/client-generator/multiple-tasks/schema.graphql
integration/gradle-plugin-integration-tests/client-generator/multiple-tasks/src/main/resources/queries/parentDir/ParentDirQuery.graphql
integration/gradle-plugin-integration-tests/client-generator/multiple-tasks/src/main/resources/queries/parentDir/subDir/SubDirQuery.graphql
integration/maven-plugin-integration-tests/integration/generate-client/src/main/resources/subDir/SubDirQuery.graphql
integration/maven-plugin-integration-tests/integration/generate-client/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientMojoTest.kt
plugins/graphql-kotlin-gradle-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/gradle/tasks/AbstractGenerateClientTask.kt
plugins/graphql-kotlin-maven-plugin/README.md
plugins/graphql-kotlin-maven-plugin/src/main/kotlin/com/expediagroup/graphql/plugin/maven/GenerateClientAbstractMojo.kt

Support subdirectories for query files in client maven plugin
https://github.com/ExpediaGroup/graphql-kotlin/issues/1807

support subdirectories in maven/gradle client plugins

---

executions/graphql-kotlin-dataloader/src/main/kotlin/com/expediagroup/graphql/dataloader/KotlinDataLoaderRegistry.kt

feat : handle thread safe issue for getCurrentFutures(#1843)

---

servers/graphql-kotlin-ktor-server/src/main/kotlin/com/expediagroup/graphql/server/ktor/KtorGraphQLRequestParser.kt

Added open modifier for class KtorGraphQLRequestParser to support custom logic for request parser

open class KtorGraphQLRequestParser

---

website/docs/client/client-overview.mdx
website/versioned_docs/version-3.x.x/client/client-overview.md
website/versioned_docs/version-4.x.x/client/client-overview.mdx
website/versioned_docs/version-5.x.x/client/client-overview.mdx
website/versioned_docs/version-6.x.x/client/client-overview.mdx

Missed updates to documentation after the rename of the Maven mojos in https://github.com/ExpediaGroup/graphql-kotlin/pull/719

chore: Update plugin goals in documentation

---

executions/graphql-kotlin-automatic-persisted-queries/src/main/kotlin/com/expediagroup/graphql/apq/extensions/executionInputExtensions.kt

cherry pick https://github.com/ExpediaGroup/graphql-kotlin/pull/1906/commits

fix: create MessageDigest when needed

---

servers/graphql-kotlin-server/src/main/kotlin/com/expediagroup/graphql/server/execution/GraphQLRequestHandler.kt
servers/graphql-kotlin-server/src/test/kotlin/com/expediagroup/graphql/server/execution/GraphQLRequestHandlerTest.kt

In case of Subscription initiation failure, for example exception thrown after some custom authentication/authorisation mechanism throws exception, error was not passed through as response body, because of exception:
```
java.lang.NullPointerException: graphQL.execute(input)
…<Flow<ExecutionResult>>() must not be null
at com.expediagroup.graphql.server.execution.GraphQLRequestHandler.executeSubscription(GraphQLRequestHandler.kt:167)
```
-

Handle exception on subscription initialization

---

clients/graphql-kotlin-ktor-client/build.gradle.kts
clients/graphql-kotlin-spring-client/build.gradle.kts
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaGeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/FederatedSchemaV2GeneratorTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/compose/ComposeDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/contact/ContactDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/link/LinkDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/policy/PolicyDirectiveTest.kt
generator/graphql-kotlin-federation/src/test/kotlin/com/expediagroup/graphql/generator/federation/directives/requiresscope/RequiresScopesDirectiveTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLSchemaExtensionsTest.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/custom.graphql
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/federated.graphql
integration/gradle-plugin-integration-tests/src/integration/resources/sdl/schema.graphql
integration/maven-plugin-integration-tests/integration/generate-sdl-federated/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/generate-sdl-hooks/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/generate-sdl/src/test/kotlin/com/expediagroup/graphql/plugin/maven/GenerateSDLMojoTest.kt
integration/maven-plugin-integration-tests/integration/wiremock/__files/testSchema.graphql
plugins/client/graphql-kotlin-client-generator/build.gradle.kts
plugins/client/graphql-kotlin-client-generator/src/test/kotlin/com/expediagroup/graphql/plugin/client/IntrospectSchemaTest.kt
plugins/graphql-kotlin-gradle-plugin/build.gradle.kts
plugins/schema/graphql-kotlin-sdl-generator/src/integrationTest/kotlin/com/expediagroup/graphql/plugin/schema/GenerateCustomSDLTest.kt
plugins/schema/graphql-kotlin-sdl-generator/src/test/kotlin/com/expediagroup/graphql/plugin/schema/GenerateSDLTest.kt
servers/graphql-kotlin-ktor-server/src/test/kotlin/com/expediagroup/graphql/server/ktor/GraphQLPluginTest.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLConfigurationProperties.kt
servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLSchemaConfiguration.kt
servers/graphql-kotlin-spring-server/src/test/kotlin/com/expediagroup/graphql/server/spring/routes/RouteConfigurationIT.kt

NOTE: We are upgrading to latest dependencies that are still using Kotlin 1.8

chore: update to latest dependencies

---

website/docs/server/ktor-server/ktor-overview.mdx

add `need`
original page: https://opensource.expediagroup.com/graphql-kotlin/docs/server/ktor-server/ktor-overview#configuration

Fix typo of `ktor-overview` website page

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt

https://github.com/ExpediaGroup/graphql-kotlin/pull/2006

feat(batching): v7 remove execution if a given operation completes with an exception

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/level/state/ExecutionLevelDispatchedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt

https://github.com/ExpediaGroup/graphql-kotlin/pull/2006

feat(batching): v6 remove execution if a given operation completes with an exception

---

executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/extensions/CompletableFutureExtensions.kt
executions/graphql-kotlin-dataloader-instrumentation/src/main/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/state/SyncExecutionExhaustedState.kt
executions/graphql-kotlin-dataloader-instrumentation/src/test/kotlin/com/expediagroup/graphql/dataloader/instrumentation/syncexhaustion/DataLoaderSyncExecutionExhaustedInstrumentationTest.kt

cherry-pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2012

feat(batching): v7 synchronize executions when attempting to remove an entry

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLContextExtensions.kt

https://github.com/ExpediaGroup/graphql-kotlin/issues/2024

fix: graphql context plus map non null values

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/extensions/GraphQLContextExtensions.kt

cherry pick
https://github.com/ExpediaGroup/graphql-kotlin/pull/2026

fix: graphql context plus map non null values (#2026)

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLServerCodecConfiguration.kt

https://github.com/ExpediaGroup/graphql-kotlin/issues/2047

feat: remove enable webflux annotation

---

servers/graphql-kotlin-spring-server/src/main/kotlin/com/expediagroup/graphql/server/spring/GraphQLServerCodecConfiguration.kt

cherry pick 
https://github.com/ExpediaGroup/graphql-kotlin/commit/d3ad96077fc6d02471f996ef34c67066145acb15

feat: remove enable webflux annotation (#2048)

---

.github/workflows/build-examples.yml
.github/workflows/build-libraries.yml
.github/workflows/plugin-it.yml
.github/workflows/release-code.yml

chore: update upload-artifact to v4

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt

cherry-pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2096

feat(8.x.x): if getter exists do not attempt to compute it again (#2096)

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt

cherry-pick https://github.com/ExpediaGroup/graphql-kotlin/pull/2096

feat(6.x.x): if getter exists do not attempt to compute it again (#2096)

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/execution/SingletonPropertyDataFetcher.kt

for null returned values, log was happening and returning Unit

fix: log on else and return result of getter.call

---

generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kClassExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kParameterExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/extensions/kTypeExtensions.kt
generator/graphql-kotlin-schema-generator/src/main/kotlin/com/expediagroup/graphql/generator/internal/state/TypesCache.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KClassExtensionsTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KParameterExtensionsKtTest.kt
generator/graphql-kotlin-schema-generator/src/test/kotlin/com/expediagroup/graphql/generator/internal/extensions/KTypeExtensionsKtTest.kt

If this doesn't work, a cache need to be put in place.
https://github.com/ExpediaGroup/graphql-kotlin/issues/1570

feat: try isAssignableFrom instead of DFS isSubclassOf

---

gradle/libs.versions.toml

https://github.com/graphql-java/graphql-java/releases/tag/v22.4

feat: update graphql java
